// Auto-generated by BoltFFI. Do not edit.
@file:Suppress("unused", "RedundantVisibilityModifier", "MemberVisibilityCanBePrivate", "PropertyName", "FunctionName", "ClassName", "LocalVariableName", "SpellCheckingInspection", "NOTHING_TO_INLINE", "KotlinRedundantDiagnosticSuppress")

package dev.syncular.client

import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.atomic.AtomicLong
import kotlin.jvm.JvmInline
import java.time.Duration
import java.time.Instant
import java.util.UUID
import java.net.URI

class FfiException(val code: Int, message: String) : Exception(message)

private fun takeLastErrorMessage(): String =
    Native.boltffi_last_error_message().toString(Charsets.UTF_8)

private inline fun <T> useWireBytes(bytes: ByteArray, block: (java.nio.ByteBuffer) -> T): T {
    return block(java.nio.ByteBuffer.wrap(bytes).order(java.nio.ByteOrder.LITTLE_ENDIAN))
}

interface WireCodable {
    fun encode(writer: WireWriter)

    interface Decoder<T> {
        fun decode(reader: WireReader): T
    }
}

class WireReader {
    private val array: ByteArray?
    private val buffer: ByteBuffer?
    private var pos: Int = 0

    constructor(array: ByteArray) {
        this.array = array
        this.buffer = null
    }

    constructor(buffer: ByteBuffer) {
        this.array = null
        this.buffer = buffer.slice().order(ByteOrder.LITTLE_ENDIAN)
    }

    private fun byteAt(index: Int): Byte = array?.get(index) ?: buffer!!.get(index)

    private fun copyRange(start: Int, len: Int): ByteArray {
        val localArray = array
        if (localArray != null) {
            return localArray.copyOfRange(start, start + len)
        }
        val bytes = ByteArray(len)
        if (len == 0) return bytes
        val source = buffer!!.duplicate().order(ByteOrder.LITTLE_ENDIAN)
        source.position(start)
        source.limit(start + len)
        source.get(bytes)
        return bytes
    }

    @PublishedApi internal fun leI16(o: Int): Short {
        val localArray = array
        return if (localArray != null) {
            ((localArray[o].toInt() and 0xFF) or ((localArray[o + 1].toInt() and 0xFF) shl 8)).toShort()
        } else {
            buffer!!.getShort(o)
        }
    }

    @PublishedApi internal fun leI32(o: Int): Int {
        val localArray = array
        return if (localArray != null) {
            (localArray[o].toInt() and 0xFF) or
            ((localArray[o + 1].toInt() and 0xFF) shl 8) or
            ((localArray[o + 2].toInt() and 0xFF) shl 16) or
            ((localArray[o + 3].toInt() and 0xFF) shl 24)
        } else {
            buffer!!.getInt(o)
        }
    }

    @PublishedApi internal fun leI64(o: Int): Long {
        val localArray = array
        return if (localArray != null) {
            (localArray[o].toLong() and 0xFFL) or
            ((localArray[o + 1].toLong() and 0xFFL) shl 8) or
            ((localArray[o + 2].toLong() and 0xFFL) shl 16) or
            ((localArray[o + 3].toLong() and 0xFFL) shl 24) or
            ((localArray[o + 4].toLong() and 0xFFL) shl 32) or
            ((localArray[o + 5].toLong() and 0xFFL) shl 40) or
            ((localArray[o + 6].toLong() and 0xFFL) shl 48) or
            ((localArray[o + 7].toLong() and 0xFFL) shl 56)
        } else {
            buffer!!.getLong(o)
        }
    }

    fun readBool(): Boolean { val v = byteAt(pos) != 0.toByte(); pos += 1; return v }
    fun readI8(): Byte { val v = byteAt(pos); pos += 1; return v }
    fun readU8(): UByte { val v = byteAt(pos).toUByte(); pos += 1; return v }
    fun readI16(): Short { val v = leI16(pos); pos += 2; return v }
    fun readU16(): UShort { val v = leI16(pos).toUShort(); pos += 2; return v }
    fun readI32(): Int { val v = leI32(pos); pos += 4; return v }
    fun readU32(): UInt { val v = leI32(pos).toUInt(); pos += 4; return v }
    fun readI64(): Long { val v = leI64(pos); pos += 8; return v }
    fun readU64(): ULong { val v = leI64(pos).toULong(); pos += 8; return v }
    fun readF32(): Float { val v = Float.fromBits(leI32(pos)); pos += 4; return v }
    fun readF64(): Double { val v = Double.fromBits(leI64(pos)); pos += 8; return v }

    fun readString(): String {
        val len = leI32(pos).toUInt().toInt()
        pos += 4
        if (len == 0) return ""
        val start = pos
        pos += len
        val localArray = array
        return if (localArray != null) {
            String(localArray, start, len, Charsets.UTF_8)
        } else {
            String(copyRange(start, len), Charsets.UTF_8)
        }
    }

    fun readBytes(): ByteArray {
        val len = leI32(pos).toUInt().toInt()
        pos += 4
        if (len == 0) return ByteArray(0)
        val start = pos
        pos += len
        return copyRange(start, len)
    }

    fun readDuration(): Duration {
        val seconds = readI64()
        val nanos = readI32().toLong()
        require(seconds >= 0L) { "Duration out of range" }
        require(nanos >= 0L) { "Duration nanos out of range" }
        return Duration.ofSeconds(seconds, nanos)
    }

    fun readInstant(): Instant {
        val seconds = readI64()
        val nanos = readI32().toLong()
        require(nanos >= 0L) { "Instant nanos out of range" }
        if (seconds >= 0L) {
            return Instant.EPOCH.plus(Duration.ofSeconds(seconds, nanos))
        }
        require(seconds != Long.MIN_VALUE) { "Instant out of range" }
        return Instant.EPOCH.minus(Duration.ofSeconds(-seconds, nanos))
    }

    fun readUuid(): UUID = UUID(readI64(), readI64())

    fun readUri(): URI = URI.create(readString())

    inline fun <T> readOptional(reader: (WireReader) -> T): T? {
        val tag = readU8().toInt()
        return if (tag == 0) null else reader(this)
    }

    inline fun <T> readList(reader: (WireReader) -> T): List<T> {
        val count = readI32().toUInt().toInt()
        if (count == 0) return emptyList()
        return ArrayList<T>(count).also { list -> repeat(count) { list.add(reader(this)) } }
    }

    inline fun <T, E> readResult(okReader: (WireReader) -> T, errReader: (WireReader) -> E): BoltFFIResult<T, E> {
        val tag = readU8().toInt()
        return if (tag == 0) BoltFFIResult.Ok(okReader(this)) else BoltFFIResult.Err(errReader(this))
    }

    fun readShortArray(): ShortArray {
        val count = readI32().toUInt().toInt()
        if (count == 0) return ShortArray(0)
        val base = pos
        pos += count * 2
        val localArray = array
        return if (localArray != null) {
            ShortArray(count) { i -> leI16(base + i * 2) }
        } else {
            val localBuffer = buffer!!
            ShortArray(count) { i -> localBuffer.getShort(base + i * 2) }
        }
    }

    fun readIntArray(): IntArray {
        val count = readI32().toUInt().toInt()
        if (count == 0) return IntArray(0)
        val base = pos
        pos += count * 4
        val localArray = array
        return if (localArray != null) {
            IntArray(count) { i -> leI32(base + i * 4) }
        } else {
            val localBuffer = buffer!!
            IntArray(count) { i -> localBuffer.getInt(base + i * 4) }
        }
    }

    fun readLongArray(): LongArray {
        val count = readI32().toUInt().toInt()
        if (count == 0) return LongArray(0)
        val base = pos
        pos += count * 8
        val localArray = array
        return if (localArray != null) {
            LongArray(count) { i -> leI64(base + i * 8) }
        } else {
            val localBuffer = buffer!!
            LongArray(count) { i -> localBuffer.getLong(base + i * 8) }
        }
    }

    fun readFloatArray(): FloatArray {
        val count = readI32().toUInt().toInt()
        if (count == 0) return FloatArray(0)
        val base = pos
        pos += count * 4
        val localArray = array
        return if (localArray != null) {
            FloatArray(count) { i -> Float.fromBits(leI32(base + i * 4)) }
        } else {
            val localBuffer = buffer!!
            FloatArray(count) { i -> localBuffer.getFloat(base + i * 4) }
        }
    }

    fun readDoubleArray(): DoubleArray {
        val count = readI32().toUInt().toInt()
        if (count == 0) return DoubleArray(0)
        val base = pos
        pos += count * 8
        val localArray = array
        return if (localArray != null) {
            DoubleArray(count) { i -> Double.fromBits(leI64(base + i * 8)) }
        } else {
            val localBuffer = buffer!!
            DoubleArray(count) { i -> localBuffer.getDouble(base + i * 8) }
        }
    }

    fun readBooleanArray(): BooleanArray {
        val count = readI32().toUInt().toInt()
        if (count == 0) return BooleanArray(0)
        val base = pos
        pos += count
        val localArray = array
        return if (localArray != null) {
            BooleanArray(count) { i -> localArray[base + i] != 0.toByte() }
        } else {
            val localBuffer = buffer!!
            BooleanArray(count) { i -> localBuffer.get(base + i) != 0.toByte() }
        }
    }

    fun skip(count: Int) { pos += count }

    fun readBlittable(sizeBytes: Int): ByteArray {
        val start = pos
        pos += sizeBytes
        return copyRange(start, sizeBytes)
    }
}

sealed class BoltFFIResult<out T, out E> {
    data class Ok<T>(val value: T) : BoltFFIResult<T, Nothing>()
    data class Err<E>(val error: E) : BoltFFIResult<Nothing, E>()

    val isSuccess: Boolean get() = this is Ok
    val isFailure: Boolean get() = this is Err

    fun getOrThrow(): T = when (this) {
        is Ok -> value
        is Err -> throw when (error) {
            is Throwable -> error
            else -> FfiException(-1, error.toString())
        }
    }

    fun getOrNull(): T? = when (this) {
        is Ok -> value
        is Err -> null
    }

    fun exceptionOrNull(): Throwable? = when (this) {
        is Ok -> null
        is Err -> when (error) {
            is Throwable -> error
            else -> FfiException(-1, error.toString())
        }
    }

    inline fun <R> fold(onSuccess: (T) -> R, onFailure: (E) -> R): R = when (this) {
        is Ok -> onSuccess(value)
        is Err -> onFailure(error)
    }
}

@Suppress("UNCHECKED_CAST")
internal fun <T> boltffiUnsafeCast(value: Any?): T = value as T

private object Utf8Codec {
    fun maxBytes(value: String): Int = value.length * 3
}

class WireWriter(initialCapacity: Int = 256) {
    private var buffer: ByteBuffer = ByteBuffer.allocateDirect(initialCapacity).order(ByteOrder.LITTLE_ENDIAN)
    private var pos: Int = 0

    internal fun reset(requiredCapacity: Int) {
        if (buffer.capacity() < requiredCapacity) {
            buffer = ByteBuffer.allocateDirect(requiredCapacity).order(ByteOrder.LITTLE_ENDIAN)
        }
        pos = 0
    }

    internal fun asDirectBuffer(): ByteBuffer {
        val view = buffer.duplicate().order(ByteOrder.LITTLE_ENDIAN)
        view.limit(pos)
        view.position(0)
        return view.slice().order(ByteOrder.LITTLE_ENDIAN)
    }

    internal fun toByteArray(): ByteArray {
        val arr = ByteArray(pos)
        val view = buffer.duplicate()
        view.position(0)
        view.get(arr, 0, pos)
        return arr
    }

    private fun ensureCapacity(needed: Int) {
        val required = pos + needed
        if (required <= buffer.capacity()) return
        val nextCapacity = maxOf(buffer.capacity() * 2, required)
        val next = ByteBuffer.allocateDirect(nextCapacity).order(ByteOrder.LITTLE_ENDIAN)
        val source = buffer.duplicate().order(ByteOrder.LITTLE_ENDIAN)
        source.limit(pos)
        source.position(0)
        next.put(source)
        buffer = next
    }

    internal inline fun writeRawBytes(byteCount: Int, writer: (ByteBuffer, Int) -> Unit) {
        ensureCapacity(byteCount)
        val baseOffset = pos
        writer(buffer, baseOffset)
        pos = baseOffset + byteCount
    }

    fun writeBool(v: Boolean) { ensureCapacity(1); buffer.put(pos, if (v) 1 else 0); pos += 1 }
    fun writePadding(count: Int) {
        ensureCapacity(count)
        val view = buffer.duplicate().order(ByteOrder.LITTLE_ENDIAN)
        view.position(pos)
        repeat(count) { view.put(0) }
        pos += count
    }
    fun writeI8(v: Byte) { ensureCapacity(1); buffer.put(pos, v); pos += 1 }
    fun writeU8(v: UByte) { ensureCapacity(1); buffer.put(pos, v.toByte()); pos += 1 }

    fun writeI16(v: Short) { ensureCapacity(2); buffer.putShort(pos, v); pos += 2 }
    fun writeU16(v: UShort) = writeI16(v.toShort())

    fun writeI32(v: Int) { ensureCapacity(4); buffer.putInt(pos, v); pos += 4 }
    fun writeU32(v: UInt) = writeI32(v.toInt())

    fun writeI64(v: Long) { ensureCapacity(8); buffer.putLong(pos, v); pos += 8 }
    fun writeU64(v: ULong) = writeI64(v.toLong())

    fun writeF32(v: Float) = writeI32(java.lang.Float.floatToRawIntBits(v))
    fun writeF64(v: Double) = writeI64(java.lang.Double.doubleToRawLongBits(v))

    fun writeDuration(v: Duration) {
        require(v.seconds >= 0L) { "Invalid duration, must be non-negative" }
        require(v.nano >= 0) { "Invalid duration nanos" }
        writeI64(v.seconds)
        writeI32(v.nano)
    }

    fun writeInstant(v: Instant) {
        var epochOffset = Duration.between(Instant.EPOCH, v)
        var sign = 1L
        if (epochOffset.isNegative) {
            sign = -1L
            epochOffset = epochOffset.negated()
        }
        require(epochOffset.nano >= 0) { "Invalid instant nanos" }
        writeI64(sign * epochOffset.seconds)
        writeI32(epochOffset.nano)
    }

    fun writeUuid(v: UUID) {
        writeI64(v.mostSignificantBits)
        writeI64(v.leastSignificantBits)
    }

    fun writeUri(v: URI) {
        writeString(v.toString())
    }

    fun writeString(v: String) {
        val bytes = v.toByteArray(Charsets.UTF_8)
        writeU32(bytes.size.toUInt())
        ensureCapacity(bytes.size)
        val view = buffer.duplicate().order(ByteOrder.LITTLE_ENDIAN)
        view.position(pos)
        view.put(bytes)
        pos += bytes.size
    }

    fun writeBytes(v: ByteArray) {
        writeU32(v.size.toUInt())
        ensureCapacity(v.size)
        val view = buffer.duplicate().order(ByteOrder.LITTLE_ENDIAN)
        view.position(pos)
        view.put(v)
        pos += v.size
    }

    fun writePrimitiveList(v: IntArray) {
        writeU32(v.size.toUInt())
        val bytes = v.size * 4
        writeRawBytes(bytes) { buf, baseOffset ->
            val view = buf.duplicate().order(ByteOrder.LITTLE_ENDIAN)
            view.position(baseOffset)
            view.limit(baseOffset + bytes)
            view.slice().order(ByteOrder.LITTLE_ENDIAN).asIntBuffer().put(v)
        }
    }

    fun writePrimitiveList(v: LongArray) {
        writeU32(v.size.toUInt())
        val bytes = v.size * 8
        writeRawBytes(bytes) { buf, baseOffset ->
            val view = buf.duplicate().order(ByteOrder.LITTLE_ENDIAN)
            view.position(baseOffset)
            view.limit(baseOffset + bytes)
            view.slice().order(ByteOrder.LITTLE_ENDIAN).asLongBuffer().put(v)
        }
    }

    fun writePrimitiveList(v: FloatArray) {
        writeU32(v.size.toUInt())
        val bytes = v.size * 4
        writeRawBytes(bytes) { buf, baseOffset ->
            val view = buf.duplicate().order(ByteOrder.LITTLE_ENDIAN)
            view.position(baseOffset)
            view.limit(baseOffset + bytes)
            view.slice().order(ByteOrder.LITTLE_ENDIAN).asFloatBuffer().put(v)
        }
    }

    fun writePrimitiveList(v: DoubleArray) {
        writeU32(v.size.toUInt())
        val bytes = v.size * 8
        writeRawBytes(bytes) { buf, baseOffset ->
            val view = buf.duplicate().order(ByteOrder.LITTLE_ENDIAN)
            view.position(baseOffset)
            view.limit(baseOffset + bytes)
            view.slice().order(ByteOrder.LITTLE_ENDIAN).asDoubleBuffer().put(v)
        }
    }

    fun writePrimitiveList(v: ShortArray) {
        writeU32(v.size.toUInt())
        val bytes = v.size * 2
        writeRawBytes(bytes) { buf, baseOffset ->
            val view = buf.duplicate().order(ByteOrder.LITTLE_ENDIAN)
            view.position(baseOffset)
            view.limit(baseOffset + bytes)
            view.slice().order(ByteOrder.LITTLE_ENDIAN).asShortBuffer().put(v)
        }
    }

    fun writePrimitiveList(v: ByteArray) {
        writeU32(v.size.toUInt())
        ensureCapacity(v.size)
        val view = buffer.duplicate().order(ByteOrder.LITTLE_ENDIAN)
        view.position(pos)
        view.put(v)
        pos += v.size
    }

    fun writePrimitiveList(v: BooleanArray) {
        writeU32(v.size.toUInt())
        v.forEach { writeBool(it) }
    }

    @JvmName("writeIntList")
    fun writePrimitiveList(v: List<Int>) {
        writeU32(v.size.toUInt())
        v.forEach { writeI32(it) }
    }

    @JvmName("writeLongList")
    fun writePrimitiveList(v: List<Long>) {
        writeU32(v.size.toUInt())
        v.forEach { writeI64(it) }
    }

    inline fun <reified T> writeBlittable(v: T) {
        when (v) {
            is Byte -> writeI8(v)
            is Short -> writeI16(v)
            is Int -> writeI32(v)
            is Long -> writeI64(v)
            is Float -> writeF32(v)
            is Double -> writeF64(v)
            is Boolean -> writeBool(v)
            else -> throw IllegalArgumentException("Cannot write blittable: ${T::class}")
        }
    }

    inline fun <reified T> writeBlittableList(v: List<T>) {
        writeU32(v.size.toUInt())
        v.forEach { item -> writeBlittable(item) }
    }
}

private const val MAX_CACHED_WIRE_WRITER_BYTES: Int = 1024 * 1024

internal class WireWriterPoolState(private val cacheSize: Int = 4) {
    private val cachedWriters: Array<WireWriter?> = arrayOfNulls(cacheSize)
    private var depth: Int = 0

    fun acquire(requiredCapacity: Int): BorrowedWireWriter {
        val slot = depth
        depth = slot + 1
        val shouldCache = requiredCapacity <= MAX_CACHED_WIRE_WRITER_BYTES && slot < cacheSize
        val writer = if (shouldCache) {
            cachedWriters[slot] ?: WireWriter(requiredCapacity).also { cachedWriters[slot] = it }
        } else {
            WireWriter(requiredCapacity)
        }

        writer.reset(requiredCapacity)
        return BorrowedWireWriter(this, writer)
    }

    fun release() {
        depth -= 1
    }
}

internal class BorrowedWireWriter(
    private val state: WireWriterPoolState,
    internal val writer: WireWriter
) : AutoCloseable {
    internal val buffer: ByteBuffer
        get() = writer.asDirectBuffer()

    override fun close() {
        state.release()
    }
}

internal object WireWriterPool {
    private val state: ThreadLocal<WireWriterPoolState> = ThreadLocal.withInitial { WireWriterPoolState() }

    fun acquire(requiredCapacity: Int): BorrowedWireWriter {
        val poolState = state.get() ?: WireWriterPoolState().also { state.set(it) }
        return poolState.acquire(requiredCapacity)
    }
}

data class SyncularBoltClientConfig(
    val dbPath: String,
    val baseUrl: String,
    val clientId: String,
    val actorId: String,
    val projectId: String? = null,
    val appSchemaJson: String? = null,
    val autoSyncLocalWrites: Boolean
) {
    companion object {
        fun decode(reader: WireReader): SyncularBoltClientConfig = SyncularBoltClientConfig(
            reader.readString(),
            reader.readString(),
            reader.readString(),
            reader.readString(),
            reader.readOptional { reader.readString() },
            reader.readOptional { reader.readString() },
            reader.readBool()
        )
    }
    fun wireEncodedSize(): Int =
        (4 + Utf8Codec.maxBytes(dbPath)) +
        (4 + Utf8Codec.maxBytes(baseUrl)) +
        (4 + Utf8Codec.maxBytes(clientId)) +
        (4 + Utf8Codec.maxBytes(actorId)) +
        (projectId?.let { v -> 1 + (4 + Utf8Codec.maxBytes(v)) } ?: 1) +
        (appSchemaJson?.let { v -> 1 + (4 + Utf8Codec.maxBytes(v)) } ?: 1) +
        1

    fun wireEncodeTo(wire: WireWriter) {
        wire.writeString(dbPath)
        wire.writeString(baseUrl)
        wire.writeString(clientId)
        wire.writeString(actorId)
        projectId?.let { v -> wire.writeU8(1u); wire.writeString(v) } ?: wire.writeU8(0u)
        appSchemaJson?.let { v -> wire.writeU8(1u); wire.writeString(v) } ?: wire.writeU8(0u)
        wire.writeBool(autoSyncLocalWrites)
    }
}

@Throws(FfiException::class)
fun syncularRuntimeManifestJson(): String {
    val buf = Native.boltffi_syncular_runtime_manifest_json()
        ?: throw FfiException(-1, "Null buffer returned")
    val reader = WireReader(buf)
    return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
}

fun syncularTakeLastOpenError(): String? {
    val buf = Native.boltffi_syncular_take_last_open_error()
        ?: throw FfiException(-1, "Null buffer returned")
    val reader = WireReader(buf)
    return reader.readOptional { reader.readString() }
}

@Throws(FfiException::class)
fun syncularYjsBuildTextUpdateJson(argsJson: String): String {
    val buf = Native.boltffi_syncular_yjs_build_text_update_json(argsJson.toByteArray(Charsets.UTF_8))
        ?: throw FfiException(-1, "Null buffer returned")
    val reader = WireReader(buf)
    return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
}

@Throws(FfiException::class)
fun syncularYjsApplyTextUpdatesJson(argsJson: String): String {
    val buf = Native.boltffi_syncular_yjs_apply_text_updates_json(argsJson.toByteArray(Charsets.UTF_8))
        ?: throw FfiException(-1, "Null buffer returned")
    val reader = WireReader(buf)
    return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
}

@Throws(FfiException::class)
fun syncularYjsApplyEnvelopeToPayloadJson(argsJson: String): String {
    val buf = Native.boltffi_syncular_yjs_apply_envelope_to_payload_json(argsJson.toByteArray(Charsets.UTF_8))
        ?: throw FfiException(-1, "Null buffer returned")
    val reader = WireReader(buf)
    return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
}

@Throws(FfiException::class)
fun syncularYjsMaterializeRowJson(argsJson: String): String {
    val buf = Native.boltffi_syncular_yjs_materialize_row_json(argsJson.toByteArray(Charsets.UTF_8))
        ?: throw FfiException(-1, "Null buffer returned")
    val reader = WireReader(buf)
    return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
}

@Throws(FfiException::class)
fun syncularEncryptionHelperJson(method: String, argsJson: String): String {
    val buf = Native.boltffi_syncular_encryption_helper_json(method.toByteArray(Charsets.UTF_8), argsJson.toByteArray(Charsets.UTF_8))
        ?: throw FfiException(-1, "Null buffer returned")
    val reader = WireReader(buf)
    return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
}

class SyncularBoltClient private constructor(internal val handle: Long) : AutoCloseable {
    private val closed = AtomicBoolean(false)

    constructor(config: SyncularBoltClientConfig) : this(
        kotlin.run {
            val wire_writer_config = WireWriterPool.acquire(config.wireEncodedSize())
        kotlin.run {
            val wire = wire_writer_config.writer
            config.wireEncodeTo(wire)
        }
            try {
                val handle = Native.boltffi_syncular_bolt_client_open(wire_writer_config.buffer)
                if (handle == 0L) throw FfiException(1, takeLastErrorMessage())
                handle
            } finally {
                wire_writer_config.close()
            }
        }
    )

    override fun close() {
        if (!closed.compareAndSet(false, true)) return
        Native.boltffi_syncular_bolt_client_free(handle)
    }

    companion object {
        fun openAsync(config: SyncularBoltClientConfig): SyncularBoltClient {
            val wire_writer_config = WireWriterPool.acquire(config.wireEncodedSize())
        kotlin.run {
            val wire = wire_writer_config.writer
            config.wireEncodeTo(wire)
        }
            try {
                val handle = Native.boltffi_syncular_bolt_client_open_async(wire_writer_config.buffer)
                if (handle == 0L) throw FfiException(1, takeLastErrorMessage())
                return SyncularBoltClient(handle)
            } finally {
                wire_writer_config.close()
            }
        }
    }


    @Throws(FfiException::class)
    fun openCommandId(): String? {
        val buf = Native.boltffi_syncular_bolt_client_open_command_id(handle)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readOptional { reader.readString() } }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun isOpenFinished(): Boolean {
        val buf = Native.boltffi_syncular_bolt_client_is_open_finished(handle)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readBool() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun finishOpenTimeout(timeoutMs: ULong): Boolean {
        val buf = Native.boltffi_syncular_bolt_client_finish_open_timeout(handle, timeoutMs.toLong())
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readBool() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun runtimeManifestJson(): String {
        val buf = Native.boltffi_syncular_bolt_client_runtime_manifest_json(handle)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun setAuthHeadersJson(headersJson: String): Boolean {
        val buf = Native.boltffi_syncular_bolt_client_set_auth_headers_json(handle, headersJson.toByteArray(Charsets.UTF_8))
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readBool() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun setSubscriptionsJson(subscriptionsJson: String): Boolean {
        val buf = Native.boltffi_syncular_bolt_client_set_subscriptions_json(handle, subscriptionsJson.toByteArray(Charsets.UTF_8))
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readBool() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun setFieldEncryptionJson(configJson: String): Boolean {
        val buf = Native.boltffi_syncular_bolt_client_set_field_encryption_json(handle, configJson.toByteArray(Charsets.UTF_8))
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readBool() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun setEncryptedCrdtJson(configJson: String): Boolean {
        val buf = Native.boltffi_syncular_bolt_client_set_encrypted_crdt_json(handle, configJson.toByteArray(Charsets.UTF_8))
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readBool() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun triggerSync(): Boolean {
        val buf = Native.boltffi_syncular_bolt_client_trigger_sync(handle)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readBool() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun triggerSyncWebsocket(): Boolean {
        val buf = Native.boltffi_syncular_bolt_client_trigger_sync_websocket(handle)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readBool() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun enqueueSyncNow(): String {
        val buf = Native.boltffi_syncular_bolt_client_enqueue_sync_now(handle)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun enqueueSyncWebsocket(): String {
        val buf = Native.boltffi_syncular_bolt_client_enqueue_sync_websocket(handle)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun pauseSyncWorker(): Boolean {
        val buf = Native.boltffi_syncular_bolt_client_pause_sync_worker(handle)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readBool() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun resumeSyncWorker(): Boolean {
        val buf = Native.boltffi_syncular_bolt_client_resume_sync_worker(handle)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readBool() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun syncWorkerRunning(): Boolean {
        val buf = Native.boltffi_syncular_bolt_client_sync_worker_running(handle)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readBool() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun startRealtimeWorker(): Boolean {
        val buf = Native.boltffi_syncular_bolt_client_start_realtime_worker(handle)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readBool() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun stopRealtimeWorker(): Boolean {
        val buf = Native.boltffi_syncular_bolt_client_stop_realtime_worker(handle)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readBool() }, { reader.readString() }).getOrThrow()
    }

    @Throws(FfiException::class)
    fun joinPresence(scopeKey: String, metadataJson: String? = null): Boolean {
        val scopeKeyBytes = scopeKey.toByteArray(Charsets.UTF_8)
        val metadataJsonBytes = WireWriter().also { wire ->
            metadataJson?.let { v -> wire.writeU8(1u); wire.writeString(v) } ?: wire.writeU8(0u)
        }.toByteArray()
        val buf = Native.boltffi_syncular_bolt_client_join_presence(handle, scopeKeyBytes, ByteBuffer.wrap(metadataJsonBytes))
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readBool() }, { reader.readString() }).getOrThrow()
    }

    @Throws(FfiException::class)
    fun leavePresence(scopeKey: String): Boolean {
        val scopeKeyBytes = scopeKey.toByteArray(Charsets.UTF_8)
        val buf = Native.boltffi_syncular_bolt_client_leave_presence(handle, scopeKeyBytes)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readBool() }, { reader.readString() }).getOrThrow()
    }

    @Throws(FfiException::class)
    fun updatePresenceMetadata(scopeKey: String, metadataJson: String): Boolean {
        val scopeKeyBytes = scopeKey.toByteArray(Charsets.UTF_8)
        val metadataJsonBytes = metadataJson.toByteArray(Charsets.UTF_8)
        val buf = Native.boltffi_syncular_bolt_client_update_presence_metadata(handle, scopeKeyBytes, metadataJsonBytes)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readBool() }, { reader.readString() }).getOrThrow()
    }

    @Throws(FfiException::class)
    fun presenceJson(scopeKey: String): String {
        val scopeKeyBytes = scopeKey.toByteArray(Charsets.UTF_8)
        val buf = Native.boltffi_syncular_bolt_client_presence_json(handle, scopeKeyBytes)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun startEventStream(capacity: ULong): Boolean {
        val buf = Native.boltffi_syncular_bolt_client_start_event_stream(handle, capacity.toLong())
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readBool() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun nextEventJson(): String? {
        val buf = Native.boltffi_syncular_bolt_client_next_event_json(handle)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readOptional { reader.readString() } }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun closeEventStream(): Boolean {
        val buf = Native.boltffi_syncular_bolt_client_close_event_stream(handle)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readBool() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun applyLocalOperationJson(operationJson: String, localRowJson: String?): String {
        val wire_writer_local_row_json = WireWriterPool.acquire((localRowJson?.let { v -> 1 + (4 + Utf8Codec.maxBytes(v)) } ?: 1))
            kotlin.run {
                val wire = wire_writer_local_row_json.writer
                localRowJson?.let { v -> wire.writeU8(1u); wire.writeString(v) } ?: wire.writeU8(0u)
            }
        try {
            val buf = Native.boltffi_syncular_bolt_client_apply_local_operation_json(handle, operationJson.toByteArray(Charsets.UTF_8), wire_writer_local_row_json.buffer)
                ?: throw FfiException(-1, "Null buffer returned")
            val reader = WireReader(buf)
            return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
        } finally {
            wire_writer_local_row_json.close()
        }
    }


    @Throws(FfiException::class)
    fun enqueueLocalOperationJson(operationJson: String, localRowJson: String?): String {
        val wire_writer_local_row_json = WireWriterPool.acquire((localRowJson?.let { v -> 1 + (4 + Utf8Codec.maxBytes(v)) } ?: 1))
            kotlin.run {
                val wire = wire_writer_local_row_json.writer
                localRowJson?.let { v -> wire.writeU8(1u); wire.writeString(v) } ?: wire.writeU8(0u)
            }
        try {
            val buf = Native.boltffi_syncular_bolt_client_enqueue_local_operation_json(handle, operationJson.toByteArray(Charsets.UTF_8), wire_writer_local_row_json.buffer)
                ?: throw FfiException(-1, "Null buffer returned")
            val reader = WireReader(buf)
            return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
        } finally {
            wire_writer_local_row_json.close()
        }
    }


    @Throws(FfiException::class)
    fun applyMutationJson(mutationJson: String, localRowJson: String?): String {
        val wire_writer_local_row_json = WireWriterPool.acquire((localRowJson?.let { v -> 1 + (4 + Utf8Codec.maxBytes(v)) } ?: 1))
            kotlin.run {
                val wire = wire_writer_local_row_json.writer
                localRowJson?.let { v -> wire.writeU8(1u); wire.writeString(v) } ?: wire.writeU8(0u)
            }
        try {
            val buf = Native.boltffi_syncular_bolt_client_apply_mutation_json(handle, mutationJson.toByteArray(Charsets.UTF_8), wire_writer_local_row_json.buffer)
                ?: throw FfiException(-1, "Null buffer returned")
            val reader = WireReader(buf)
            return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
        } finally {
            wire_writer_local_row_json.close()
        }
    }


    @Throws(FfiException::class)
    fun enqueueMutationJson(mutationJson: String, localRowJson: String?): String {
        val wire_writer_local_row_json = WireWriterPool.acquire((localRowJson?.let { v -> 1 + (4 + Utf8Codec.maxBytes(v)) } ?: 1))
            kotlin.run {
                val wire = wire_writer_local_row_json.writer
                localRowJson?.let { v -> wire.writeU8(1u); wire.writeString(v) } ?: wire.writeU8(0u)
            }
        try {
            val buf = Native.boltffi_syncular_bolt_client_enqueue_mutation_json(handle, mutationJson.toByteArray(Charsets.UTF_8), wire_writer_local_row_json.buffer)
                ?: throw FfiException(-1, "Null buffer returned")
            val reader = WireReader(buf)
            return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
        } finally {
            wire_writer_local_row_json.close()
        }
    }


    @Throws(FfiException::class)
    fun enqueueYjsUpdateJson(updateJson: String): String {
        val buf = Native.boltffi_syncular_bolt_client_enqueue_yjs_update_json(handle, updateJson.toByteArray(Charsets.UTF_8))
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun openCrdtFieldJson(requestJson: String): String {
        val buf = Native.boltffi_syncular_bolt_client_open_crdt_field_json(handle, requestJson.toByteArray(Charsets.UTF_8))
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun applyCrdtFieldTextJson(requestJson: String): String {
        val buf = Native.boltffi_syncular_bolt_client_apply_crdt_field_text_json(handle, requestJson.toByteArray(Charsets.UTF_8))
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun applyCrdtFieldYjsUpdateJson(requestJson: String): String {
        val buf = Native.boltffi_syncular_bolt_client_apply_crdt_field_yjs_update_json(handle, requestJson.toByteArray(Charsets.UTF_8))
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun enqueueCrdtFieldYjsUpdateJson(requestJson: String): String {
        val buf = Native.boltffi_syncular_bolt_client_enqueue_crdt_field_yjs_update_json(handle, requestJson.toByteArray(Charsets.UTF_8))
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun enqueueCrdtFieldTextJson(requestJson: String): String {
        val buf = Native.boltffi_syncular_bolt_client_enqueue_crdt_field_text_json(handle, requestJson.toByteArray(Charsets.UTF_8))
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun enqueueCrdtFieldCompactionJson(requestJson: String): String {
        val buf = Native.boltffi_syncular_bolt_client_enqueue_crdt_field_compaction_json(handle, requestJson.toByteArray(Charsets.UTF_8))
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun materializeCrdtFieldJson(requestJson: String): String {
        val buf = Native.boltffi_syncular_bolt_client_materialize_crdt_field_json(handle, requestJson.toByteArray(Charsets.UTF_8))
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun crdtDocumentSnapshotJson(requestJson: String): String {
        val buf = Native.boltffi_syncular_bolt_client_crdt_document_snapshot_json(handle, requestJson.toByteArray(Charsets.UTF_8))
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun crdtUpdateLogJson(requestJson: String): String {
        val buf = Native.boltffi_syncular_bolt_client_crdt_update_log_json(handle, requestJson.toByteArray(Charsets.UTF_8))
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun snapshotCrdtFieldStateVectorJson(requestJson: String): String {
        val buf = Native.boltffi_syncular_bolt_client_snapshot_crdt_field_state_vector_json(handle, requestJson.toByteArray(Charsets.UTF_8))
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun compactCrdtFieldJson(requestJson: String): String {
        val buf = Native.boltffi_syncular_bolt_client_compact_crdt_field_json(handle, requestJson.toByteArray(Charsets.UTF_8))
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun applyEncryptedCrdtUpdateJson(requestJson: String): String {
        val buf = Native.boltffi_syncular_bolt_client_apply_encrypted_crdt_update_json(handle, requestJson.toByteArray(Charsets.UTF_8))
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun enqueueEncryptedCrdtUpdateJson(requestJson: String): String {
        val buf = Native.boltffi_syncular_bolt_client_enqueue_encrypted_crdt_update_json(handle, requestJson.toByteArray(Charsets.UTF_8))
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun applyEncryptedCrdtCheckpointJson(requestJson: String): String {
        val buf = Native.boltffi_syncular_bolt_client_apply_encrypted_crdt_checkpoint_json(handle, requestJson.toByteArray(Charsets.UTF_8))
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun enqueueEncryptedCrdtCheckpointJson(requestJson: String): String {
        val buf = Native.boltffi_syncular_bolt_client_enqueue_encrypted_crdt_checkpoint_json(handle, requestJson.toByteArray(Charsets.UTF_8))
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun listTableJson(table: String): String {
        val buf = Native.boltffi_syncular_bolt_client_list_table_json(handle, table.toByteArray(Charsets.UTF_8))
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun queryJson(requestJson: String): String {
        val buf = Native.boltffi_syncular_bolt_client_query_json(handle, requestJson.toByteArray(Charsets.UTF_8))
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun enqueueRefreshSnapshotJson(requestJson: String): String {
        val buf = Native.boltffi_syncular_bolt_client_enqueue_refresh_snapshot_json(handle, requestJson.toByteArray(Charsets.UTF_8))
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun storeBlobFileJson(path: String, optionsJson: String?): String {
        val wire_writer_options_json = WireWriterPool.acquire((optionsJson?.let { v -> 1 + (4 + Utf8Codec.maxBytes(v)) } ?: 1))
            kotlin.run {
                val wire = wire_writer_options_json.writer
                optionsJson?.let { v -> wire.writeU8(1u); wire.writeString(v) } ?: wire.writeU8(0u)
            }
        try {
            val buf = Native.boltffi_syncular_bolt_client_store_blob_file_json(handle, path.toByteArray(Charsets.UTF_8), wire_writer_options_json.buffer)
                ?: throw FfiException(-1, "Null buffer returned")
            val reader = WireReader(buf)
            return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
        } finally {
            wire_writer_options_json.close()
        }
    }


    @Throws(FfiException::class)
    fun enqueueStoreBlobFileJson(path: String, optionsJson: String?): String {
        val wire_writer_options_json = WireWriterPool.acquire((optionsJson?.let { v -> 1 + (4 + Utf8Codec.maxBytes(v)) } ?: 1))
            kotlin.run {
                val wire = wire_writer_options_json.writer
                optionsJson?.let { v -> wire.writeU8(1u); wire.writeString(v) } ?: wire.writeU8(0u)
            }
        try {
            val buf = Native.boltffi_syncular_bolt_client_enqueue_store_blob_file_json(handle, path.toByteArray(Charsets.UTF_8), wire_writer_options_json.buffer)
                ?: throw FfiException(-1, "Null buffer returned")
            val reader = WireReader(buf)
            return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
        } finally {
            wire_writer_options_json.close()
        }
    }


    @Throws(FfiException::class)
    fun retrieveBlobFileJson(refJson: String, path: String, optionsJson: String?): Boolean {
        val wire_writer_options_json = WireWriterPool.acquire((optionsJson?.let { v -> 1 + (4 + Utf8Codec.maxBytes(v)) } ?: 1))
            kotlin.run {
                val wire = wire_writer_options_json.writer
                optionsJson?.let { v -> wire.writeU8(1u); wire.writeString(v) } ?: wire.writeU8(0u)
            }
        try {
            val buf = Native.boltffi_syncular_bolt_client_retrieve_blob_file_json(handle, refJson.toByteArray(Charsets.UTF_8), path.toByteArray(Charsets.UTF_8), wire_writer_options_json.buffer)
                ?: throw FfiException(-1, "Null buffer returned")
            val reader = WireReader(buf)
            return reader.readResult({ reader.readBool() }, { reader.readString() }).getOrThrow()
        } finally {
            wire_writer_options_json.close()
        }
    }


    @Throws(FfiException::class)
    fun enqueueRetrieveBlobFileJson(refJson: String, path: String, optionsJson: String?): String {
        val wire_writer_options_json = WireWriterPool.acquire((optionsJson?.let { v -> 1 + (4 + Utf8Codec.maxBytes(v)) } ?: 1))
            kotlin.run {
                val wire = wire_writer_options_json.writer
                optionsJson?.let { v -> wire.writeU8(1u); wire.writeString(v) } ?: wire.writeU8(0u)
            }
        try {
            val buf = Native.boltffi_syncular_bolt_client_enqueue_retrieve_blob_file_json(handle, refJson.toByteArray(Charsets.UTF_8), path.toByteArray(Charsets.UTF_8), wire_writer_options_json.buffer)
                ?: throw FfiException(-1, "Null buffer returned")
            val reader = WireReader(buf)
            return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
        } finally {
            wire_writer_options_json.close()
        }
    }


    @Throws(FfiException::class)
    fun isBlobLocal(hash: String): Boolean {
        val buf = Native.boltffi_syncular_bolt_client_is_blob_local(handle, hash.toByteArray(Charsets.UTF_8))
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readBool() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun processBlobUploadQueueJson(): String {
        val buf = Native.boltffi_syncular_bolt_client_process_blob_upload_queue_json(handle)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun blobUploadQueueStatsJson(): String {
        val buf = Native.boltffi_syncular_bolt_client_blob_upload_queue_stats_json(handle)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun blobCacheStatsJson(): String {
        val buf = Native.boltffi_syncular_bolt_client_blob_cache_stats_json(handle)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun pruneBlobCache(maxBytes: Long): Long {
        val buf = Native.boltffi_syncular_bolt_client_prune_blob_cache(handle, maxBytes)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readI64() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun enqueuePruneBlobCache(maxBytes: Long): String {
        val buf = Native.boltffi_syncular_bolt_client_enqueue_prune_blob_cache(handle, maxBytes)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun clearBlobCache(): Boolean {
        val buf = Native.boltffi_syncular_bolt_client_clear_blob_cache(handle)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readBool() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun enqueueClearBlobCache(): String {
        val buf = Native.boltffi_syncular_bolt_client_enqueue_clear_blob_cache(handle)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun compactStorageJson(optionsJson: String?): String {
        val wire_writer_options_json = WireWriterPool.acquire((optionsJson?.let { v -> 1 + (4 + Utf8Codec.maxBytes(v)) } ?: 1))
            kotlin.run {
                val wire = wire_writer_options_json.writer
                optionsJson?.let { v -> wire.writeU8(1u); wire.writeString(v) } ?: wire.writeU8(0u)
            }
        try {
            val buf = Native.boltffi_syncular_bolt_client_compact_storage_json(handle, wire_writer_options_json.buffer)
                ?: throw FfiException(-1, "Null buffer returned")
            val reader = WireReader(buf)
            return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
        } finally {
            wire_writer_options_json.close()
        }
    }


    @Throws(FfiException::class)
    fun enqueueCompactStorageJson(optionsJson: String?): String {
        val wire_writer_options_json = WireWriterPool.acquire((optionsJson?.let { v -> 1 + (4 + Utf8Codec.maxBytes(v)) } ?: 1))
            kotlin.run {
                val wire = wire_writer_options_json.writer
                optionsJson?.let { v -> wire.writeU8(1u); wire.writeString(v) } ?: wire.writeU8(0u)
            }
        try {
            val buf = Native.boltffi_syncular_bolt_client_enqueue_compact_storage_json(handle, wire_writer_options_json.buffer)
                ?: throw FfiException(-1, "Null buffer returned")
            val reader = WireReader(buf)
            return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
        } finally {
            wire_writer_options_json.close()
        }
    }


    @Throws(FfiException::class)
    fun appTablesJson(): String {
        val buf = Native.boltffi_syncular_bolt_client_app_tables_json(handle)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun appTableMetadataJson(): String {
        val buf = Native.boltffi_syncular_bolt_client_app_table_metadata_json(handle)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun registerQueryJson(queryJson: String): String {
        val buf = Native.boltffi_syncular_bolt_client_register_query_json(handle, queryJson.toByteArray(Charsets.UTF_8))
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun unregisterQuery(id: String): Boolean {
        val buf = Native.boltffi_syncular_bolt_client_unregister_query(handle, id.toByteArray(Charsets.UTF_8))
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readBool() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun observedQueriesJson(): String {
        val buf = Native.boltffi_syncular_bolt_client_observed_queries_json(handle)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun outboxSummariesJson(): String {
        val buf = Native.boltffi_syncular_bolt_client_outbox_summaries_json(handle)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun conflictSummariesJson(): String {
        val buf = Native.boltffi_syncular_bolt_client_conflict_summaries_json(handle)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun resolveConflict(id: String, resolution: String): Boolean {
        val buf = Native.boltffi_syncular_bolt_client_resolve_conflict(handle, id.toByteArray(Charsets.UTF_8), resolution.toByteArray(Charsets.UTF_8))
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readBool() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun enqueueResolveConflict(id: String, resolution: String): String {
        val buf = Native.boltffi_syncular_bolt_client_enqueue_resolve_conflict(handle, id.toByteArray(Charsets.UTF_8), resolution.toByteArray(Charsets.UTF_8))
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun retryConflictKeepLocal(id: String): String {
        val buf = Native.boltffi_syncular_bolt_client_retry_conflict_keep_local(handle, id.toByteArray(Charsets.UTF_8))
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readString() }, { reader.readString() }).getOrThrow()
    }


    @Throws(FfiException::class)
    fun shutdown(): Boolean {
        val buf = Native.boltffi_syncular_bolt_client_shutdown(handle)
            ?: throw FfiException(-1, "Null buffer returned")
        val reader = WireReader(buf)
        return reader.readResult({ reader.readBool() }, { reader.readString() }).getOrThrow()
    }
}

@Suppress("FunctionName")
private object Native {
    init {
        val preferredLibrary = "syncular_runtime_jni"
        val fallbackLibrary = "syncular_runtime"
        val vmName = System.getProperty("java.vm.name").orEmpty()
        val isAndroidRuntime =
            vmName.contains("dalvik", ignoreCase = true) ||
            vmName.contains("art", ignoreCase = true)
        if (isAndroidRuntime) {
            System.loadLibrary(fallbackLibrary)
        } else {
            loadDesktopLibraries(preferredLibrary, fallbackLibrary)
        }
    }
    @Volatile
    private var bundledLibraryDirectory: java.io.File? = null

    private fun loadDesktopLibraries(preferredLibrary: String, fallbackLibrary: String) {
        var preferredFailure = tryLoadDesktopLibrary(preferredLibrary)
        if (preferredFailure == null) {
            return
        }

        if (tryLoadOptionalDesktopLibrary(fallbackLibrary)) {
            preferredFailure = tryLoadDesktopLibrary(preferredLibrary)
            if (preferredFailure == null) {
                return
            }
        }

        throw preferredFailure
    }

    private fun tryLoadDesktopLibrary(libraryName: String): UnsatisfiedLinkError? {
        try {
            if (loadBundledLibraryIfPresent(libraryName) || loadExternalLibraryIfPresent(libraryName)) {
                return null
            }
            return UnsatisfiedLinkError("Could not load native library '$libraryName'")
        } catch (error: UnsatisfiedLinkError) {
            return error
        }
    }

    private fun tryLoadOptionalDesktopLibrary(libraryName: String): Boolean {
        return try {
            loadBundledLibraryIfPresent(libraryName) || loadExternalLibraryIfPresent(libraryName)
        } catch (_: UnsatisfiedLinkError) {
            false
        }
    }

    private fun loadExternalLibraryIfPresent(libraryName: String): Boolean {
        return try {
            System.loadLibrary(libraryName)
            true
        } catch (_: UnsatisfiedLinkError) {
            false
        }
    }

    private fun loadBundledLibraryIfPresent(libraryName: String): Boolean {
        val mappedName = System.mapLibraryName(libraryName)
        for (resourcePath in bundledLibraryResourceCandidates(mappedName)) {
            Native::class.java.getResourceAsStream(resourcePath)?.use { input ->
                val extracted = extractBundledLibrary(resourcePath, input)
                System.load(extracted.absolutePath)
                return true
            }
        }
        return false
    }

    private fun extractBundledLibrary(
        resourcePath: String,
        input: java.io.InputStream,
    ): java.io.File {
        val fileName = resourcePath.substringAfterLast('/')
        val extracted = java.io.File(bundledLibraryDirectory(), fileName)
        if (!extracted.isFile) {
            java.io.FileOutputStream(extracted).use { output ->
                input.copyTo(output)
            }
            extracted.deleteOnExit()
        }
        return extracted
    }

    private fun bundledLibraryDirectory(): java.io.File {
        bundledLibraryDirectory?.let { return it }
        synchronized(this) {
            bundledLibraryDirectory?.let { return it }
            val created = java.io.File.createTempFile("boltffi-native-", "")
            if (!created.delete() || !created.mkdir()) {
                throw java.io.IOException("failed to create temp directory for bundled native extraction")
            }
            created.deleteOnExit()
            bundledLibraryDirectory = created
            return created
        }
    }

    private fun bundledLibraryResourceCandidates(mappedName: String): List<String> {
        val candidates = mutableListOf<String>()
        for (directory in desktopNativeDirectories()) {
            candidates += "/$directory/$mappedName"
            candidates += "/native/$directory/$mappedName"
        }
        candidates += "/$mappedName"
        return candidates
    }

    private fun desktopNativeDirectories(): List<String> {
        val osName = System.getProperty("os.name").orEmpty().lowercase()
        val osArch = System.getProperty("os.arch").orEmpty().lowercase()
        return when {
            (osName.contains("mac") || osName.contains("darwin")) &&
                (osArch == "aarch64" || osArch == "arm64") ->
                listOf("darwin-arm64", "darwin-aarch64")
            (osName.contains("mac") || osName.contains("darwin")) && osArch == "x86_64" ->
                listOf("darwin-x86_64", "darwin-x86-64")
            osName.contains("linux") && (osArch == "x86_64" || osArch == "amd64") ->
                listOf("linux-x86_64", "linux-x86-64")
            osName.contains("linux") && (osArch == "aarch64" || osArch == "arm64") ->
                listOf("linux-aarch64", "linux-arm64")
            osName.contains("windows") && (osArch == "x86_64" || osArch == "amd64") ->
                listOf("windows-x86_64", "windows-x86-64", "win32-x86_64")
            else -> emptyList()
        }
    }

    @JvmStatic external fun boltffi_free_string(ptr: Long)
    @JvmStatic external fun boltffi_last_error_message(): ByteArray
    @JvmStatic external fun boltffi_syncular_runtime_manifest_json(): ByteArray?
    @JvmStatic external fun boltffi_syncular_take_last_open_error(): ByteArray?
    @JvmStatic external fun boltffi_syncular_yjs_build_text_update_json(args_json: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_yjs_apply_text_updates_json(args_json: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_yjs_apply_envelope_to_payload_json(args_json: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_yjs_materialize_row_json(args_json: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_encryption_helper_json(method: ByteArray, args_json: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_open(config: ByteBuffer): Long
    @JvmStatic external fun boltffi_syncular_bolt_client_open_async(config: ByteBuffer): Long
    @JvmStatic external fun boltffi_syncular_bolt_client_free(handle: Long)
    @JvmStatic external fun boltffi_syncular_bolt_client_open_command_id(handle: Long): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_is_open_finished(handle: Long): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_finish_open_timeout(handle: Long, timeout_ms: Long): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_runtime_manifest_json(handle: Long): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_set_auth_headers_json(handle: Long, headers_json: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_set_subscriptions_json(handle: Long, subscriptions_json: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_set_field_encryption_json(handle: Long, config_json: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_set_encrypted_crdt_json(handle: Long, config_json: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_trigger_sync(handle: Long): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_trigger_sync_websocket(handle: Long): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_enqueue_sync_now(handle: Long): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_enqueue_sync_websocket(handle: Long): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_pause_sync_worker(handle: Long): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_resume_sync_worker(handle: Long): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_sync_worker_running(handle: Long): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_start_realtime_worker(handle: Long): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_stop_realtime_worker(handle: Long): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_join_presence(handle: Long, scope_key: ByteArray, metadata_json: ByteBuffer): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_leave_presence(handle: Long, scope_key: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_update_presence_metadata(handle: Long, scope_key: ByteArray, metadata_json: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_presence_json(handle: Long, scope_key: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_start_event_stream(handle: Long, capacity: Long): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_next_event_json(handle: Long): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_close_event_stream(handle: Long): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_apply_local_operation_json(handle: Long, operation_json: ByteArray, local_row_json: ByteBuffer): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_enqueue_local_operation_json(handle: Long, operation_json: ByteArray, local_row_json: ByteBuffer): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_apply_mutation_json(handle: Long, mutation_json: ByteArray, local_row_json: ByteBuffer): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_enqueue_mutation_json(handle: Long, mutation_json: ByteArray, local_row_json: ByteBuffer): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_enqueue_yjs_update_json(handle: Long, update_json: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_open_crdt_field_json(handle: Long, request_json: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_apply_crdt_field_text_json(handle: Long, request_json: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_apply_crdt_field_yjs_update_json(handle: Long, request_json: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_enqueue_crdt_field_yjs_update_json(handle: Long, request_json: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_enqueue_crdt_field_text_json(handle: Long, request_json: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_enqueue_crdt_field_compaction_json(handle: Long, request_json: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_materialize_crdt_field_json(handle: Long, request_json: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_crdt_document_snapshot_json(handle: Long, request_json: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_crdt_update_log_json(handle: Long, request_json: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_snapshot_crdt_field_state_vector_json(handle: Long, request_json: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_compact_crdt_field_json(handle: Long, request_json: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_apply_encrypted_crdt_update_json(handle: Long, request_json: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_enqueue_encrypted_crdt_update_json(handle: Long, request_json: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_apply_encrypted_crdt_checkpoint_json(handle: Long, request_json: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_enqueue_encrypted_crdt_checkpoint_json(handle: Long, request_json: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_list_table_json(handle: Long, table: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_query_json(handle: Long, request_json: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_enqueue_refresh_snapshot_json(handle: Long, request_json: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_store_blob_file_json(handle: Long, path: ByteArray, options_json: ByteBuffer): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_enqueue_store_blob_file_json(handle: Long, path: ByteArray, options_json: ByteBuffer): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_retrieve_blob_file_json(handle: Long, ref_json: ByteArray, path: ByteArray, options_json: ByteBuffer): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_enqueue_retrieve_blob_file_json(handle: Long, ref_json: ByteArray, path: ByteArray, options_json: ByteBuffer): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_is_blob_local(handle: Long, hash: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_process_blob_upload_queue_json(handle: Long): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_blob_upload_queue_stats_json(handle: Long): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_blob_cache_stats_json(handle: Long): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_prune_blob_cache(handle: Long, max_bytes: Long): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_enqueue_prune_blob_cache(handle: Long, max_bytes: Long): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_clear_blob_cache(handle: Long): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_enqueue_clear_blob_cache(handle: Long): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_compact_storage_json(handle: Long, options_json: ByteBuffer): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_enqueue_compact_storage_json(handle: Long, options_json: ByteBuffer): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_app_tables_json(handle: Long): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_app_table_metadata_json(handle: Long): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_register_query_json(handle: Long, query_json: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_unregister_query(handle: Long, id: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_observed_queries_json(handle: Long): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_outbox_summaries_json(handle: Long): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_conflict_summaries_json(handle: Long): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_resolve_conflict(handle: Long, id: ByteArray, resolution: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_enqueue_resolve_conflict(handle: Long, id: ByteArray, resolution: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_retry_conflict_keep_local(handle: Long, id: ByteArray): ByteArray?
    @JvmStatic external fun boltffi_syncular_bolt_client_shutdown(handle: Long): ByteArray?
}
