// Generated by @syncular/typegen — DO NOT EDIT.
// irVersion: 1
// irHash: sha256:9f91145d5e1d17303de133edc87b440f6ad59fe2a081c2303db1dd01db831ac4

export type SyqlRuntimeErrorCode =
  | 'SYQL_RUNTIME_MISSING_REQUIRED_INPUT'
  | 'SYQL_RUNTIME_UNKNOWN_INPUT'
  | 'SYQL_RUNTIME_INVALID_INPUT'
  | 'SYQL_RUNTIME_INVALID_GROUP'
  | 'SYQL_RUNTIME_INVALID_SORT'
  | 'SYQL_RUNTIME_INVALID_LIMIT';

export class SyqlInputError extends Error {
  readonly name = 'SyqlInputError';
  constructor(readonly code: SyqlRuntimeErrorCode, message: string) {
    super(message);
  }
}

export interface SyqlPresent<T> {
  readonly present: true;
  readonly value: T;
}

export function syqlPresent<T>(value: T): SyqlPresent<T> {
  return { present: true, value };
}

/** A generated named-query row did not match its analyzed result type. */
export class QueryResultDecodeError extends TypeError {
  readonly name = 'QueryResultDecodeError';
  constructor(readonly query: string, readonly column: string) {
    super(query + ': result column ' + column + ' is not a SQLite boolean');
  }
}

/** Lift a SQLite boolean: preserve booleans, map 0 to false and finite non-zero numbers to true. */
function decodeQueryBoolean(value: unknown, query: string, column: string): boolean {
  if (typeof value === 'boolean') return value;
  if (typeof value === 'number' && Number.isFinite(value)) return value !== 0;
  throw new QueryResultDecodeError(query, column);
}

/** A bindable SQL param/row value (the wrapper's SqlValue subset). */
export type QueryValue =
  | string
  | number
  | bigint
  | boolean
  | Uint8Array
  | null;

/** Minimal structural client surface — the wrapper's positional
 *  `query(sql, params?)`. `SyncClient`/`SyncClientHandle`/`SyncClientLike`
 *  all satisfy it, so this module imports nothing. */
export interface QueryClient {
  query(
    sql: string,
    params?: readonly QueryValue[],
  ): unknown[] | Promise<unknown[]>;
}

/** A named-query descriptor — checked SQL plus revisioned reactive metadata and a
 *  `bind(params)` → positional args. Consumed by
 *  `@syncular/react`'s `useQuery`. `Row` is the projection row
 *  type; `Params` is `undefined` for a param-less query. `sqlFor`
 *  selects a checked revision-1 SYQL physical statement when needed. */
export interface NamedQuery<Row, Params = undefined> {
  readonly id: string;
  readonly hasParams: boolean;
  readonly sql: string;
  readonly mapRow: (row: Readonly<Record<string, unknown>>) => Row;
  readonly tables: readonly string[];
  readonly bind: (params: Params) => readonly QueryValue[];
  readonly sqlFor?: (params: Params) => string;
  readonly dependencies: (params: Params) => readonly QueryDependency[];
  readonly coverage: (params: Params) => readonly WindowCoverage[];
  readonly rowKey?: (row: Row) => readonly QueryValue[];
  /** Phantom — carries the Row type for `useQuery` inference. */
  readonly __row?: Row;
}

export interface QueryDependency {
  readonly table: string;
  readonly scopeKeys?: readonly string[];
}

export interface WindowCoverage {
  readonly base: {
    readonly table: string;
    readonly variable: string;
    readonly fixedScopes?: Readonly<Record<string, readonly string[]>>;
    readonly params?: string;
  };
  readonly units: readonly string[];
}

/** One row of the 'booleanResults' query (its projection). */
export interface BooleanResultsRow {
  id: string;
  isDone: boolean;
  maybeDone: boolean | null;
}

/** Decode one storage-shaped result row for 'booleanResults'. */
export function booleanResultsMapRow(row: Readonly<Record<string, unknown>>): BooleanResultsRow {
  return {
    ...row,
    isDone: decodeQueryBoolean(row['isDone'], 'booleanResults', 'isDone'),
    maybeDone: row['maybeDone'] === null ? null : decodeQueryBoolean(row['maybeDone'], 'booleanResults', 'maybeDone'),
  } as unknown as BooleanResultsRow;
}

/** Tables 'booleanResults' reads (compatibility/export surface). */
export const booleanResultsTables = ['docs', 'tasks'] as const;

const booleanResultsSql = 'SELECT t.id, t.done AS isDone, t.reviewed AS maybeDone FROM tasks t JOIN docs d ON d.project_id = t.project_id ORDER BY t.id';

/** Run the 'booleanResults' named query (SELECT-only). */
export async function booleanResults(client: QueryClient): Promise<BooleanResultsRow[]> {
  const rows = await client.query(booleanResultsSql);
  return rows.map((row) => booleanResultsMapRow(row as Readonly<Record<string, unknown>>));
}

/** Revisioned reactive descriptor for `useQuery(booleanResultsQuery)`. */
export const booleanResultsQuery: NamedQuery<BooleanResultsRow, undefined> = {
  id: 'sha256:9f91145d5e1d17303de133edc87b440f6ad59fe2a081c2303db1dd01db831ac4/booleanResults',
  hasParams: false,
  sql: booleanResultsSql,
  mapRow: booleanResultsMapRow,
  tables: booleanResultsTables,
  dependencies: () => [
    { table: 'docs' },
    { table: 'tasks' },
  ],
  coverage: () => [
  ],
  bind: () => [],
};

/** One row of the 'findDocByOrg' query (its projection). */
export interface FindDocByOrgRow {
  id: string;
  body: string;
}

/** Decode one storage-shaped result row for 'findDocByOrg'. */
export function findDocByOrgMapRow(row: Readonly<Record<string, unknown>>): FindDocByOrgRow {
  return row as unknown as FindDocByOrgRow;
}

/** Named parameters for 'findDocByOrg'. */
export interface FindDocByOrgParams {
  orgId: string;
}

/** Tables 'findDocByOrg' reads (compatibility/export surface). */
export const findDocByOrgTables = ['docs'] as const;

const findDocByOrgSql = 'SELECT id, body FROM docs WHERE org_id = ? ORDER BY id';

/** Run the 'findDocByOrg' named query (SELECT-only). */
export async function findDocByOrg(client: QueryClient, params: FindDocByOrgParams): Promise<FindDocByOrgRow[]> {
  const rows = await client.query(findDocByOrgSql, [params.orgId]);
  return rows.map((row) => findDocByOrgMapRow(row as Readonly<Record<string, unknown>>));
}

/** Revisioned reactive descriptor for `useQuery(findDocByOrgQuery, params)`. */
export const findDocByOrgQuery: NamedQuery<FindDocByOrgRow, FindDocByOrgParams> = {
  id: 'sha256:9f91145d5e1d17303de133edc87b440f6ad59fe2a081c2303db1dd01db831ac4/findDocByOrg',
  hasParams: true,
  sql: findDocByOrgSql,
  mapRow: findDocByOrgMapRow,
  tables: findDocByOrgTables,
  dependencies: (params) => [
    { table: 'docs', scopeKeys: ['org:' + String(params.orgId) + ''] },
  ],
  coverage: () => [
  ],
  bind: (params: FindDocByOrgParams) => [params.orgId],
  rowKey: (row) => [row.id],
};

/** One row of the 'docValueTypes' query (its projection). */
export interface DocValueTypesRow {
  id: string;
  attachment: Uint8Array | null;
  bodyDoc: Uint8Array | null;
  remoteBlob: string | null;
}

/** Decode one storage-shaped result row for 'docValueTypes'. */
export function docValueTypesMapRow(row: Readonly<Record<string, unknown>>): DocValueTypesRow {
  return row as unknown as DocValueTypesRow;
}

/** Named parameters for 'docValueTypes'. */
export interface DocValueTypesParams {
  id: string;
}

/** Tables 'docValueTypes' reads (compatibility/export surface). */
export const docValueTypesTables = ['docs'] as const;

const docValueTypesSql = 'SELECT id, attachment, body_doc AS bodyDoc, remote_blob AS remoteBlob FROM docs WHERE id = ?';

/** Run the 'docValueTypes' named query (SELECT-only). */
export async function docValueTypes(client: QueryClient, params: DocValueTypesParams): Promise<DocValueTypesRow[]> {
  const rows = await client.query(docValueTypesSql, [params.id]);
  return rows.map((row) => docValueTypesMapRow(row as Readonly<Record<string, unknown>>));
}

/** Revisioned reactive descriptor for `useQuery(docValueTypesQuery, params)`. */
export const docValueTypesQuery: NamedQuery<DocValueTypesRow, DocValueTypesParams> = {
  id: 'sha256:9f91145d5e1d17303de133edc87b440f6ad59fe2a081c2303db1dd01db831ac4/docValueTypes',
  hasParams: true,
  sql: docValueTypesSql,
  mapRow: docValueTypesMapRow,
  tables: docValueTypesTables,
  dependencies: () => [
    { table: 'docs' },
  ],
  coverage: () => [
  ],
  bind: (params: DocValueTypesParams) => [params.id],
  rowKey: (row) => [row.id],
};

/** One row of the 'docWithBody' query (its projection). */
export interface DocWithBodyRow {
  docId: string;
  body: string;
  taskTitle: string;
}

/** Decode one storage-shaped result row for 'docWithBody'. */
export function docWithBodyMapRow(row: Readonly<Record<string, unknown>>): DocWithBodyRow {
  return row as unknown as DocWithBodyRow;
}

/** Named parameters for 'docWithBody'. */
export interface DocWithBodyParams {
  orgId: string;
}

/** Tables 'docWithBody' reads (compatibility/export surface). */
export const docWithBodyTables = ['docs', 'tasks'] as const;

const docWithBodySql = 'SELECT d.id AS docId, d.body, t.title AS taskTitle FROM docs d JOIN tasks t ON t.project_id = d.project_id WHERE d.org_id = ?';

/** Run the 'docWithBody' named query (SELECT-only). */
export async function docWithBody(client: QueryClient, params: DocWithBodyParams): Promise<DocWithBodyRow[]> {
  const rows = await client.query(docWithBodySql, [params.orgId]);
  return rows.map((row) => docWithBodyMapRow(row as Readonly<Record<string, unknown>>));
}

/** Revisioned reactive descriptor for `useQuery(docWithBodyQuery, params)`. */
export const docWithBodyQuery: NamedQuery<DocWithBodyRow, DocWithBodyParams> = {
  id: 'sha256:9f91145d5e1d17303de133edc87b440f6ad59fe2a081c2303db1dd01db831ac4/docWithBody',
  hasParams: true,
  sql: docWithBodySql,
  mapRow: docWithBodyMapRow,
  tables: docWithBodyTables,
  dependencies: (params) => [
    { table: 'docs', scopeKeys: ['org:' + String(params.orgId) + ''] },
    { table: 'tasks' },
  ],
  coverage: () => [
  ],
  bind: (params: DocWithBodyParams) => [params.orgId],
};

/** One row of the 'docsInProject' query (its projection). */
export interface DocsInProjectRow {
  id: string;
  body: string;
}

/** Decode one storage-shaped result row for 'docsInProject'. */
export function docsInProjectMapRow(row: Readonly<Record<string, unknown>>): DocsInProjectRow {
  return row as unknown as DocsInProjectRow;
}

/** Named parameters for 'docsInProject'. */
export interface DocsInProjectParams {
  orgId: string;
  projectId: string;
}

/** Tables 'docsInProject' reads (compatibility/export surface). */
export const docsInProjectTables = ['docs'] as const;

const docsInProjectSql = 'SELECT id, body FROM docs WHERE org_id = ? AND project_id = ? ORDER BY id';

/** Run the 'docsInProject' named query (SELECT-only). */
export async function docsInProject(client: QueryClient, params: DocsInProjectParams): Promise<DocsInProjectRow[]> {
  const rows = await client.query(docsInProjectSql, [params.orgId, params.projectId]);
  return rows.map((row) => docsInProjectMapRow(row as Readonly<Record<string, unknown>>));
}

/** Revisioned reactive descriptor for `useQuery(docsInProjectQuery, params)`. */
export const docsInProjectQuery: NamedQuery<DocsInProjectRow, DocsInProjectParams> = {
  id: 'sha256:9f91145d5e1d17303de133edc87b440f6ad59fe2a081c2303db1dd01db831ac4/docsInProject',
  hasParams: true,
  sql: docsInProjectSql,
  mapRow: docsInProjectMapRow,
  tables: docsInProjectTables,
  dependencies: (params) => [
    { table: 'docs', scopeKeys: ['org:' + String(params.orgId) + '', 'project:' + String(params.projectId) + ''] },
  ],
  coverage: (params) => [
    { base: { table: 'docs', variable: 'org_id', fixedScopes: { projectId: [String(params.projectId)] } }, units: [String(params.orgId)] },
  ],
  bind: (params: DocsInProjectParams) => [params.orgId, params.projectId],
  rowKey: (row) => [row.id],
};

/** One row of the 'hostBoolean' query (its projection). */
export interface HostBooleanRow {
  id: string;
  done: boolean;
}

/** Decode one storage-shaped result row for 'hostBoolean'. */
export function hostBooleanMapRow(row: Readonly<Record<string, unknown>>): HostBooleanRow {
  return {
    ...row,
    done: decodeQueryBoolean(row['done'], 'hostBoolean', 'done'),
  } as unknown as HostBooleanRow;
}

/** Named parameters for 'hostBoolean'. */
export interface HostBooleanParams {
  projectId: string;
}

/** Tables 'hostBoolean' reads (compatibility/export surface). */
export const hostBooleanTables = ['tasks'] as const;

const hostBooleanSql = 'SELECT id, done FROM tasks WHERE project_id = ? ORDER BY id';

/** Run the 'hostBoolean' named query (SELECT-only). */
export async function hostBoolean(client: QueryClient, params: HostBooleanParams): Promise<HostBooleanRow[]> {
  const rows = await client.query(hostBooleanSql, [params.projectId]);
  return rows.map((row) => hostBooleanMapRow(row as Readonly<Record<string, unknown>>));
}

/** Revisioned reactive descriptor for `useQuery(hostBooleanQuery, params)`. */
export const hostBooleanQuery: NamedQuery<HostBooleanRow, HostBooleanParams> = {
  id: 'sha256:9f91145d5e1d17303de133edc87b440f6ad59fe2a081c2303db1dd01db831ac4/hostBoolean',
  hasParams: true,
  sql: hostBooleanSql,
  mapRow: hostBooleanMapRow,
  tables: hostBooleanTables,
  dependencies: (params) => [
    { table: 'tasks', scopeKeys: ['project:' + String(params.projectId) + ''] },
  ],
  coverage: (params) => [
    { base: { table: 'tasks', variable: 'project_id' }, units: [String(params.projectId)] },
  ],
  bind: (params: HostBooleanParams) => [params.projectId],
  rowKey: (row) => [row.id],
};

/** One row of the 'listProjectTasks' query (its projection). */
export interface ListProjectTasksRow {
  id: string;
  title: string;
  done: boolean;
  priority: number | null;
  estimate: number | null;
}

/** Decode one storage-shaped result row for 'listProjectTasks'. */
export function listProjectTasksMapRow(row: Readonly<Record<string, unknown>>): ListProjectTasksRow {
  return {
    ...row,
    done: decodeQueryBoolean(row['done'], 'listProjectTasks', 'done'),
  } as unknown as ListProjectTasksRow;
}

/** Named parameters for 'listProjectTasks'. */
export interface ListProjectTasksParams {
  projectId: string;
}

/** Tables 'listProjectTasks' reads (compatibility/export surface). */
export const listProjectTasksTables = ['tasks'] as const;

const listProjectTasksSql = 'SELECT id, title, done, priority, estimate FROM tasks WHERE project_id = ? ORDER BY priority';

/** Run the 'listProjectTasks' named query (SELECT-only). */
export async function listProjectTasks(client: QueryClient, params: ListProjectTasksParams): Promise<ListProjectTasksRow[]> {
  const rows = await client.query(listProjectTasksSql, [params.projectId]);
  return rows.map((row) => listProjectTasksMapRow(row as Readonly<Record<string, unknown>>));
}

/** Revisioned reactive descriptor for `useQuery(listProjectTasksQuery, params)`. */
export const listProjectTasksQuery: NamedQuery<ListProjectTasksRow, ListProjectTasksParams> = {
  id: 'sha256:9f91145d5e1d17303de133edc87b440f6ad59fe2a081c2303db1dd01db831ac4/listProjectTasks',
  hasParams: true,
  sql: listProjectTasksSql,
  mapRow: listProjectTasksMapRow,
  tables: listProjectTasksTables,
  dependencies: (params) => [
    { table: 'tasks', scopeKeys: ['project:' + String(params.projectId) + ''] },
  ],
  coverage: (params) => [
    { base: { table: 'tasks', variable: 'project_id' }, units: [String(params.projectId)] },
  ],
  bind: (params: ListProjectTasksParams) => [params.projectId],
  rowKey: (row) => [row.id],
};

/** One row of the 'outerJoinValues' query (its projection). */
export interface OuterJoinValuesRow {
  taskId: string;
  title: string;
  docBody: string | null;
}

/** Decode one storage-shaped result row for 'outerJoinValues'. */
export function outerJoinValuesMapRow(row: Readonly<Record<string, unknown>>): OuterJoinValuesRow {
  return row as unknown as OuterJoinValuesRow;
}

/** Named parameters for 'outerJoinValues'. */
export interface OuterJoinValuesParams {
  taskId: string;
}

/** Tables 'outerJoinValues' reads (compatibility/export surface). */
export const outerJoinValuesTables = ['docs', 'tasks'] as const;

const outerJoinValuesSql = 'SELECT t.id AS taskId, t.title, d.body AS docBody FROM tasks AS t LEFT JOIN docs AS d ON d.project_id = t.project_id WHERE t.id = ?';

/** Run the 'outerJoinValues' named query (SELECT-only). */
export async function outerJoinValues(client: QueryClient, params: OuterJoinValuesParams): Promise<OuterJoinValuesRow[]> {
  const rows = await client.query(outerJoinValuesSql, [params.taskId]);
  return rows.map((row) => outerJoinValuesMapRow(row as Readonly<Record<string, unknown>>));
}

/** Revisioned reactive descriptor for `useQuery(outerJoinValuesQuery, params)`. */
export const outerJoinValuesQuery: NamedQuery<OuterJoinValuesRow, OuterJoinValuesParams> = {
  id: 'sha256:9f91145d5e1d17303de133edc87b440f6ad59fe2a081c2303db1dd01db831ac4/outerJoinValues',
  hasParams: true,
  sql: outerJoinValuesSql,
  mapRow: outerJoinValuesMapRow,
  tables: outerJoinValuesTables,
  dependencies: () => [
    { table: 'docs' },
    { table: 'tasks' },
  ],
  coverage: () => [
  ],
  bind: (params: OuterJoinValuesParams) => [params.taskId],
};

/** One row of the 'projectDocCount' query (its projection). */
export interface ProjectDocCountRow {
  projectId: string;
  docCount: number | null;
}

/** Decode one storage-shaped result row for 'projectDocCount'. */
export function projectDocCountMapRow(row: Readonly<Record<string, unknown>>): ProjectDocCountRow {
  return row as unknown as ProjectDocCountRow;
}

/** Tables 'projectDocCount' reads (compatibility/export surface). */
export const projectDocCountTables = ['docs'] as const;

const projectDocCountSql = 'SELECT project_id AS projectId, count(*) AS docCount FROM docs GROUP BY project_id';

/** Run the 'projectDocCount' named query (SELECT-only). */
export async function projectDocCount(client: QueryClient): Promise<ProjectDocCountRow[]> {
  const rows = await client.query(projectDocCountSql);
  return rows.map((row) => projectDocCountMapRow(row as Readonly<Record<string, unknown>>));
}

/** Revisioned reactive descriptor for `useQuery(projectDocCountQuery)`. */
export const projectDocCountQuery: NamedQuery<ProjectDocCountRow, undefined> = {
  id: 'sha256:9f91145d5e1d17303de133edc87b440f6ad59fe2a081c2303db1dd01db831ac4/projectDocCount',
  hasParams: false,
  sql: projectDocCountSql,
  mapRow: projectDocCountMapRow,
  tables: projectDocCountTables,
  dependencies: () => [
    { table: 'docs' },
  ],
  coverage: () => [
  ],
  bind: () => [],
};

/** One row of the 'reportingTasksByPriority' query (its projection). */
export interface ReportingTasksByPriorityRow {
  id: string;
  title: string;
  priority: number | null;
}

/** Decode one storage-shaped result row for 'reportingTasksByPriority'. */
export function reportingTasksByPriorityMapRow(row: Readonly<Record<string, unknown>>): ReportingTasksByPriorityRow {
  return row as unknown as ReportingTasksByPriorityRow;
}

/** Named parameters for 'reportingTasksByPriority'. */
export interface ReportingTasksByPriorityParams {
  priority: number;
}

/** Tables 'reportingTasksByPriority' reads (compatibility/export surface). */
export const reportingTasksByPriorityTables = ['tasks'] as const;

const reportingTasksByPrioritySql = 'SELECT id, title, priority FROM tasks WHERE priority = ? ORDER BY id';

/** Run the 'reportingTasksByPriority' named query (SELECT-only). */
export async function reportingTasksByPriority(client: QueryClient, params: ReportingTasksByPriorityParams): Promise<ReportingTasksByPriorityRow[]> {
  const rows = await client.query(reportingTasksByPrioritySql, [params.priority]);
  return rows.map((row) => reportingTasksByPriorityMapRow(row as Readonly<Record<string, unknown>>));
}

/** Revisioned reactive descriptor for `useQuery(reportingTasksByPriorityQuery, params)`. */
export const reportingTasksByPriorityQuery: NamedQuery<ReportingTasksByPriorityRow, ReportingTasksByPriorityParams> = {
  id: 'sha256:9f91145d5e1d17303de133edc87b440f6ad59fe2a081c2303db1dd01db831ac4/reportingTasksByPriority',
  hasParams: true,
  sql: reportingTasksByPrioritySql,
  mapRow: reportingTasksByPriorityMapRow,
  tables: reportingTasksByPriorityTables,
  dependencies: () => [
    { table: 'tasks' },
  ],
  coverage: () => [
  ],
  bind: (params: ReportingTasksByPriorityParams) => [params.priority],
  rowKey: (row) => [row.id],
};

/** One row of the 'reportOpenTasks' query (its projection). */
export interface ReportOpenTasksRow {
  id: string;
  title: string;
  done: boolean;
}

/** Decode one storage-shaped result row for 'reportOpenTasks'. */
export function reportOpenTasksMapRow(row: Readonly<Record<string, unknown>>): ReportOpenTasksRow {
  return {
    ...row,
    done: decodeQueryBoolean(row['done'], 'reportOpenTasks', 'done'),
  } as unknown as ReportOpenTasksRow;
}

/** Named parameters for 'reportOpenTasks'. */
export interface ReportOpenTasksParams {
  projectId: string;
}

/** Tables 'reportOpenTasks' reads (compatibility/export surface). */
export const reportOpenTasksTables = ['tasks'] as const;

const reportOpenTasksSql = 'SELECT id, title, done FROM tasks WHERE project_id = ? AND done = 0 ORDER BY id';

/** Run the 'reportOpenTasks' named query (SELECT-only). */
export async function reportOpenTasks(client: QueryClient, params: ReportOpenTasksParams): Promise<ReportOpenTasksRow[]> {
  const rows = await client.query(reportOpenTasksSql, [params.projectId]);
  return rows.map((row) => reportOpenTasksMapRow(row as Readonly<Record<string, unknown>>));
}

/** Revisioned reactive descriptor for `useQuery(reportOpenTasksQuery, params)`. */
export const reportOpenTasksQuery: NamedQuery<ReportOpenTasksRow, ReportOpenTasksParams> = {
  id: 'sha256:9f91145d5e1d17303de133edc87b440f6ad59fe2a081c2303db1dd01db831ac4/reportOpenTasks',
  hasParams: true,
  sql: reportOpenTasksSql,
  mapRow: reportOpenTasksMapRow,
  tables: reportOpenTasksTables,
  dependencies: (params) => [
    { table: 'tasks', scopeKeys: ['project:' + String(params.projectId) + ''] },
  ],
  coverage: (params) => [
    { base: { table: 'tasks', variable: 'project_id' }, units: [String(params.projectId)] },
  ],
  bind: (params: ReportOpenTasksParams) => [params.projectId],
  rowKey: (row) => [row.id],
};

/** One row of the 'reportDocScores' query (its projection). */
export interface ReportDocScoresRow {
  id: string;
  orgId: string;
  score: number | null;
}

/** Decode one storage-shaped result row for 'reportDocScores'. */
export function reportDocScoresMapRow(row: Readonly<Record<string, unknown>>): ReportDocScoresRow {
  return row as unknown as ReportDocScoresRow;
}

/** Named parameters for 'reportDocScores'. */
export interface ReportDocScoresParams {
  minScore: number;
}

/** Tables 'reportDocScores' reads (compatibility/export surface). */
export const reportDocScoresTables = ['docs'] as const;

const reportDocScoresSql = 'SELECT id, org_id AS orgId, score FROM docs WHERE score > ? * 1.0 ORDER BY id';

/** Run the 'reportDocScores' named query (SELECT-only). */
export async function reportDocScores(client: QueryClient, params: ReportDocScoresParams): Promise<ReportDocScoresRow[]> {
  const rows = await client.query(reportDocScoresSql, [params.minScore]);
  return rows.map((row) => reportDocScoresMapRow(row as Readonly<Record<string, unknown>>));
}

/** Revisioned reactive descriptor for `useQuery(reportDocScoresQuery, params)`. */
export const reportDocScoresQuery: NamedQuery<ReportDocScoresRow, ReportDocScoresParams> = {
  id: 'sha256:9f91145d5e1d17303de133edc87b440f6ad59fe2a081c2303db1dd01db831ac4/reportDocScores',
  hasParams: true,
  sql: reportDocScoresSql,
  mapRow: reportDocScoresMapRow,
  tables: reportDocScoresTables,
  dependencies: () => [
    { table: 'docs' },
  ],
  coverage: () => [
  ],
  bind: (params: ReportDocScoresParams) => [params.minScore],
  rowKey: (row) => [row.id],
};

/** One row of the 'taskTitles' query (its projection). */
export interface TaskTitlesRow {
  id: string;
  title: string;
}

/** Decode one storage-shaped result row for 'taskTitles'. */
export function taskTitlesMapRow(row: Readonly<Record<string, unknown>>): TaskTitlesRow {
  return row as unknown as TaskTitlesRow;
}

/** Tables 'taskTitles' reads (compatibility/export surface). */
export const taskTitlesTables = ['tasks'] as const;

const taskTitlesSql = 'SELECT id, title FROM tasks';

/** Run the 'taskTitles' named query (SELECT-only). */
export async function taskTitles(client: QueryClient): Promise<TaskTitlesRow[]> {
  const rows = await client.query(taskTitlesSql);
  return rows.map((row) => taskTitlesMapRow(row as Readonly<Record<string, unknown>>));
}

/** Revisioned reactive descriptor for `useQuery(taskTitlesQuery)`. */
export const taskTitlesQuery: NamedQuery<TaskTitlesRow, undefined> = {
  id: 'sha256:9f91145d5e1d17303de133edc87b440f6ad59fe2a081c2303db1dd01db831ac4/taskTitles',
  hasParams: false,
  sql: taskTitlesSql,
  mapRow: taskTitlesMapRow,
  tables: taskTitlesTables,
  dependencies: () => [
    { table: 'tasks' },
  ],
  coverage: () => [
  ],
  bind: () => [],
  rowKey: (row) => [row.id],
};

/** One row of the 'taskValueTypes' query (its projection). */
export interface TaskValueTypesRow {
  id: string;
  done: boolean;
  priority: number | null;
  estimate: number | null;
  meta: string | null;
}

/** Decode one storage-shaped result row for 'taskValueTypes'. */
export function taskValueTypesMapRow(row: Readonly<Record<string, unknown>>): TaskValueTypesRow {
  return {
    ...row,
    done: decodeQueryBoolean(row['done'], 'taskValueTypes', 'done'),
  } as unknown as TaskValueTypesRow;
}

/** Named parameters for 'taskValueTypes'. */
export interface TaskValueTypesParams {
  id: string;
}

/** Tables 'taskValueTypes' reads (compatibility/export surface). */
export const taskValueTypesTables = ['tasks'] as const;

const taskValueTypesSql = 'SELECT id, done, priority, estimate, meta FROM tasks WHERE id = ?';

/** Run the 'taskValueTypes' named query (SELECT-only). */
export async function taskValueTypes(client: QueryClient, params: TaskValueTypesParams): Promise<TaskValueTypesRow[]> {
  const rows = await client.query(taskValueTypesSql, [params.id]);
  return rows.map((row) => taskValueTypesMapRow(row as Readonly<Record<string, unknown>>));
}

/** Revisioned reactive descriptor for `useQuery(taskValueTypesQuery, params)`. */
export const taskValueTypesQuery: NamedQuery<TaskValueTypesRow, TaskValueTypesParams> = {
  id: 'sha256:9f91145d5e1d17303de133edc87b440f6ad59fe2a081c2303db1dd01db831ac4/taskValueTypes',
  hasParams: true,
  sql: taskValueTypesSql,
  mapRow: taskValueTypesMapRow,
  tables: taskValueTypesTables,
  dependencies: () => [
    { table: 'tasks' },
  ],
  coverage: () => [
  ],
  bind: (params: TaskValueTypesParams) => [params.id],
  rowKey: (row) => [row.id],
};

/** One row of the 'tasksInProjects' query (its projection). */
export interface TasksInProjectsRow {
  id: string;
  title: string;
}

/** Decode one storage-shaped result row for 'tasksInProjects'. */
export function tasksInProjectsMapRow(row: Readonly<Record<string, unknown>>): TasksInProjectsRow {
  return row as unknown as TasksInProjectsRow;
}

/** Named parameters for 'tasksInProjects'. */
export interface TasksInProjectsParams {
  first: string;
  second: string;
}

/** Tables 'tasksInProjects' reads (compatibility/export surface). */
export const tasksInProjectsTables = ['tasks'] as const;

const tasksInProjectsSql = 'SELECT id, title FROM tasks WHERE project_id IN (?, ?)';

/** Run the 'tasksInProjects' named query (SELECT-only). */
export async function tasksInProjects(client: QueryClient, params: TasksInProjectsParams): Promise<TasksInProjectsRow[]> {
  const rows = await client.query(tasksInProjectsSql, [params.first, params.second]);
  return rows.map((row) => tasksInProjectsMapRow(row as Readonly<Record<string, unknown>>));
}

/** Revisioned reactive descriptor for `useQuery(tasksInProjectsQuery, params)`. */
export const tasksInProjectsQuery: NamedQuery<TasksInProjectsRow, TasksInProjectsParams> = {
  id: 'sha256:9f91145d5e1d17303de133edc87b440f6ad59fe2a081c2303db1dd01db831ac4/tasksInProjects',
  hasParams: true,
  sql: tasksInProjectsSql,
  mapRow: tasksInProjectsMapRow,
  tables: tasksInProjectsTables,
  dependencies: (params) => [
    { table: 'tasks', scopeKeys: ['project:' + String(params.first) + '', 'project:' + String(params.second) + ''] },
  ],
  coverage: (params) => [
    { base: { table: 'tasks', variable: 'project_id' }, units: [String(params.first), String(params.second)] },
  ],
  bind: (params: TasksInProjectsParams) => [params.first, params.second],
  rowKey: (row) => [row.id],
};

/** One row of the 'tasksSince' query (its projection). */
export interface TasksSinceRow {
  id: string;
  title: string;
}

/** Decode one storage-shaped result row for 'tasksSince'. */
export function tasksSinceMapRow(row: Readonly<Record<string, unknown>>): TasksSinceRow {
  return row as unknown as TasksSinceRow;
}

/** Named parameters for 'tasksSince'. */
export interface TasksSinceParams {
  sinceMs: number;
}

/** Tables 'tasksSince' reads (compatibility/export surface). */
export const tasksSinceTables = ['tasks'] as const;

const tasksSinceSql = 'SELECT id, title FROM tasks WHERE estimated_at > ? + 0';

/** Run the 'tasksSince' named query (SELECT-only). */
export async function tasksSince(client: QueryClient, params: TasksSinceParams): Promise<TasksSinceRow[]> {
  const rows = await client.query(tasksSinceSql, [params.sinceMs]);
  return rows.map((row) => tasksSinceMapRow(row as Readonly<Record<string, unknown>>));
}

/** Revisioned reactive descriptor for `useQuery(tasksSinceQuery, params)`. */
export const tasksSinceQuery: NamedQuery<TasksSinceRow, TasksSinceParams> = {
  id: 'sha256:9f91145d5e1d17303de133edc87b440f6ad59fe2a081c2303db1dd01db831ac4/tasksSince',
  hasParams: true,
  sql: tasksSinceSql,
  mapRow: tasksSinceMapRow,
  tables: tasksSinceTables,
  dependencies: () => [
    { table: 'tasks' },
  ],
  coverage: () => [
  ],
  bind: (params: TasksSinceParams) => [params.sinceMs],
  rowKey: (row) => [row.id],
};

/** One row of the 'joinedSyncCoverage' query (its projection). */
export interface JoinedSyncCoverageRow {
  taskId: string;
  docId: string;
  body: string;
}

/** Decode one storage-shaped result row for 'joinedSyncCoverage'. */
export function joinedSyncCoverageMapRow(row: Readonly<Record<string, unknown>>): JoinedSyncCoverageRow {
  return row as unknown as JoinedSyncCoverageRow;
}

/** Public revision-1 SYQL inputs for 'joinedSyncCoverage'. */
export interface JoinedSyncCoverageParams {
  orgId: string;
  projectId: string;
}

function joinedSyncCoverageValidate(raw?: JoinedSyncCoverageParams): JoinedSyncCoverageParams {
  const params = raw ?? ({} as JoinedSyncCoverageParams);
  const allowed = new Set(['orgId', 'projectId']);
  for (const key of Object.keys(params)) {
    if (!allowed.has(key)) throw new SyqlInputError('SYQL_RUNTIME_UNKNOWN_INPUT', 'joinedSyncCoverage' + ': unknown input ' + key);
  }
  if (!Object.prototype.hasOwnProperty.call(params, 'orgId')) throw new SyqlInputError('SYQL_RUNTIME_MISSING_REQUIRED_INPUT', 'joinedSyncCoverage: missing required input orgId');
  if (!(typeof params.orgId === 'string')) throw new SyqlInputError('SYQL_RUNTIME_INVALID_INPUT', 'joinedSyncCoverage: invalid input orgId');
  if (!Object.prototype.hasOwnProperty.call(params, 'projectId')) throw new SyqlInputError('SYQL_RUNTIME_MISSING_REQUIRED_INPUT', 'joinedSyncCoverage: missing required input projectId');
  if (!(typeof params.projectId === 'string')) throw new SyqlInputError('SYQL_RUNTIME_INVALID_INPUT', 'joinedSyncCoverage: invalid input projectId');
  return params;
}

/** Tables 'joinedSyncCoverage' reads (compatibility/export surface). */
export const joinedSyncCoverageTables = ['docs', 'tasks'] as const;

const joinedSyncCoverageStatements: { sql: string; bind: (params: JoinedSyncCoverageParams) => QueryValue[] }[] = [
  { sql: 'select t.id AS taskId, d.id AS docId, d.body from tasks as t join docs as d on d.project_id = t.project_id where t.project_id = ? and d.org_id = ? order by t.id, d.id', bind: (params) => [params.projectId, params.orgId] },
];
function joinedSyncCoverageSelect(raw: JoinedSyncCoverageParams): { sql: string; bind: QueryValue[] } {
  const params = joinedSyncCoverageValidate(raw);
  let mask = 0;
  const statement = joinedSyncCoverageStatements[mask * 1 + 0];
  if (statement === undefined) throw new Error('invalid generated SYQL statement index');
  return { sql: statement.sql, bind: statement.bind(params) };
}

/** Run the 'joinedSyncCoverage' named query (SELECT-only). */
export async function joinedSyncCoverage(client: QueryClient, params: JoinedSyncCoverageParams): Promise<JoinedSyncCoverageRow[]> {
  const selected = joinedSyncCoverageSelect(params);
  const rows = await client.query(selected.sql, selected.bind);
  return rows.map((row) => joinedSyncCoverageMapRow(row as Readonly<Record<string, unknown>>));
}

/** Revisioned reactive descriptor for `useQuery(joinedSyncCoverageQuery, params)`. */
export const joinedSyncCoverageQuery: NamedQuery<JoinedSyncCoverageRow, JoinedSyncCoverageParams> = {
  id: 'sha256:9f91145d5e1d17303de133edc87b440f6ad59fe2a081c2303db1dd01db831ac4/joinedSyncCoverage',
  hasParams: true,
  sql: 'select t.id AS taskId, d.id AS docId, d.body from tasks as t join docs as d on d.project_id = t.project_id where t.project_id = ? and d.org_id = ? order by t.id, d.id',
  mapRow: joinedSyncCoverageMapRow,
  sqlFor: (params: JoinedSyncCoverageParams) => joinedSyncCoverageSelect(params).sql,
  tables: joinedSyncCoverageTables,
  dependencies: (params) => [
    { table: 'docs', scopeKeys: ['org:' + String(params.orgId) + '', 'project:' + String(params.projectId) + ''] },
    { table: 'tasks', scopeKeys: ['project:' + String(params.projectId) + ''] },
  ],
  coverage: (params) => [
    { base: { table: 'docs', variable: 'projectId', fixedScopes: { org_id: [String(params.orgId)] } }, units: [String(params.projectId)] },
    { base: { table: 'tasks', variable: 'project_id' }, units: [String(params.projectId)] },
  ],
  bind: (params: JoinedSyncCoverageParams) => joinedSyncCoverageSelect(params).bind,
  rowKey: (row) => [row.taskId, row.docId],
};

/** One row of the 'taskMetaFilter' query (its projection). */
export interface TaskMetaFilterRow {
  id: string;
  meta: string | null;
}

/** Decode one storage-shaped result row for 'taskMetaFilter'. */
export function taskMetaFilterMapRow(row: Readonly<Record<string, unknown>>): TaskMetaFilterRow {
  return row as unknown as TaskMetaFilterRow;
}

/** Public revision-1 SYQL inputs for 'taskMetaFilter'. */
export interface TaskMetaFilterParams {
  projectId: string;
  meta?: SyqlPresent<string | null>;
}

function taskMetaFilterValidate(raw?: TaskMetaFilterParams): TaskMetaFilterParams {
  const params = raw ?? ({} as TaskMetaFilterParams);
  const allowed = new Set(['projectId', 'meta']);
  for (const key of Object.keys(params)) {
    if (!allowed.has(key)) throw new SyqlInputError('SYQL_RUNTIME_UNKNOWN_INPUT', 'taskMetaFilter' + ': unknown input ' + key);
  }
  if (!Object.prototype.hasOwnProperty.call(params, 'projectId')) throw new SyqlInputError('SYQL_RUNTIME_MISSING_REQUIRED_INPUT', 'taskMetaFilter: missing required input projectId');
  if (!(typeof params.projectId === 'string')) throw new SyqlInputError('SYQL_RUNTIME_INVALID_INPUT', 'taskMetaFilter: invalid input projectId');
  if (params.meta !== undefined && (typeof params.meta !== 'object' || params.meta === null || params.meta.present !== true || !(params.meta.value === null || (typeof params.meta.value === 'string')))) throw new SyqlInputError('SYQL_RUNTIME_INVALID_INPUT', 'taskMetaFilter: invalid optional input meta');
  return params;
}

/** Tables 'taskMetaFilter' reads (compatibility/export surface). */
export const taskMetaFilterTables = ['tasks'] as const;

const taskMetaFilterStatements: { sql: string; bind: (params: TaskMetaFilterParams) => QueryValue[] }[] = [
  { sql: 'select id, meta from tasks where tasks.project_id = ? and 1 order by id', bind: (params) => [params.projectId] },
  { sql: 'select id, meta from tasks where tasks.project_id = ? and ( meta is ?) order by id', bind: (params) => [params.projectId, params.meta?.value ?? null] },
];
function taskMetaFilterSelect(raw: TaskMetaFilterParams): { sql: string; bind: QueryValue[] } {
  const params = taskMetaFilterValidate(raw);
  let mask = 0;
  if (params.meta !== undefined) mask |= 1;
  const statement = taskMetaFilterStatements[mask * 1 + 0];
  if (statement === undefined) throw new Error('invalid generated SYQL statement index');
  return { sql: statement.sql, bind: statement.bind(params) };
}

/** Run the 'taskMetaFilter' named query (SELECT-only). */
export async function taskMetaFilter(client: QueryClient, params: TaskMetaFilterParams): Promise<TaskMetaFilterRow[]> {
  const selected = taskMetaFilterSelect(params);
  const rows = await client.query(selected.sql, selected.bind);
  return rows.map((row) => taskMetaFilterMapRow(row as Readonly<Record<string, unknown>>));
}

/** Revisioned reactive descriptor for `useQuery(taskMetaFilterQuery, params)`. */
export const taskMetaFilterQuery: NamedQuery<TaskMetaFilterRow, TaskMetaFilterParams> = {
  id: 'sha256:9f91145d5e1d17303de133edc87b440f6ad59fe2a081c2303db1dd01db831ac4/taskMetaFilter',
  hasParams: true,
  sql: 'select id, meta from tasks where tasks.project_id = ? and 1 order by id',
  mapRow: taskMetaFilterMapRow,
  sqlFor: (params: TaskMetaFilterParams) => taskMetaFilterSelect(params).sql,
  tables: taskMetaFilterTables,
  dependencies: (params) => [
    { table: 'tasks', scopeKeys: ['project:' + String(params.projectId) + ''] },
  ],
  coverage: () => [
  ],
  bind: (params: TaskMetaFilterParams) => taskMetaFilterSelect(params).bind,
  rowKey: (row) => [row.id],
};

/** One row of the 'searchTasks' query (its projection). */
export interface SearchTasksRow {
  id: string;
  title: string;
  done: boolean;
  priority: number | null;
  estimatedAt: number | null;
}

/** Decode one storage-shaped result row for 'searchTasks'. */
export function searchTasksMapRow(row: Readonly<Record<string, unknown>>): SearchTasksRow {
  return {
    ...row,
    done: decodeQueryBoolean(row['done'], 'searchTasks', 'done'),
  } as unknown as SearchTasksRow;
}

/** Public revision-1 SYQL inputs for 'searchTasks'. */
export interface SearchTasksParams {
  projectId: string;
  needle?: string;
  minPriority?: bigint;
  openOnly?: boolean;
  sortBy?: 'priorityAsc' | 'priorityDesc' | 'estimatedAtAsc' | 'estimatedAtDesc' | 'titleAsc' | 'titleDesc';
  pageSize?: number;
}

function searchTasksValidate(raw?: SearchTasksParams): SearchTasksParams {
  const params = raw ?? ({} as SearchTasksParams);
  const allowed = new Set(['projectId', 'needle', 'minPriority', 'openOnly', 'sortBy', 'pageSize']);
  for (const key of Object.keys(params)) {
    if (!allowed.has(key)) throw new SyqlInputError('SYQL_RUNTIME_UNKNOWN_INPUT', 'searchTasks' + ': unknown input ' + key);
  }
  if (!Object.prototype.hasOwnProperty.call(params, 'projectId')) throw new SyqlInputError('SYQL_RUNTIME_MISSING_REQUIRED_INPUT', 'searchTasks: missing required input projectId');
  if (!(typeof params.projectId === 'string')) throw new SyqlInputError('SYQL_RUNTIME_INVALID_INPUT', 'searchTasks: invalid input projectId');
  if (params.needle !== undefined && !(typeof params.needle === 'string')) throw new SyqlInputError('SYQL_RUNTIME_INVALID_INPUT', 'searchTasks: invalid optional input needle');
  if (params.minPriority !== undefined && !(typeof params.minPriority === 'bigint')) throw new SyqlInputError('SYQL_RUNTIME_INVALID_INPUT', 'searchTasks: invalid optional input minPriority');
  if (params.openOnly !== undefined && !(typeof params.openOnly === 'boolean')) throw new SyqlInputError('SYQL_RUNTIME_INVALID_INPUT', 'searchTasks: invalid optional input openOnly');
  if (params.sortBy !== undefined && !['priorityAsc', 'priorityDesc', 'estimatedAtAsc', 'estimatedAtDesc', 'titleAsc', 'titleDesc'].includes(params.sortBy)) throw new SyqlInputError('SYQL_RUNTIME_INVALID_SORT', 'searchTasks: invalid sort profile');
  if (params.pageSize !== undefined && (!Number.isSafeInteger(params.pageSize) || params.pageSize < 1 || params.pageSize > 200)) throw new SyqlInputError('SYQL_RUNTIME_INVALID_LIMIT', 'searchTasks: limit must be an integer from 1 through 200');
  return params;
}

/** Tables 'searchTasks' reads (compatibility/export surface). */
export const searchTasksTables = ['tasks'] as const;

const searchTasksStatements: { sql: string; bind: (params: SearchTasksParams) => QueryValue[] }[] = [
  { sql: 'select id, title, done, priority, estimated_at AS estimatedAt from tasks where tasks.project_id = ? and case when ? = 0 then 1 else ( ( title like \'%\' || ? || \'%\' )) end and case when ? = 0 then 1 else ( priority >= ?) end and case when ? = 0 then 1 else ( done = 0 ) end order by priority asc, id asc limit min(coalesce(?, 50), 200)', bind: (params) => [params.projectId, params.needle !== undefined, params.needle ?? null, params.minPriority !== undefined, params.minPriority ?? null, params.openOnly === true, params.pageSize ?? 50] },
  { sql: 'select id, title, done, priority, estimated_at AS estimatedAt from tasks where tasks.project_id = ? and case when ? = 0 then 1 else ( ( title like \'%\' || ? || \'%\' )) end and case when ? = 0 then 1 else ( priority >= ?) end and case when ? = 0 then 1 else ( done = 0 ) end order by priority desc, id desc limit min(coalesce(?, 50), 200)', bind: (params) => [params.projectId, params.needle !== undefined, params.needle ?? null, params.minPriority !== undefined, params.minPriority ?? null, params.openOnly === true, params.pageSize ?? 50] },
  { sql: 'select id, title, done, priority, estimated_at AS estimatedAt from tasks where tasks.project_id = ? and case when ? = 0 then 1 else ( ( title like \'%\' || ? || \'%\' )) end and case when ? = 0 then 1 else ( priority >= ?) end and case when ? = 0 then 1 else ( done = 0 ) end order by estimated_at asc, id asc limit min(coalesce(?, 50), 200)', bind: (params) => [params.projectId, params.needle !== undefined, params.needle ?? null, params.minPriority !== undefined, params.minPriority ?? null, params.openOnly === true, params.pageSize ?? 50] },
  { sql: 'select id, title, done, priority, estimated_at AS estimatedAt from tasks where tasks.project_id = ? and case when ? = 0 then 1 else ( ( title like \'%\' || ? || \'%\' )) end and case when ? = 0 then 1 else ( priority >= ?) end and case when ? = 0 then 1 else ( done = 0 ) end order by estimated_at desc, id desc limit min(coalesce(?, 50), 200)', bind: (params) => [params.projectId, params.needle !== undefined, params.needle ?? null, params.minPriority !== undefined, params.minPriority ?? null, params.openOnly === true, params.pageSize ?? 50] },
  { sql: 'select id, title, done, priority, estimated_at AS estimatedAt from tasks where tasks.project_id = ? and case when ? = 0 then 1 else ( ( title like \'%\' || ? || \'%\' )) end and case when ? = 0 then 1 else ( priority >= ?) end and case when ? = 0 then 1 else ( done = 0 ) end order by title asc, id asc limit min(coalesce(?, 50), 200)', bind: (params) => [params.projectId, params.needle !== undefined, params.needle ?? null, params.minPriority !== undefined, params.minPriority ?? null, params.openOnly === true, params.pageSize ?? 50] },
  { sql: 'select id, title, done, priority, estimated_at AS estimatedAt from tasks where tasks.project_id = ? and case when ? = 0 then 1 else ( ( title like \'%\' || ? || \'%\' )) end and case when ? = 0 then 1 else ( priority >= ?) end and case when ? = 0 then 1 else ( done = 0 ) end order by title desc, id desc limit min(coalesce(?, 50), 200)', bind: (params) => [params.projectId, params.needle !== undefined, params.needle ?? null, params.minPriority !== undefined, params.minPriority ?? null, params.openOnly === true, params.pageSize ?? 50] },
];
const searchTasksSortIndexes = { priorityAsc: 0, priorityDesc: 1, estimatedAtAsc: 2, estimatedAtDesc: 3, titleAsc: 4, titleDesc: 5 } as const;
function searchTasksSelect(raw: SearchTasksParams): { sql: string; bind: QueryValue[] } {
  const params = searchTasksValidate(raw);
  const statement = searchTasksStatements[searchTasksSortIndexes[params.sortBy ?? 'priorityDesc']];
  if (statement === undefined) throw new Error('invalid generated SYQL statement index');
  return { sql: statement.sql, bind: statement.bind(params) };
}

/** Run the 'searchTasks' named query (SELECT-only). */
export async function searchTasks(client: QueryClient, params: SearchTasksParams): Promise<SearchTasksRow[]> {
  const selected = searchTasksSelect(params);
  const rows = await client.query(selected.sql, selected.bind);
  return rows.map((row) => searchTasksMapRow(row as Readonly<Record<string, unknown>>));
}

/** Revisioned reactive descriptor for `useQuery(searchTasksQuery, params)`. */
export const searchTasksQuery: NamedQuery<SearchTasksRow, SearchTasksParams> = {
  id: 'sha256:9f91145d5e1d17303de133edc87b440f6ad59fe2a081c2303db1dd01db831ac4/searchTasks',
  hasParams: true,
  sql: 'select id, title, done, priority, estimated_at AS estimatedAt from tasks where tasks.project_id = ? and case when ? = 0 then 1 else ( ( title like \'%\' || ? || \'%\' )) end and case when ? = 0 then 1 else ( priority >= ?) end and case when ? = 0 then 1 else ( done = 0 ) end order by priority desc, id desc limit min(coalesce(?, 50), 200)',
  mapRow: searchTasksMapRow,
  sqlFor: (params: SearchTasksParams) => searchTasksSelect(params).sql,
  tables: searchTasksTables,
  dependencies: (params) => [
    { table: 'tasks', scopeKeys: ['project:' + String(params.projectId) + ''] },
  ],
  coverage: () => [
  ],
  bind: (params: SearchTasksParams) => searchTasksSelect(params).bind,
  rowKey: (row) => [row.id],
};

/** One row of the 'taskEstimateRange' query (its projection). */
export interface TaskEstimateRangeRow {
  id: string;
  title: string;
  estimate: number | null;
}

/** Decode one storage-shaped result row for 'taskEstimateRange'. */
export function taskEstimateRangeMapRow(row: Readonly<Record<string, unknown>>): TaskEstimateRangeRow {
  return row as unknown as TaskEstimateRangeRow;
}

export interface TaskEstimateRangeRange {
  start: bigint;
  end: bigint;
}

/** Public revision-1 SYQL inputs for 'taskEstimateRange'. */
export interface TaskEstimateRangeParams {
  projectId: string;
  range?: TaskEstimateRangeRange;
}

function taskEstimateRangeValidate(raw?: TaskEstimateRangeParams): TaskEstimateRangeParams {
  const params = raw ?? ({} as TaskEstimateRangeParams);
  const allowed = new Set(['projectId', 'range']);
  for (const key of Object.keys(params)) {
    if (!allowed.has(key)) throw new SyqlInputError('SYQL_RUNTIME_UNKNOWN_INPUT', 'taskEstimateRange' + ': unknown input ' + key);
  }
  if (!Object.prototype.hasOwnProperty.call(params, 'projectId')) throw new SyqlInputError('SYQL_RUNTIME_MISSING_REQUIRED_INPUT', 'taskEstimateRange: missing required input projectId');
  if (!(typeof params.projectId === 'string')) throw new SyqlInputError('SYQL_RUNTIME_INVALID_INPUT', 'taskEstimateRange: invalid input projectId');
  if (params.range !== undefined) {
    if (typeof params.range !== 'object' || params.range === null) throw new SyqlInputError('SYQL_RUNTIME_INVALID_GROUP', 'taskEstimateRange: invalid group range');
    const allowedMembers = new Set(['start', 'end']);
    if (Object.keys(params.range).some((key) => !allowedMembers.has(key))) throw new SyqlInputError('SYQL_RUNTIME_INVALID_GROUP', 'taskEstimateRange: unknown member in group range');
    if (!Object.prototype.hasOwnProperty.call(params.range, 'start') || !(typeof params.range.start === 'bigint')) throw new SyqlInputError('SYQL_RUNTIME_INVALID_GROUP', 'taskEstimateRange: invalid or partial group range');
    if (!Object.prototype.hasOwnProperty.call(params.range, 'end') || !(typeof params.range.end === 'bigint')) throw new SyqlInputError('SYQL_RUNTIME_INVALID_GROUP', 'taskEstimateRange: invalid or partial group range');
  }
  return params;
}

/** Tables 'taskEstimateRange' reads (compatibility/export surface). */
export const taskEstimateRangeTables = ['tasks'] as const;

const taskEstimateRangeStatements: { sql: string; bind: (params: TaskEstimateRangeParams) => QueryValue[] }[] = [
  { sql: 'select id, title, estimate from tasks where tasks.project_id = ? and 1', bind: (params) => [params.projectId] },
  { sql: 'select id, title, estimate from tasks where tasks.project_id = ? and ( estimated_at between ? and ?)', bind: (params) => [params.projectId, params.range?.start ?? null, params.range?.end ?? null] },
];
function taskEstimateRangeSelect(raw: TaskEstimateRangeParams): { sql: string; bind: QueryValue[] } {
  const params = taskEstimateRangeValidate(raw);
  let mask = 0;
  if (params.range !== undefined) mask |= 1;
  const statement = taskEstimateRangeStatements[mask * 1 + 0];
  if (statement === undefined) throw new Error('invalid generated SYQL statement index');
  return { sql: statement.sql, bind: statement.bind(params) };
}

/** Run the 'taskEstimateRange' named query (SELECT-only). */
export async function taskEstimateRange(client: QueryClient, params: TaskEstimateRangeParams): Promise<TaskEstimateRangeRow[]> {
  const selected = taskEstimateRangeSelect(params);
  const rows = await client.query(selected.sql, selected.bind);
  return rows.map((row) => taskEstimateRangeMapRow(row as Readonly<Record<string, unknown>>));
}

/** Revisioned reactive descriptor for `useQuery(taskEstimateRangeQuery, params)`. */
export const taskEstimateRangeQuery: NamedQuery<TaskEstimateRangeRow, TaskEstimateRangeParams> = {
  id: 'sha256:9f91145d5e1d17303de133edc87b440f6ad59fe2a081c2303db1dd01db831ac4/taskEstimateRange',
  hasParams: true,
  sql: 'select id, title, estimate from tasks where tasks.project_id = ? and 1',
  mapRow: taskEstimateRangeMapRow,
  sqlFor: (params: TaskEstimateRangeParams) => taskEstimateRangeSelect(params).sql,
  tables: taskEstimateRangeTables,
  dependencies: (params) => [
    { table: 'tasks', scopeKeys: ['project:' + String(params.projectId) + ''] },
  ],
  coverage: () => [
  ],
  bind: (params: TaskEstimateRangeParams) => taskEstimateRangeSelect(params).bind,
  rowKey: (row) => [row.id],
};
