// Generated by @syncular/typegen — DO NOT EDIT.
// irVersion: 1
// irHash: sha256:c03629b4f51fc7970700f504f5022d6f9be57ae9f8247c73291fee100c36f19d
// ignore_for_file: type=lint

/// ServerSchema-compatible schema (SPEC §2.4, §3.1) —
/// pass to `SyncularClient.create(schema: …)`.
const Map<String, Object?> syncularSchema = <String, Object?>{
  'version': 3,
  'tables': [
    {
      'name': 'tasks',
      'primaryKey': 'id',
      'columns': [
        {'name': 'id', 'type': 'string', 'nullable': false},
        {'name': 'project_id', 'type': 'string', 'nullable': false},
        {'name': 'title', 'type': 'string', 'nullable': false},
        {'name': 'done', 'type': 'boolean', 'nullable': false},
        {'name': 'priority', 'type': 'integer', 'nullable': true},
        {'name': 'meta', 'type': 'json', 'nullable': true},
        {'name': 'estimate', 'type': 'float', 'nullable': true},
        {'name': 'estimated_at', 'type': 'integer', 'nullable': true},
      ],
      'scopes': [
        {'pattern': 'project:{project_id}', 'column': 'project_id'},
      ],
    },
    {
      'name': 'docs',
      'primaryKey': 'id',
      'columns': [
        {'name': 'id', 'type': 'string', 'nullable': false},
        {'name': 'org_id', 'type': 'string', 'nullable': false},
        {'name': 'project_id', 'type': 'string', 'nullable': false},
        {'name': 'body', 'type': 'string', 'nullable': false},
        {'name': 'score', 'type': 'float', 'nullable': true},
        {'name': 'attachment', 'type': 'bytes', 'nullable': true},
        {'name': 'body_doc', 'type': 'crdt', 'nullable': true, 'crdtType': 'yjs-doc'},
      ],
      'scopes': [
        {'pattern': 'org:{org_id}', 'column': 'org_id'},
        {'pattern': 'project:{projectId}', 'column': 'project_id'},
      ],
    },
  ],
};

/// Lift a SQLite boolean: a real bool, or 0/1 as a number.
bool? _rowBool(Object? value) {
  if (value is bool) return value;
  if (value is num) return value != 0;
  return null;
}

/// Decode the core's {'\$bytes': '<hex>'} marshaling (bytes as hex).
List<int>? _rowBytes(Object? value) {
  if (value is! Map) return null;
  final hex = value[r'$bytes'];
  if (hex is! String || hex.length % 2 != 0) return null;
  return [
    for (var i = 0; i < hex.length; i += 2)
      int.parse(hex.substring(i, i + 2), radix: 16),
  ];
}

/// One tasks row (§2.4 column order).
class Tasks {
  final String id;
  final String projectId;
  final String title;
  final bool done;
  final int? priority;
  final String? meta;
  final double? estimate;
  final int? estimatedAt;

  const Tasks({required this.id, required this.projectId, required this.title, required this.done, this.priority, this.meta, this.estimate, this.estimatedAt});

  /// Build from a `query`/`readRows` row. Returns null when a
  /// non-nullable column is missing or mistyped.
  static Tasks? fromRow(Map<String, Object?> row) {
    final id = row['id'] as String?;
    if (id == null) return null;
    final projectId = row['project_id'] as String?;
    if (projectId == null) return null;
    final title = row['title'] as String?;
    if (title == null) return null;
    final done = _rowBool(row['done']);
    if (done == null) return null;
    return Tasks(id: id, projectId: projectId, title: title, done: done, priority: (row['priority'] as num?)?.toInt(), meta: row['meta'] as String?, estimate: (row['estimate'] as num?)?.toDouble(), estimatedAt: (row['estimated_at'] as num?)?.toInt());
  }
}

/// One docs row (§2.4 column order).
class Docs {
  final String id;
  final String orgId;
  final String projectId;
  final String body;
  final double? score;
  final List<int>? attachment;
  final List<int>? bodyDoc;

  const Docs({required this.id, required this.orgId, required this.projectId, required this.body, this.score, this.attachment, this.bodyDoc});

  /// Build from a `query`/`readRows` row. Returns null when a
  /// non-nullable column is missing or mistyped.
  static Docs? fromRow(Map<String, Object?> row) {
    final id = row['id'] as String?;
    if (id == null) return null;
    final orgId = row['org_id'] as String?;
    if (orgId == null) return null;
    final projectId = row['project_id'] as String?;
    if (projectId == null) return null;
    final body = row['body'] as String?;
    if (body == null) return null;
    return Docs(id: id, orgId: orgId, projectId: projectId, body: body, score: (row['score'] as num?)?.toDouble(), attachment: _rowBytes(row['attachment']), bodyDoc: _rowBytes(row['body_doc']));
  }
}

/// Requested-scope template for the 'projectTasks' subscription.
class SyncularProjectTasksSubscription {
  static const String name = 'projectTasks';
  static const String table = 'tasks';
  static Map<String, List<String>> scopes({required String projectId}) => {
        'project_id': [projectId],
      };
}

/// Requested-scope template for the 'acmeDocs' subscription.
class SyncularAcmeDocsSubscription {
  static const String name = 'acmeDocs';
  static const String table = 'docs';
  static Map<String, List<String>> scopes({required String projectId}) => {
        'org_id': ['acme'],
        'projectId': [projectId],
      };
}
