// Generated by @syncular/typegen — DO NOT EDIT.
// irVersion: 1
// irHash: sha256:205eb84283bd6448618aa5a547c70d1c0779cd6d6db49ea1cc3da946c38dde92
// ignore_for_file: type=lint

import 'package:syncular/syncular.dart';

class SyqlQueryPresence<T> {
  final bool isPresent;
  final T? value;
  const SyqlQueryPresence.absent() : isPresent = false, value = null;
  const SyqlQueryPresence.present(this.value) : isPresent = true;
}

class SyqlQueryInputException implements Exception {
  final String code;
  final String message;
  const SyqlQueryInputException(this.code, this.message);
  @override
  String toString() => '$code: $message';
}

/// Lift a SQLite boolean: a real bool, or 0/1 as a number.
bool? _queryRowBool(Object? value) {
  if (value is bool) return value;
  if (value is num) return value != 0;
  return null;
}

/// Decode the core's {'\$bytes': '<hex>'} marshaling (bytes as hex).
List<int>? _queryRowBytes(Object? value) {
  if (value is! Map) return null;
  final hex = value[r'$bytes'];
  if (hex is! String || hex.length % 2 != 0) return null;
  return [
    for (var i = 0; i < hex.length; i += 2)
      int.parse(hex.substring(i, i + 2), radix: 16),
  ];
}

/// Encode bytes as the core's {'\$bytes': '<hex>'} marshaling for binding.
Map<String, Object?> _queryBindBytes(List<int> value) {
  final hex = value.map((b) => b.toRadixString(16).padLeft(2, '0')).join();
  return {r'$bytes': hex};
}

/// One row of the booleanResults query (its projection).
class BooleanResultsRow {
  final String id;
  final bool isDone;
  final bool? maybeDone;

  const BooleanResultsRow({required this.id, required this.isDone, this.maybeDone});

  static BooleanResultsRow? fromRow(Map<String, Object?> row) {
    final id = row['id'] as String?;
    if (id == null) return null;
    final isDone = _queryRowBool(row['isDone']);
    if (isDone == null) return null;
    return BooleanResultsRow(id: id, isDone: isDone, maybeDone: _queryRowBool(row['maybeDone']));
  }
}

/// One row of the findDocByOrg query (its projection).
class FindDocByOrgRow {
  final String id;
  final String body;

  const FindDocByOrgRow({required this.id, required this.body});

  static FindDocByOrgRow? fromRow(Map<String, Object?> row) {
    final id = row['id'] as String?;
    if (id == null) return null;
    final body = row['body'] as String?;
    if (body == null) return null;
    return FindDocByOrgRow(id: id, body: body);
  }
}

/// One row of the docValueTypes query (its projection).
class DocValueTypesRow {
  final String id;
  final List<int>? attachment;
  final List<int>? bodyDoc;
  final String? remoteBlob;

  const DocValueTypesRow({required this.id, this.attachment, this.bodyDoc, this.remoteBlob});

  static DocValueTypesRow? fromRow(Map<String, Object?> row) {
    final id = row['id'] as String?;
    if (id == null) return null;
    return DocValueTypesRow(id: id, attachment: _queryRowBytes(row['attachment']), bodyDoc: _queryRowBytes(row['bodyDoc']), remoteBlob: row['remoteBlob'] as String?);
  }
}

/// One row of the docWithBody query (its projection).
class DocWithBodyRow {
  final String docId;
  final String body;
  final String taskTitle;

  const DocWithBodyRow({required this.docId, required this.body, required this.taskTitle});

  static DocWithBodyRow? fromRow(Map<String, Object?> row) {
    final docId = row['docId'] as String?;
    if (docId == null) return null;
    final body = row['body'] as String?;
    if (body == null) return null;
    final taskTitle = row['taskTitle'] as String?;
    if (taskTitle == null) return null;
    return DocWithBodyRow(docId: docId, body: body, taskTitle: taskTitle);
  }
}

/// One row of the docsInProject query (its projection).
class DocsInProjectRow {
  final String id;
  final String body;

  const DocsInProjectRow({required this.id, required this.body});

  static DocsInProjectRow? fromRow(Map<String, Object?> row) {
    final id = row['id'] as String?;
    if (id == null) return null;
    final body = row['body'] as String?;
    if (body == null) return null;
    return DocsInProjectRow(id: id, body: body);
  }
}

/// One row of the hostBoolean query (its projection).
class HostBooleanRow {
  final String id;
  final bool done;

  const HostBooleanRow({required this.id, required this.done});

  static HostBooleanRow? fromRow(Map<String, Object?> row) {
    final id = row['id'] as String?;
    if (id == null) return null;
    final done = _queryRowBool(row['done']);
    if (done == null) return null;
    return HostBooleanRow(id: id, done: done);
  }
}

/// One row of the listProjectTasks query (its projection).
class ListProjectTasksRow {
  final String id;
  final String title;
  final bool done;
  final int? priority;
  final double? estimate;

  const ListProjectTasksRow({required this.id, required this.title, required this.done, this.priority, this.estimate});

  static ListProjectTasksRow? fromRow(Map<String, Object?> row) {
    final id = row['id'] as String?;
    if (id == null) return null;
    final title = row['title'] as String?;
    if (title == null) return null;
    final done = _queryRowBool(row['done']);
    if (done == null) return null;
    return ListProjectTasksRow(id: id, title: title, done: done, priority: (row['priority'] as num?)?.toInt(), estimate: (row['estimate'] as num?)?.toDouble());
  }
}

/// One row of the projectDocCount query (its projection).
class ProjectDocCountRow {
  final String projectId;
  final double? docCount;

  const ProjectDocCountRow({required this.projectId, this.docCount});

  static ProjectDocCountRow? fromRow(Map<String, Object?> row) {
    final projectId = row['projectId'] as String?;
    if (projectId == null) return null;
    return ProjectDocCountRow(projectId: projectId, docCount: (row['docCount'] as num?)?.toDouble());
  }
}

/// One row of the reportingTasksByPriority query (its projection).
class ReportingTasksByPriorityRow {
  final String id;
  final String title;
  final int? priority;

  const ReportingTasksByPriorityRow({required this.id, required this.title, this.priority});

  static ReportingTasksByPriorityRow? fromRow(Map<String, Object?> row) {
    final id = row['id'] as String?;
    if (id == null) return null;
    final title = row['title'] as String?;
    if (title == null) return null;
    return ReportingTasksByPriorityRow(id: id, title: title, priority: (row['priority'] as num?)?.toInt());
  }
}

/// One row of the reportOpenTasks query (its projection).
class ReportOpenTasksRow {
  final String id;
  final String title;
  final bool done;

  const ReportOpenTasksRow({required this.id, required this.title, required this.done});

  static ReportOpenTasksRow? fromRow(Map<String, Object?> row) {
    final id = row['id'] as String?;
    if (id == null) return null;
    final title = row['title'] as String?;
    if (title == null) return null;
    final done = _queryRowBool(row['done']);
    if (done == null) return null;
    return ReportOpenTasksRow(id: id, title: title, done: done);
  }
}

/// One row of the reportDocScores query (its projection).
class ReportDocScoresRow {
  final String id;
  final String orgId;
  final double? score;

  const ReportDocScoresRow({required this.id, required this.orgId, this.score});

  static ReportDocScoresRow? fromRow(Map<String, Object?> row) {
    final id = row['id'] as String?;
    if (id == null) return null;
    final orgId = row['orgId'] as String?;
    if (orgId == null) return null;
    return ReportDocScoresRow(id: id, orgId: orgId, score: (row['score'] as num?)?.toDouble());
  }
}

/// One row of the taskTitles query (its projection).
class TaskTitlesRow {
  final String id;
  final String title;

  const TaskTitlesRow({required this.id, required this.title});

  static TaskTitlesRow? fromRow(Map<String, Object?> row) {
    final id = row['id'] as String?;
    if (id == null) return null;
    final title = row['title'] as String?;
    if (title == null) return null;
    return TaskTitlesRow(id: id, title: title);
  }
}

/// One row of the taskValueTypes query (its projection).
class TaskValueTypesRow {
  final String id;
  final bool done;
  final int? priority;
  final double? estimate;
  final String? meta;

  const TaskValueTypesRow({required this.id, required this.done, this.priority, this.estimate, this.meta});

  static TaskValueTypesRow? fromRow(Map<String, Object?> row) {
    final id = row['id'] as String?;
    if (id == null) return null;
    final done = _queryRowBool(row['done']);
    if (done == null) return null;
    return TaskValueTypesRow(id: id, done: done, priority: (row['priority'] as num?)?.toInt(), estimate: (row['estimate'] as num?)?.toDouble(), meta: row['meta'] as String?);
  }
}

/// One row of the tasksInProjects query (its projection).
class TasksInProjectsRow {
  final String id;
  final String title;

  const TasksInProjectsRow({required this.id, required this.title});

  static TasksInProjectsRow? fromRow(Map<String, Object?> row) {
    final id = row['id'] as String?;
    if (id == null) return null;
    final title = row['title'] as String?;
    if (title == null) return null;
    return TasksInProjectsRow(id: id, title: title);
  }
}

/// One row of the tasksSince query (its projection).
class TasksSinceRow {
  final String id;
  final String title;

  const TasksSinceRow({required this.id, required this.title});

  static TasksSinceRow? fromRow(Map<String, Object?> row) {
    final id = row['id'] as String?;
    if (id == null) return null;
    final title = row['title'] as String?;
    if (title == null) return null;
    return TasksSinceRow(id: id, title: title);
  }
}

/// One row of the taskMetaFilter query (its projection).
class TaskMetaFilterRow {
  final String id;
  final String? meta;

  const TaskMetaFilterRow({required this.id, this.meta});

  static TaskMetaFilterRow? fromRow(Map<String, Object?> row) {
    final id = row['id'] as String?;
    if (id == null) return null;
    return TaskMetaFilterRow(id: id, meta: row['meta'] as String?);
  }
}

enum SearchTasksSortBy { priorityAsc, priorityDesc, estimatedAtAsc, estimatedAtDesc, titleAsc, titleDesc }

/// One row of the searchTasks query (its projection).
class SearchTasksRow {
  final String id;
  final String title;
  final bool done;
  final int? priority;
  final int? estimatedAt;

  const SearchTasksRow({required this.id, required this.title, required this.done, this.priority, this.estimatedAt});

  static SearchTasksRow? fromRow(Map<String, Object?> row) {
    final id = row['id'] as String?;
    if (id == null) return null;
    final title = row['title'] as String?;
    if (title == null) return null;
    final done = _queryRowBool(row['done']);
    if (done == null) return null;
    return SearchTasksRow(id: id, title: title, done: done, priority: (row['priority'] as num?)?.toInt(), estimatedAt: (row['estimatedAt'] as num?)?.toInt());
  }
}

class TaskEstimateRangeRange {
  final int start;
  final int end;
  const TaskEstimateRangeRange({required this.start, required this.end});
}

/// One row of the taskEstimateRange query (its projection).
class TaskEstimateRangeRow {
  final String id;
  final String title;
  final double? estimate;

  const TaskEstimateRangeRow({required this.id, required this.title, this.estimate});

  static TaskEstimateRangeRow? fromRow(Map<String, Object?> row) {
    final id = row['id'] as String?;
    if (id == null) return null;
    final title = row['title'] as String?;
    if (title == null) return null;
    return TaskEstimateRangeRow(id: id, title: title, estimate: (row['estimate'] as num?)?.toDouble());
  }
}

/// Tables the booleanResults query reads (exact invalidation set).
const List<String> syncularBooleanResultsQueryTables = ['docs', 'tasks'];

const String _booleanResultsSql = 'SELECT t.id, t.done AS isDone, t.reviewed AS maybeDone FROM tasks t JOIN docs d ON d.project_id = t.project_id ORDER BY t.id';

/// Run the booleanResults named query (SELECT-only).
List<BooleanResultsRow> syncularBooleanResultsQuery(SyncularClient client) {
  return client.query(_booleanResultsSql).map(BooleanResultsRow.fromRow).whereType<BooleanResultsRow>().toList();
}

/// Tables the findDocByOrg query reads (exact invalidation set).
const List<String> syncularFindDocByOrgQueryTables = ['docs'];

const String _findDocByOrgSql = 'SELECT id, body FROM docs WHERE org_id = ? ORDER BY id';

/// Run the findDocByOrg named query (SELECT-only).
List<FindDocByOrgRow> syncularFindDocByOrgQuery(SyncularClient client, {required String orgId}) {
  final params = <Object?>[orgId];
  return client.query(_findDocByOrgSql, params: params).map(FindDocByOrgRow.fromRow).whereType<FindDocByOrgRow>().toList();
}

/// Tables the docValueTypes query reads (exact invalidation set).
const List<String> syncularDocValueTypesQueryTables = ['docs'];

const String _docValueTypesSql = 'SELECT id, attachment, body_doc AS bodyDoc, remote_blob AS remoteBlob FROM docs WHERE id = ?';

/// Run the docValueTypes named query (SELECT-only).
List<DocValueTypesRow> syncularDocValueTypesQuery(SyncularClient client, {required String id}) {
  final params = <Object?>[id];
  return client.query(_docValueTypesSql, params: params).map(DocValueTypesRow.fromRow).whereType<DocValueTypesRow>().toList();
}

/// Tables the docWithBody query reads (exact invalidation set).
const List<String> syncularDocWithBodyQueryTables = ['docs', 'tasks'];

const String _docWithBodySql = 'SELECT d.id AS docId, d.body, t.title AS taskTitle FROM docs d JOIN tasks t ON t.project_id = d.project_id WHERE d.org_id = ?';

/// Run the docWithBody named query (SELECT-only).
List<DocWithBodyRow> syncularDocWithBodyQuery(SyncularClient client, {required String orgId}) {
  final params = <Object?>[orgId];
  return client.query(_docWithBodySql, params: params).map(DocWithBodyRow.fromRow).whereType<DocWithBodyRow>().toList();
}

/// Tables the docsInProject query reads (exact invalidation set).
const List<String> syncularDocsInProjectQueryTables = ['docs'];

const String _docsInProjectSql = 'SELECT id, body FROM docs WHERE org_id = ? AND project_id = ? ORDER BY id';

/// Run the docsInProject named query (SELECT-only).
List<DocsInProjectRow> syncularDocsInProjectQuery(SyncularClient client, {required String orgId, required String projectId}) {
  final params = <Object?>[orgId, projectId];
  return client.query(_docsInProjectSql, params: params).map(DocsInProjectRow.fromRow).whereType<DocsInProjectRow>().toList();
}

/// Tables the hostBoolean query reads (exact invalidation set).
const List<String> syncularHostBooleanQueryTables = ['tasks'];

const String _hostBooleanSql = 'SELECT id, done FROM tasks WHERE project_id = ? ORDER BY id';

/// Run the hostBoolean named query (SELECT-only).
List<HostBooleanRow> syncularHostBooleanQuery(SyncularClient client, {required String projectId}) {
  final params = <Object?>[projectId];
  return client.query(_hostBooleanSql, params: params).map(HostBooleanRow.fromRow).whereType<HostBooleanRow>().toList();
}

/// Tables the listProjectTasks query reads (exact invalidation set).
const List<String> syncularListProjectTasksQueryTables = ['tasks'];

const String _listProjectTasksSql = 'SELECT id, title, done, priority, estimate FROM tasks WHERE project_id = ? ORDER BY priority';

/// Run the listProjectTasks named query (SELECT-only).
List<ListProjectTasksRow> syncularListProjectTasksQuery(SyncularClient client, {required String projectId}) {
  final params = <Object?>[projectId];
  return client.query(_listProjectTasksSql, params: params).map(ListProjectTasksRow.fromRow).whereType<ListProjectTasksRow>().toList();
}

/// Tables the projectDocCount query reads (exact invalidation set).
const List<String> syncularProjectDocCountQueryTables = ['docs'];

const String _projectDocCountSql = 'SELECT project_id AS projectId, count(*) AS docCount FROM docs GROUP BY project_id';

/// Run the projectDocCount named query (SELECT-only).
List<ProjectDocCountRow> syncularProjectDocCountQuery(SyncularClient client) {
  return client.query(_projectDocCountSql).map(ProjectDocCountRow.fromRow).whereType<ProjectDocCountRow>().toList();
}

/// Tables the reportingTasksByPriority query reads (exact invalidation set).
const List<String> syncularReportingTasksByPriorityQueryTables = ['tasks'];

const String _reportingTasksByPrioritySql = 'SELECT id, title, priority FROM tasks WHERE priority = ? ORDER BY id';

/// Run the reportingTasksByPriority named query (SELECT-only).
List<ReportingTasksByPriorityRow> syncularReportingTasksByPriorityQuery(SyncularClient client, {required int priority}) {
  final params = <Object?>[priority];
  return client.query(_reportingTasksByPrioritySql, params: params).map(ReportingTasksByPriorityRow.fromRow).whereType<ReportingTasksByPriorityRow>().toList();
}

/// Tables the reportOpenTasks query reads (exact invalidation set).
const List<String> syncularReportOpenTasksQueryTables = ['tasks'];

const String _reportOpenTasksSql = 'SELECT id, title, done FROM tasks WHERE project_id = ? AND done = 0 ORDER BY id';

/// Run the reportOpenTasks named query (SELECT-only).
List<ReportOpenTasksRow> syncularReportOpenTasksQuery(SyncularClient client, {required String projectId}) {
  final params = <Object?>[projectId];
  return client.query(_reportOpenTasksSql, params: params).map(ReportOpenTasksRow.fromRow).whereType<ReportOpenTasksRow>().toList();
}

/// Tables the reportDocScores query reads (exact invalidation set).
const List<String> syncularReportDocScoresQueryTables = ['docs'];

const String _reportDocScoresSql = 'SELECT id, org_id AS orgId, score FROM docs WHERE score > ? * 1.0 ORDER BY id';

/// Run the reportDocScores named query (SELECT-only).
List<ReportDocScoresRow> syncularReportDocScoresQuery(SyncularClient client, {required double minScore}) {
  final params = <Object?>[minScore];
  return client.query(_reportDocScoresSql, params: params).map(ReportDocScoresRow.fromRow).whereType<ReportDocScoresRow>().toList();
}

/// Tables the taskTitles query reads (exact invalidation set).
const List<String> syncularTaskTitlesQueryTables = ['tasks'];

const String _taskTitlesSql = 'SELECT id, title FROM tasks';

/// Run the taskTitles named query (SELECT-only).
List<TaskTitlesRow> syncularTaskTitlesQuery(SyncularClient client) {
  return client.query(_taskTitlesSql).map(TaskTitlesRow.fromRow).whereType<TaskTitlesRow>().toList();
}

/// Tables the taskValueTypes query reads (exact invalidation set).
const List<String> syncularTaskValueTypesQueryTables = ['tasks'];

const String _taskValueTypesSql = 'SELECT id, done, priority, estimate, meta FROM tasks WHERE id = ?';

/// Run the taskValueTypes named query (SELECT-only).
List<TaskValueTypesRow> syncularTaskValueTypesQuery(SyncularClient client, {required String id}) {
  final params = <Object?>[id];
  return client.query(_taskValueTypesSql, params: params).map(TaskValueTypesRow.fromRow).whereType<TaskValueTypesRow>().toList();
}

/// Tables the tasksInProjects query reads (exact invalidation set).
const List<String> syncularTasksInProjectsQueryTables = ['tasks'];

const String _tasksInProjectsSql = 'SELECT id, title FROM tasks WHERE project_id IN (?, ?)';

/// Run the tasksInProjects named query (SELECT-only).
List<TasksInProjectsRow> syncularTasksInProjectsQuery(SyncularClient client, {required String first, required String second}) {
  final params = <Object?>[first, second];
  return client.query(_tasksInProjectsSql, params: params).map(TasksInProjectsRow.fromRow).whereType<TasksInProjectsRow>().toList();
}

/// Tables the tasksSince query reads (exact invalidation set).
const List<String> syncularTasksSinceQueryTables = ['tasks'];

const String _tasksSinceSql = 'SELECT id, title FROM tasks WHERE estimated_at > ? + 0';

/// Run the tasksSince named query (SELECT-only).
List<TasksSinceRow> syncularTasksSinceQuery(SyncularClient client, {required int sinceMs}) {
  final params = <Object?>[sinceMs];
  return client.query(_tasksSinceSql, params: params).map(TasksSinceRow.fromRow).whereType<TasksSinceRow>().toList();
}

/// Tables the taskMetaFilter query reads (exact invalidation set).
const List<String> syncularTaskMetaFilterQueryTables = ['tasks'];

/// Run the taskMetaFilter revision-1 SYQL query.
List<TaskMetaFilterRow> syncularTaskMetaFilterQuery(SyncularClient client, {required String projectId, SyqlQueryPresence<String?> meta = const SyqlQueryPresence.absent()}) {
  var activationMask = 0;
  if (meta.isPresent) activationMask |= 1;
  final statementIndex = activationMask * 1 + 0;
  late final String sql;
  late final List<Object?> params;
  switch (statementIndex) {
    case 0: sql = 'select id, meta from tasks where tasks.project_id = ? and 1 order by id'; params = <Object?>[projectId]; break;
    case 1: sql = 'select id, meta from tasks where tasks.project_id = ? and ( meta is ?) order by id'; params = <Object?>[projectId, meta.isPresent ? meta.value : null]; break;
    default: throw StateError('invalid generated SYQL statement index');
  }
  return client.query(sql, params: params).map(TaskMetaFilterRow.fromRow).whereType<TaskMetaFilterRow>().toList();
}

/// Tables the searchTasks query reads (exact invalidation set).
const List<String> syncularSearchTasksQueryTables = ['tasks'];

/// Run the searchTasks revision-1 SYQL query.
List<SearchTasksRow> syncularSearchTasksQuery(SyncularClient client, {required String projectId, String? needle, int? minPriority, bool openOnly = false, SearchTasksSortBy sortBy = SearchTasksSortBy.priorityDesc, int? pageSize}) {
  final effectivePageSize = pageSize ?? 50;
  if (effectivePageSize < 1 || effectivePageSize > 200) {
    throw SyqlQueryInputException('SYQL_RUNTIME_INVALID_LIMIT', 'searchTasks: invalid limit');
  }
  final statementIndex = sortBy.index;
  late final String sql;
  late final List<Object?> params;
  switch (statementIndex) {
    case 0: sql = 'select id, title, done, priority, estimated_at AS estimatedAt from tasks where tasks.project_id = ? and case when ? = 0 then 1 else ( ( title like \'%\' || ? || \'%\' )) end and case when ? = 0 then 1 else ( priority >= ?) end and case when ? = 0 then 1 else ( done = 0 ) end order by priority asc, id asc limit min(coalesce(?, 50), 200)'; params = <Object?>[projectId, needle != null, needle, minPriority != null, minPriority, openOnly, effectivePageSize]; break;
    case 1: sql = 'select id, title, done, priority, estimated_at AS estimatedAt from tasks where tasks.project_id = ? and case when ? = 0 then 1 else ( ( title like \'%\' || ? || \'%\' )) end and case when ? = 0 then 1 else ( priority >= ?) end and case when ? = 0 then 1 else ( done = 0 ) end order by priority desc, id desc limit min(coalesce(?, 50), 200)'; params = <Object?>[projectId, needle != null, needle, minPriority != null, minPriority, openOnly, effectivePageSize]; break;
    case 2: sql = 'select id, title, done, priority, estimated_at AS estimatedAt from tasks where tasks.project_id = ? and case when ? = 0 then 1 else ( ( title like \'%\' || ? || \'%\' )) end and case when ? = 0 then 1 else ( priority >= ?) end and case when ? = 0 then 1 else ( done = 0 ) end order by estimated_at asc, id asc limit min(coalesce(?, 50), 200)'; params = <Object?>[projectId, needle != null, needle, minPriority != null, minPriority, openOnly, effectivePageSize]; break;
    case 3: sql = 'select id, title, done, priority, estimated_at AS estimatedAt from tasks where tasks.project_id = ? and case when ? = 0 then 1 else ( ( title like \'%\' || ? || \'%\' )) end and case when ? = 0 then 1 else ( priority >= ?) end and case when ? = 0 then 1 else ( done = 0 ) end order by estimated_at desc, id desc limit min(coalesce(?, 50), 200)'; params = <Object?>[projectId, needle != null, needle, minPriority != null, minPriority, openOnly, effectivePageSize]; break;
    case 4: sql = 'select id, title, done, priority, estimated_at AS estimatedAt from tasks where tasks.project_id = ? and case when ? = 0 then 1 else ( ( title like \'%\' || ? || \'%\' )) end and case when ? = 0 then 1 else ( priority >= ?) end and case when ? = 0 then 1 else ( done = 0 ) end order by title asc, id asc limit min(coalesce(?, 50), 200)'; params = <Object?>[projectId, needle != null, needle, minPriority != null, minPriority, openOnly, effectivePageSize]; break;
    case 5: sql = 'select id, title, done, priority, estimated_at AS estimatedAt from tasks where tasks.project_id = ? and case when ? = 0 then 1 else ( ( title like \'%\' || ? || \'%\' )) end and case when ? = 0 then 1 else ( priority >= ?) end and case when ? = 0 then 1 else ( done = 0 ) end order by title desc, id desc limit min(coalesce(?, 50), 200)'; params = <Object?>[projectId, needle != null, needle, minPriority != null, minPriority, openOnly, effectivePageSize]; break;
    default: throw StateError('invalid generated SYQL statement index');
  }
  return client.query(sql, params: params).map(SearchTasksRow.fromRow).whereType<SearchTasksRow>().toList();
}

/// Tables the taskEstimateRange query reads (exact invalidation set).
const List<String> syncularTaskEstimateRangeQueryTables = ['tasks'];

/// Run the taskEstimateRange revision-1 SYQL query.
List<TaskEstimateRangeRow> syncularTaskEstimateRangeQuery(SyncularClient client, {required String projectId, TaskEstimateRangeRange? range}) {
  var activationMask = 0;
  if (range != null) activationMask |= 1;
  final statementIndex = activationMask * 1 + 0;
  late final String sql;
  late final List<Object?> params;
  switch (statementIndex) {
    case 0: sql = 'select id, title, estimate from tasks where tasks.project_id = ? and 1'; params = <Object?>[projectId]; break;
    case 1: sql = 'select id, title, estimate from tasks where tasks.project_id = ? and ( estimated_at between ? and ?)'; params = <Object?>[projectId, range == null ? null : range.start, range == null ? null : range.end]; break;
    default: throw StateError('invalid generated SYQL statement index');
  }
  return client.query(sql, params: params).map(TaskEstimateRangeRow.fromRow).whereType<TaskEstimateRangeRow>().toList();
}
