// Generated by @syncular-v2/typegen — DO NOT EDIT.
// irVersion: 1
// irHash: sha256:7206380358bb01c1ca51e8992be93a4fb77ef4cb05755016cb8e79aae08997e6

/** ServerSchema-compatible schema object (SPEC §2.4, §3.1). */
export const schema = {
  version: 3,
  tables: [
    {
      name: 'tasks',
      columns: [
        { name: 'id', type: 'string', nullable: false },
        { name: 'project_id', type: 'string', nullable: false },
        { name: 'title', type: 'string', nullable: false },
        { name: 'done', type: 'boolean', nullable: false },
        { name: 'priority', type: 'integer', nullable: true },
        { name: 'meta', type: 'json', nullable: true },
        { name: 'estimate', type: 'float', nullable: true },
        { name: 'estimated_at', type: 'integer', nullable: true },
      ],
      primaryKey: 'id',
      scopes: [
        { pattern: 'project:{project_id}', column: 'project_id' },
      ],
    },
    {
      name: 'docs',
      columns: [
        { name: 'id', type: 'string', nullable: false },
        { name: 'org_id', type: 'string', nullable: false },
        { name: 'project_id', type: 'string', nullable: false },
        { name: 'body', type: 'string', nullable: false },
        { name: 'score', type: 'float', nullable: true },
        { name: 'attachment', type: 'bytes', nullable: true },
        { name: 'body_doc', type: 'crdt', nullable: true, crdtType: 'yjs-doc' },
      ],
      primaryKey: 'id',
      scopes: [
        { pattern: 'org:{org_id}', column: 'org_id' },
        { pattern: 'project:{projectId}', column: 'project_id' },
      ],
    },
  ],
} as const;

/** One tasks row (§2.4 column order). */
export interface TasksRow {
  id: string;
  project_id: string;
  title: string;
  done: boolean;
  priority: number | null;
  meta: string | null;
  estimate: number | null;
  estimated_at: number | null;
}

/** Insert shape: nullable columns may be omitted. */
export interface TasksInsert {
  id: string;
  project_id: string;
  title: string;
  done: boolean;
  priority?: number | null;
  meta?: string | null;
  estimate?: number | null;
  estimated_at?: number | null;
}

/** Update shape: primary key required, all other columns optional. */
export interface TasksUpdate {
  id: string;
  project_id?: string;
  title?: string;
  done?: boolean;
  priority?: number | null;
  meta?: string | null;
  estimate?: number | null;
  estimated_at?: number | null;
}

/** One docs row (§2.4 column order). */
export interface DocsRow {
  id: string;
  org_id: string;
  project_id: string;
  body: string;
  score: number | null;
  attachment: Uint8Array | null;
  body_doc: Uint8Array | null;
}

/** Insert shape: nullable columns may be omitted. */
export interface DocsInsert {
  id: string;
  org_id: string;
  project_id: string;
  body: string;
  score?: number | null;
  attachment?: Uint8Array | null;
  body_doc?: Uint8Array | null;
}

/** Update shape: primary key required, all other columns optional. */
export interface DocsUpdate {
  id: string;
  org_id?: string;
  project_id?: string;
  body?: string;
  score?: number | null;
  attachment?: Uint8Array | null;
  body_doc?: Uint8Array | null;
}

/** Kysely `Database` interface (table → Row); the generic for
 *  @syncular-v2/kysely's SyncularDialect. */
export interface Database {
  tasks: TasksRow;
  docs: DocsRow;
}

export interface ProjectTasksParams {
  projectId: string;
}

/** Requested-scope template for the 'projectTasks' subscription. */
export const projectTasksSubscription = {
  name: 'projectTasks',
  table: 'tasks',
  scopes: (params: ProjectTasksParams): Record<string, string[]> => ({
    project_id: [params.projectId],
  }),
} as const;

export interface AcmeDocsParams {
  projectId: string;
}

/** Requested-scope template for the 'acmeDocs' subscription. */
export const acmeDocsSubscription = {
  name: 'acmeDocs',
  table: 'docs',
  scopes: (params: AcmeDocsParams): Record<string, string[]> => ({
    org_id: ['acme'],
    projectId: [params.projectId],
  }),
} as const;
