// Generated by @syncular/typegen — DO NOT EDIT.
// irVersion: 1
// irHash: sha256:8fbe6f1bd2db58913722dabf335b9bba5a3697296553714be02c6ccfda40f1fa

/** Structural descriptor consumed by renderer bindings; phantom type
 * fields make row/insert/update/id inference available without imports. */
export interface SyncTable<Row, Insert, Update, Id> {
  readonly name: string;
  /** Language-facing key used in generated row and mutation types. */
  readonly primaryKey: keyof Row & string;
  /** Physical SQLite/wire primary-key column. */
  readonly physicalPrimaryKey: string;
  readonly __row?: Row;
  readonly __insert?: Insert;
  readonly __update?: Update;
  readonly __id?: Id;
}

/** ServerSchema-compatible schema object (SPEC §2.4, §3.1). */
export const schema = {
  version: 4,
  tables: [
    {
      name: 'tasks',
      columns: [
        { name: 'id', type: 'string', nullable: false },
        { name: 'project_id', type: 'string', nullable: false },
        { name: 'title', type: 'string', nullable: false },
        { name: 'done', type: 'boolean', nullable: false },
        { name: 'reviewed', type: 'boolean', nullable: true },
        { name: 'priority', type: 'integer', nullable: true },
        { name: 'meta', type: 'json', nullable: true },
        { name: 'estimate', type: 'float', nullable: true },
        { name: 'estimated_at', type: 'integer', nullable: true },
      ],
      primaryKey: 'id',
      scopes: [
        { pattern: 'project:{project_id}', column: 'project_id' },
      ],
      indexes: [
        { name: 'idx_tasks_project', columns: ['project_id'], unique: false },
        { name: 'idx_tasks_project_title', columns: ['project_id', 'title'], unique: true },
      ],
    },
    {
      name: 'docs',
      columns: [
        { name: 'id', type: 'string', nullable: false },
        { name: 'org_id', type: 'string', nullable: false },
        { name: 'project_id', type: 'string', nullable: false },
        { name: 'body', type: 'string', nullable: false },
        { name: 'score', type: 'float', nullable: true },
        { name: 'attachment', type: 'bytes', nullable: true },
        { name: 'body_doc', type: 'crdt', nullable: true, crdtType: 'yjs-doc' },
        { name: 'remote_blob', type: 'blob_ref', nullable: true },
      ],
      primaryKey: 'id',
      scopes: [
        { pattern: 'org:{org_id}', column: 'org_id' },
        { pattern: 'project:{projectId}', column: 'project_id' },
      ],
    },
  ],
} as const;

/** One tasks row (§2.4 column order). */
export interface TasksRow {
  id: string;
  projectId: string;
  title: string;
  done: boolean;
  reviewed: boolean | null;
  priority: number | null;
  meta: string | null;
  estimate: number | null;
  estimatedAt: number | null;
}

/** Insert shape: nullable columns may be omitted. */
export interface TasksInsert {
  id: string;
  projectId: string;
  title: string;
  done: boolean;
  reviewed?: boolean | null;
  priority?: number | null;
  meta?: string | null;
  estimate?: number | null;
  estimatedAt?: number | null;
}

/** Update shape: primary key required, all other columns optional. */
export interface TasksUpdate {
  id: string;
  projectId?: string;
  title?: string;
  done?: boolean;
  reviewed?: boolean | null;
  priority?: number | null;
  meta?: string | null;
  estimate?: number | null;
  estimatedAt?: number | null;
}

/** Typed mutation/resource descriptor for 'tasks'. */
export const tasksTable: SyncTable<TasksRow, TasksInsert, TasksUpdate, string> = {
  name: 'tasks',
  primaryKey: 'id',
  physicalPrimaryKey: 'id',
};

/** One docs row (§2.4 column order). */
export interface DocsRow {
  id: string;
  orgId: string;
  projectId: string;
  body: string;
  score: number | null;
  attachment: Uint8Array | null;
  bodyDoc: Uint8Array | null;
  remoteBlob: string | null;
}

/** Insert shape: nullable columns may be omitted. */
export interface DocsInsert {
  id: string;
  orgId: string;
  projectId: string;
  body: string;
  score?: number | null;
  attachment?: Uint8Array | null;
  bodyDoc?: Uint8Array | null;
  remoteBlob?: string | null;
}

/** Update shape: primary key required, all other columns optional. */
export interface DocsUpdate {
  id: string;
  orgId?: string;
  projectId?: string;
  body?: string;
  score?: number | null;
  attachment?: Uint8Array | null;
  bodyDoc?: Uint8Array | null;
  remoteBlob?: string | null;
}

/** Typed mutation/resource descriptor for 'docs'. */
export const docsTable: SyncTable<DocsRow, DocsInsert, DocsUpdate, string> = {
  name: 'docs',
  primaryKey: 'id',
  physicalPrimaryKey: 'id',
};

export interface ProjectTasksParams {
  projectId: string;
}

/** Requested-scope template for the 'projectTasks' subscription. */
export const projectTasksSubscription = {
  name: 'projectTasks',
  table: 'tasks',
  scopes: (params: ProjectTasksParams): Record<string, string[]> => ({
    project_id: [params.projectId],
  }),
} as const;

export interface AcmeDocsParams {
  projectId: string;
}

/** Requested-scope template for the 'acmeDocs' subscription. */
export const acmeDocsSubscription = {
  name: 'acmeDocs',
  table: 'docs',
  scopes: (params: AcmeDocsParams): Record<string, string[]> => ({
    org_id: ['acme'],
    projectId: [params.projectId],
  }),
} as const;
