// Generated by @syncular/typegen — DO NOT EDIT.
// irVersion: 1
// irHash: sha256:c03629b4f51fc7970700f504f5022d6f9be57ae9f8247c73291fee100c36f19d

/** A bindable SQL param/row value (the wrapper's SqlValue subset). */
export type QueryValue =
  | string
  | number
  | bigint
  | boolean
  | Uint8Array
  | null;

/** Minimal structural client surface — the wrapper's positional
 *  `query(sql, params?)`. `SyncClient`/`SyncClientHandle`/`SyncClientLike`
 *  all satisfy it, so this module imports nothing. */
export interface QueryClient {
  query(
    sql: string,
    params?: readonly QueryValue[],
  ): unknown[] | Promise<unknown[]>;
}

/** A named-query descriptor — sql + its exact table dependency set + a
 *  `bind(params)` → positional args. Consumed by
 *  `@syncular/react`'s `useQuery`. `Row` is the projection row
 *  type; `Params` is `undefined` for a param-less query. `sqlFor`
 *  (present only with an orderBy knob) composes the statement from a
 *  generate-time-checked column allowlist. */
export interface NamedQuery<Row, Params = undefined> {
  readonly sql: string;
  readonly tables: readonly string[];
  readonly bind: (params: Params) => readonly QueryValue[];
  readonly sqlFor?: (params: Params) => string;
  /** Phantom — carries the Row type for `useQuery` inference. */
  readonly __row?: Row;
}

/** One row of the 'findDocByOrg' query (its projection). */
export interface FindDocByOrgRow {
  id: string;
  body: string;
}

/** Named parameters for 'findDocByOrg'. */
export interface FindDocByOrgParams {
  orgId: string;
}

/** Tables 'findDocByOrg' reads — the exact useRawSql `{tables}` set. */
export const findDocByOrgTables = ['docs'] as const;

const findDocByOrgSql = 'SELECT id, body FROM docs WHERE org_id = ? ORDER BY id';

/** Run the 'findDocByOrg' named query (SELECT-only). */
export async function findDocByOrg(client: QueryClient, params: FindDocByOrgParams): Promise<FindDocByOrgRow[]> {
  const rows = await client.query(findDocByOrgSql, [params.orgId]);
  return rows as unknown as FindDocByOrgRow[];
}

/** Descriptor for `useQuery(findDocByOrgQuery, params)` — sql + tables + row type. */
export const findDocByOrgQuery: NamedQuery<FindDocByOrgRow, FindDocByOrgParams> = {
  sql: findDocByOrgSql,
  tables: findDocByOrgTables,
  bind: (params: FindDocByOrgParams) => [params.orgId],
};

/** One row of the 'docWithBody' query (its projection). */
export interface DocWithBodyRow {
  docId: string;
  body: string;
  taskTitle: string;
}

/** Named parameters for 'docWithBody'. */
export interface DocWithBodyParams {
  orgId: string;
}

/** Tables 'docWithBody' reads — the exact useRawSql `{tables}` set. */
export const docWithBodyTables = ['docs', 'tasks'] as const;

const docWithBodySql = 'SELECT d.id AS docId, d.body, t.title AS taskTitle FROM docs d JOIN tasks t ON t.project_id = d.project_id WHERE d.org_id = ?';

/** Run the 'docWithBody' named query (SELECT-only). */
export async function docWithBody(client: QueryClient, params: DocWithBodyParams): Promise<DocWithBodyRow[]> {
  const rows = await client.query(docWithBodySql, [params.orgId]);
  return rows as unknown as DocWithBodyRow[];
}

/** Descriptor for `useQuery(docWithBodyQuery, params)` — sql + tables + row type. */
export const docWithBodyQuery: NamedQuery<DocWithBodyRow, DocWithBodyParams> = {
  sql: docWithBodySql,
  tables: docWithBodyTables,
  bind: (params: DocWithBodyParams) => [params.orgId],
};

/** One row of the 'listProjectTasks' query (its projection). */
export interface ListProjectTasksRow {
  id: string;
  title: string;
  done: boolean;
  priority: number | null;
  estimate: number | null;
}

/** Named parameters for 'listProjectTasks'. */
export interface ListProjectTasksParams {
  projectId: string;
}

/** Tables 'listProjectTasks' reads — the exact useRawSql `{tables}` set. */
export const listProjectTasksTables = ['tasks'] as const;

const listProjectTasksSql = 'SELECT id, title, done, priority, estimate FROM tasks WHERE project_id = ? ORDER BY priority';

/** Run the 'listProjectTasks' named query (SELECT-only). */
export async function listProjectTasks(client: QueryClient, params: ListProjectTasksParams): Promise<ListProjectTasksRow[]> {
  const rows = await client.query(listProjectTasksSql, [params.projectId]);
  return rows as unknown as ListProjectTasksRow[];
}

/** Descriptor for `useQuery(listProjectTasksQuery, params)` — sql + tables + row type. */
export const listProjectTasksQuery: NamedQuery<ListProjectTasksRow, ListProjectTasksParams> = {
  sql: listProjectTasksSql,
  tables: listProjectTasksTables,
  bind: (params: ListProjectTasksParams) => [params.projectId],
};

/** One row of the 'projectDocCount' query (its projection). */
export interface ProjectDocCountRow {
  projectId: string;
  docCount: number | null;
}

/** Tables 'projectDocCount' reads — the exact useRawSql `{tables}` set. */
export const projectDocCountTables = ['docs'] as const;

const projectDocCountSql = 'SELECT project_id AS projectId, count(*) AS docCount FROM docs GROUP BY project_id';

/** Run the 'projectDocCount' named query (SELECT-only). */
export async function projectDocCount(client: QueryClient): Promise<ProjectDocCountRow[]> {
  const rows = await client.query(projectDocCountSql);
  return rows as unknown as ProjectDocCountRow[];
}

/** Descriptor for `useQuery(projectDocCountQuery)` — sql + tables + row type. */
export const projectDocCountQuery: NamedQuery<ProjectDocCountRow, undefined> = {
  sql: projectDocCountSql,
  tables: projectDocCountTables,
  bind: () => [],
};

/** One row of the 'reportingTasksByPriority' query (its projection). */
export interface ReportingTasksByPriorityRow {
  id: string;
  title: string;
  priority: number | null;
}

/** Named parameters for 'reportingTasksByPriority'. */
export interface ReportingTasksByPriorityParams {
  priority: number;
}

/** Tables 'reportingTasksByPriority' reads — the exact useRawSql `{tables}` set. */
export const reportingTasksByPriorityTables = ['tasks'] as const;

const reportingTasksByPrioritySql = 'SELECT id, title, priority FROM tasks WHERE priority = ? ORDER BY id';

/** Run the 'reportingTasksByPriority' named query (SELECT-only). */
export async function reportingTasksByPriority(client: QueryClient, params: ReportingTasksByPriorityParams): Promise<ReportingTasksByPriorityRow[]> {
  const rows = await client.query(reportingTasksByPrioritySql, [params.priority]);
  return rows as unknown as ReportingTasksByPriorityRow[];
}

/** Descriptor for `useQuery(reportingTasksByPriorityQuery, params)` — sql + tables + row type. */
export const reportingTasksByPriorityQuery: NamedQuery<ReportingTasksByPriorityRow, ReportingTasksByPriorityParams> = {
  sql: reportingTasksByPrioritySql,
  tables: reportingTasksByPriorityTables,
  bind: (params: ReportingTasksByPriorityParams) => [params.priority],
};

/** One row of the 'reportOpenTasks' query (its projection). */
export interface ReportOpenTasksRow {
  id: string;
  title: string;
  done: boolean;
}

/** Named parameters for 'reportOpenTasks'. */
export interface ReportOpenTasksParams {
  projectId: string;
}

/** Tables 'reportOpenTasks' reads — the exact useRawSql `{tables}` set. */
export const reportOpenTasksTables = ['tasks'] as const;

const reportOpenTasksSql = 'SELECT id, title, done FROM tasks WHERE project_id = ? AND done = 0 ORDER BY id';

/** Run the 'reportOpenTasks' named query (SELECT-only). */
export async function reportOpenTasks(client: QueryClient, params: ReportOpenTasksParams): Promise<ReportOpenTasksRow[]> {
  const rows = await client.query(reportOpenTasksSql, [params.projectId]);
  return rows as unknown as ReportOpenTasksRow[];
}

/** Descriptor for `useQuery(reportOpenTasksQuery, params)` — sql + tables + row type. */
export const reportOpenTasksQuery: NamedQuery<ReportOpenTasksRow, ReportOpenTasksParams> = {
  sql: reportOpenTasksSql,
  tables: reportOpenTasksTables,
  bind: (params: ReportOpenTasksParams) => [params.projectId],
};

/** One row of the 'reportDocScores' query (its projection). */
export interface ReportDocScoresRow {
  id: string;
  orgId: string;
  score: number | null;
}

/** Named parameters for 'reportDocScores'. */
export interface ReportDocScoresParams {
  minScore: number;
}

/** Tables 'reportDocScores' reads — the exact useRawSql `{tables}` set. */
export const reportDocScoresTables = ['docs'] as const;

const reportDocScoresSql = 'SELECT id, org_id AS orgId, score FROM docs WHERE score > ? * 1.0 ORDER BY id';

/** Run the 'reportDocScores' named query (SELECT-only). */
export async function reportDocScores(client: QueryClient, params: ReportDocScoresParams): Promise<ReportDocScoresRow[]> {
  const rows = await client.query(reportDocScoresSql, [params.minScore]);
  return rows as unknown as ReportDocScoresRow[];
}

/** Descriptor for `useQuery(reportDocScoresQuery, params)` — sql + tables + row type. */
export const reportDocScoresQuery: NamedQuery<ReportDocScoresRow, ReportDocScoresParams> = {
  sql: reportDocScoresSql,
  tables: reportDocScoresTables,
  bind: (params: ReportDocScoresParams) => [params.minScore],
};

/** One row of the 'searchTasks' query (its projection). */
export interface SearchTasksRow {
  id: string;
  title: string;
  done: boolean;
  priority: number | null;
  estimatedAt: number | null;
}

/** Named parameters for 'searchTasks'. */
export interface SearchTasksParams {
  projectId: string;
  q?: string | null;
  minPriority?: number | null;
  openOnly?: boolean | null;
  /** §6 orderBy knob — a generate-time-checked allowlist. */
  orderBy?: 'priority' | 'estimatedAt' | 'title';
  dir?: 'asc' | 'desc';
  /** §6 limit knob — binds as a value (clamped to 200); default 50. */
  limit?: number;
}

/** Tables 'searchTasks' reads — the exact useRawSql `{tables}` set. */
export const searchTasksTables = ['tasks'] as const;

const searchTasksSql = 'select id, title, done, priority, estimated_at AS estimatedAt from tasks where (project_id = ?1) and (?2 is null or ((title like \'%\' || ?2 || \'%\'))) and (?3 is null or (priority >= ?3)) and (coalesce(?4, 0) = 0 or (done = 0)) order by priority desc limit min(coalesce(?5, 50), 200)';
const searchTasksSqlBase = 'select id, title, done, priority, estimated_at AS estimatedAt from tasks where (project_id = ?1) and (?2 is null or ((title like \'%\' || ?2 || \'%\'))) and (?3 is null or (priority >= ?3)) and (coalesce(?4, 0) = 0 or (done = 0))';
const searchTasksOrderColumns = { priority: 'priority', estimatedAt: 'estimated_at', title: 'title' } as const;
function searchTasksComposeSql(params?: SearchTasksParams): string {
  const column = searchTasksOrderColumns[params?.orderBy ?? 'priority'] ?? 'priority';
  const dir = (params?.dir ?? 'desc') === 'desc' ? 'desc' : 'asc';
  return `${searchTasksSqlBase} order by ${column} ${dir} limit min(coalesce(?5, 50), 200)`;
}

/** Run the 'searchTasks' named query (SELECT-only). */
export async function searchTasks(client: QueryClient, params: SearchTasksParams): Promise<SearchTasksRow[]> {
  const rows = await client.query(searchTasksComposeSql(params), [params.projectId, params.q ?? null, params.minPriority ?? null, params.openOnly ?? null, params.limit ?? null]);
  return rows as unknown as SearchTasksRow[];
}

/** Descriptor for `useQuery(searchTasksQuery, params)` — sql + tables + row type. */
export const searchTasksQuery: NamedQuery<SearchTasksRow, SearchTasksParams> = {
  sql: searchTasksSql,
  sqlFor: (params: SearchTasksParams) => searchTasksComposeSql(params),
  tables: searchTasksTables,
  bind: (params: SearchTasksParams) => [params.projectId, params.q ?? null, params.minPriority ?? null, params.openOnly ?? null, params.limit ?? null],
};

/** One row of the 'taskEstimateRange' query (its projection). */
export interface TaskEstimateRangeRow {
  id: string;
  title: string;
  estimate: number | null;
}

/** Named parameters for 'taskEstimateRange'. */
export interface TaskEstimateRangeParams {
  projectId: string;
  from?: number | null;
  to?: number | null;
}

/** Tables 'taskEstimateRange' reads — the exact useRawSql `{tables}` set. */
export const taskEstimateRangeTables = ['tasks'] as const;

const taskEstimateRangeSql = 'select id, title, estimate from tasks where (project_id = ?1) and (?2 is null or ?3 is null or (estimated_at between ?2 and ?3))';

/** Run the 'taskEstimateRange' named query (SELECT-only). */
export async function taskEstimateRange(client: QueryClient, params: TaskEstimateRangeParams): Promise<TaskEstimateRangeRow[]> {
  const rows = await client.query(taskEstimateRangeSql, [params.projectId, params.from ?? null, params.to ?? null]);
  return rows as unknown as TaskEstimateRangeRow[];
}

/** Descriptor for `useQuery(taskEstimateRangeQuery, params)` — sql + tables + row type. */
export const taskEstimateRangeQuery: NamedQuery<TaskEstimateRangeRow, TaskEstimateRangeParams> = {
  sql: taskEstimateRangeSql,
  tables: taskEstimateRangeTables,
  bind: (params: TaskEstimateRangeParams) => [params.projectId, params.from ?? null, params.to ?? null],
};

/** One row of the 'taskTitles' query (its projection). */
export interface TaskTitlesRow {
  id: string;
  title: string;
}

/** Tables 'taskTitles' reads — the exact useRawSql `{tables}` set. */
export const taskTitlesTables = ['tasks'] as const;

const taskTitlesSql = 'SELECT id, title FROM tasks';

/** Run the 'taskTitles' named query (SELECT-only). */
export async function taskTitles(client: QueryClient): Promise<TaskTitlesRow[]> {
  const rows = await client.query(taskTitlesSql);
  return rows as unknown as TaskTitlesRow[];
}

/** Descriptor for `useQuery(taskTitlesQuery)` — sql + tables + row type. */
export const taskTitlesQuery: NamedQuery<TaskTitlesRow, undefined> = {
  sql: taskTitlesSql,
  tables: taskTitlesTables,
  bind: () => [],
};

/** One row of the 'tasksInProjects' query (its projection). */
export interface TasksInProjectsRow {
  id: string;
  title: string;
}

/** Named parameters for 'tasksInProjects'. */
export interface TasksInProjectsParams {
  first: string;
  second: string;
}

/** Tables 'tasksInProjects' reads — the exact useRawSql `{tables}` set. */
export const tasksInProjectsTables = ['tasks'] as const;

const tasksInProjectsSql = 'SELECT id, title FROM tasks WHERE project_id IN (?, ?)';

/** Run the 'tasksInProjects' named query (SELECT-only). */
export async function tasksInProjects(client: QueryClient, params: TasksInProjectsParams): Promise<TasksInProjectsRow[]> {
  const rows = await client.query(tasksInProjectsSql, [params.first, params.second]);
  return rows as unknown as TasksInProjectsRow[];
}

/** Descriptor for `useQuery(tasksInProjectsQuery, params)` — sql + tables + row type. */
export const tasksInProjectsQuery: NamedQuery<TasksInProjectsRow, TasksInProjectsParams> = {
  sql: tasksInProjectsSql,
  tables: tasksInProjectsTables,
  bind: (params: TasksInProjectsParams) => [params.first, params.second],
};

/** One row of the 'tasksSince' query (its projection). */
export interface TasksSinceRow {
  id: string;
  title: string;
}

/** Named parameters for 'tasksSince'. */
export interface TasksSinceParams {
  sinceMs: number;
}

/** Tables 'tasksSince' reads — the exact useRawSql `{tables}` set. */
export const tasksSinceTables = ['tasks'] as const;

const tasksSinceSql = 'SELECT id, title FROM tasks WHERE estimated_at > ? + 0';

/** Run the 'tasksSince' named query (SELECT-only). */
export async function tasksSince(client: QueryClient, params: TasksSinceParams): Promise<TasksSinceRow[]> {
  const rows = await client.query(tasksSinceSql, [params.sinceMs]);
  return rows as unknown as TasksSinceRow[];
}

/** Descriptor for `useQuery(tasksSinceQuery, params)` — sql + tables + row type. */
export const tasksSinceQuery: NamedQuery<TasksSinceRow, TasksSinceParams> = {
  sql: tasksSinceSql,
  tables: tasksSinceTables,
  bind: (params: TasksSinceParams) => [params.sinceMs],
};
