// Generated by @syncular/typegen — DO NOT EDIT.
// irVersion: 1
// irHash: sha256:6e01ecdced6eba6808eb5dc2c70b8d8b1dcdf9ee22d49f49e03e0bd9ab6dab9e

export type SyqlRuntimeErrorCode =
  | 'SYQL_RUNTIME_MISSING_REQUIRED_INPUT'
  | 'SYQL_RUNTIME_UNKNOWN_INPUT'
  | 'SYQL_RUNTIME_INVALID_INPUT'
  | 'SYQL_RUNTIME_INVALID_GROUP'
  | 'SYQL_RUNTIME_INVALID_SORT'
  | 'SYQL_RUNTIME_INVALID_LIMIT';

export class SyqlInputError extends Error {
  readonly name = 'SyqlInputError';
  constructor(readonly code: SyqlRuntimeErrorCode, message: string) {
    super(message);
  }
}

export interface SyqlPresent<T> {
  readonly present: true;
  readonly value: T;
}

export function syqlPresent<T>(value: T): SyqlPresent<T> {
  return { present: true, value };
}

/** A bindable SQL param/row value (the wrapper's SqlValue subset). */
export type QueryValue =
  | string
  | number
  | bigint
  | boolean
  | Uint8Array
  | null;

/** Minimal structural client surface — the wrapper's positional
 *  `query(sql, params?)`. `SyncClient`/`SyncClientHandle`/`SyncClientLike`
 *  all satisfy it, so this module imports nothing. */
export interface QueryClient {
  query(
    sql: string,
    params?: readonly QueryValue[],
  ): unknown[] | Promise<unknown[]>;
}

/** A named-query descriptor — checked SQL plus revisioned reactive metadata and a
 *  `bind(params)` → positional args. Consumed by
 *  `@syncular/react`'s `useQuery`. `Row` is the projection row
 *  type; `Params` is `undefined` for a param-less query. `sqlFor`
 *  selects a checked revision-1 SYQL physical statement when needed. */
export interface NamedQuery<Row, Params = undefined> {
  readonly id: string;
  readonly hasParams: boolean;
  readonly sql: string;
  readonly tables: readonly string[];
  readonly bind: (params: Params) => readonly QueryValue[];
  readonly sqlFor?: (params: Params) => string;
  readonly dependencies: (params: Params) => readonly QueryDependency[];
  readonly coverage: (params: Params) => readonly WindowCoverage[];
  readonly rowKey?: (row: Row) => readonly QueryValue[];
  /** Phantom — carries the Row type for `useQuery` inference. */
  readonly __row?: Row;
}

export interface QueryDependency {
  readonly table: string;
  readonly scopeKeys?: readonly string[];
}

export interface WindowCoverage {
  readonly base: {
    readonly table: string;
    readonly variable: string;
    readonly fixedScopes?: Readonly<Record<string, readonly string[]>>;
    readonly params?: string;
  };
  readonly units: readonly string[];
}

/** One row of the 'findDocByOrg' query (its projection). */
export interface FindDocByOrgRow {
  id: string;
  body: string;
}

/** Named parameters for 'findDocByOrg'. */
export interface FindDocByOrgParams {
  orgId: string;
}

/** Tables 'findDocByOrg' reads (compatibility/export surface). */
export const findDocByOrgTables = ['docs'] as const;

const findDocByOrgSql = 'SELECT id, body FROM docs WHERE org_id = ? ORDER BY id';

/** Run the 'findDocByOrg' named query (SELECT-only). */
export async function findDocByOrg(client: QueryClient, params: FindDocByOrgParams): Promise<FindDocByOrgRow[]> {
  const rows = await client.query(findDocByOrgSql, [params.orgId]);
  return rows as unknown as FindDocByOrgRow[];
}

/** Revisioned reactive descriptor for `useQuery(findDocByOrgQuery, params)`. */
export const findDocByOrgQuery: NamedQuery<FindDocByOrgRow, FindDocByOrgParams> = {
  id: 'sha256:6e01ecdced6eba6808eb5dc2c70b8d8b1dcdf9ee22d49f49e03e0bd9ab6dab9e/findDocByOrg',
  hasParams: true,
  sql: findDocByOrgSql,
  tables: findDocByOrgTables,
  dependencies: (params) => [
    { table: 'docs', scopeKeys: ['org:' + String(params.orgId) + ''] },
  ],
  coverage: () => [
  ],
  bind: (params: FindDocByOrgParams) => [params.orgId],
  rowKey: (row) => [row.id],
};

/** One row of the 'docValueTypes' query (its projection). */
export interface DocValueTypesRow {
  id: string;
  attachment: Uint8Array | null;
  bodyDoc: Uint8Array | null;
  remoteBlob: string | null;
}

/** Named parameters for 'docValueTypes'. */
export interface DocValueTypesParams {
  id: string;
}

/** Tables 'docValueTypes' reads (compatibility/export surface). */
export const docValueTypesTables = ['docs'] as const;

const docValueTypesSql = 'SELECT id, attachment, body_doc AS bodyDoc, remote_blob AS remoteBlob FROM docs WHERE id = ?';

/** Run the 'docValueTypes' named query (SELECT-only). */
export async function docValueTypes(client: QueryClient, params: DocValueTypesParams): Promise<DocValueTypesRow[]> {
  const rows = await client.query(docValueTypesSql, [params.id]);
  return rows as unknown as DocValueTypesRow[];
}

/** Revisioned reactive descriptor for `useQuery(docValueTypesQuery, params)`. */
export const docValueTypesQuery: NamedQuery<DocValueTypesRow, DocValueTypesParams> = {
  id: 'sha256:6e01ecdced6eba6808eb5dc2c70b8d8b1dcdf9ee22d49f49e03e0bd9ab6dab9e/docValueTypes',
  hasParams: true,
  sql: docValueTypesSql,
  tables: docValueTypesTables,
  dependencies: () => [
    { table: 'docs' },
  ],
  coverage: () => [
  ],
  bind: (params: DocValueTypesParams) => [params.id],
  rowKey: (row) => [row.id],
};

/** One row of the 'docWithBody' query (its projection). */
export interface DocWithBodyRow {
  docId: string;
  body: string;
  taskTitle: string;
}

/** Named parameters for 'docWithBody'. */
export interface DocWithBodyParams {
  orgId: string;
}

/** Tables 'docWithBody' reads (compatibility/export surface). */
export const docWithBodyTables = ['docs', 'tasks'] as const;

const docWithBodySql = 'SELECT d.id AS docId, d.body, t.title AS taskTitle FROM docs d JOIN tasks t ON t.project_id = d.project_id WHERE d.org_id = ?';

/** Run the 'docWithBody' named query (SELECT-only). */
export async function docWithBody(client: QueryClient, params: DocWithBodyParams): Promise<DocWithBodyRow[]> {
  const rows = await client.query(docWithBodySql, [params.orgId]);
  return rows as unknown as DocWithBodyRow[];
}

/** Revisioned reactive descriptor for `useQuery(docWithBodyQuery, params)`. */
export const docWithBodyQuery: NamedQuery<DocWithBodyRow, DocWithBodyParams> = {
  id: 'sha256:6e01ecdced6eba6808eb5dc2c70b8d8b1dcdf9ee22d49f49e03e0bd9ab6dab9e/docWithBody',
  hasParams: true,
  sql: docWithBodySql,
  tables: docWithBodyTables,
  dependencies: (params) => [
    { table: 'docs', scopeKeys: ['org:' + String(params.orgId) + ''] },
    { table: 'tasks' },
  ],
  coverage: () => [
  ],
  bind: (params: DocWithBodyParams) => [params.orgId],
};

/** One row of the 'docsInProject' query (its projection). */
export interface DocsInProjectRow {
  id: string;
  body: string;
}

/** Named parameters for 'docsInProject'. */
export interface DocsInProjectParams {
  orgId: string;
  projectId: string;
}

/** Tables 'docsInProject' reads (compatibility/export surface). */
export const docsInProjectTables = ['docs'] as const;

const docsInProjectSql = 'SELECT id, body FROM docs WHERE org_id = ? AND project_id = ? ORDER BY id';

/** Run the 'docsInProject' named query (SELECT-only). */
export async function docsInProject(client: QueryClient, params: DocsInProjectParams): Promise<DocsInProjectRow[]> {
  const rows = await client.query(docsInProjectSql, [params.orgId, params.projectId]);
  return rows as unknown as DocsInProjectRow[];
}

/** Revisioned reactive descriptor for `useQuery(docsInProjectQuery, params)`. */
export const docsInProjectQuery: NamedQuery<DocsInProjectRow, DocsInProjectParams> = {
  id: 'sha256:6e01ecdced6eba6808eb5dc2c70b8d8b1dcdf9ee22d49f49e03e0bd9ab6dab9e/docsInProject',
  hasParams: true,
  sql: docsInProjectSql,
  tables: docsInProjectTables,
  dependencies: (params) => [
    { table: 'docs', scopeKeys: ['org:' + String(params.orgId) + '', 'project:' + String(params.projectId) + ''] },
  ],
  coverage: (params) => [
    { base: { table: 'docs', variable: 'org_id', fixedScopes: { projectId: [String(params.projectId)] } }, units: [String(params.orgId)] },
  ],
  bind: (params: DocsInProjectParams) => [params.orgId, params.projectId],
  rowKey: (row) => [row.id],
};

/** One row of the 'listProjectTasks' query (its projection). */
export interface ListProjectTasksRow {
  id: string;
  title: string;
  done: boolean;
  priority: number | null;
  estimate: number | null;
}

/** Named parameters for 'listProjectTasks'. */
export interface ListProjectTasksParams {
  projectId: string;
}

/** Tables 'listProjectTasks' reads (compatibility/export surface). */
export const listProjectTasksTables = ['tasks'] as const;

const listProjectTasksSql = 'SELECT id, title, done, priority, estimate FROM tasks WHERE project_id = ? ORDER BY priority';

/** Run the 'listProjectTasks' named query (SELECT-only). */
export async function listProjectTasks(client: QueryClient, params: ListProjectTasksParams): Promise<ListProjectTasksRow[]> {
  const rows = await client.query(listProjectTasksSql, [params.projectId]);
  return rows as unknown as ListProjectTasksRow[];
}

/** Revisioned reactive descriptor for `useQuery(listProjectTasksQuery, params)`. */
export const listProjectTasksQuery: NamedQuery<ListProjectTasksRow, ListProjectTasksParams> = {
  id: 'sha256:6e01ecdced6eba6808eb5dc2c70b8d8b1dcdf9ee22d49f49e03e0bd9ab6dab9e/listProjectTasks',
  hasParams: true,
  sql: listProjectTasksSql,
  tables: listProjectTasksTables,
  dependencies: (params) => [
    { table: 'tasks', scopeKeys: ['project:' + String(params.projectId) + ''] },
  ],
  coverage: (params) => [
    { base: { table: 'tasks', variable: 'project_id' }, units: [String(params.projectId)] },
  ],
  bind: (params: ListProjectTasksParams) => [params.projectId],
  rowKey: (row) => [row.id],
};

/** One row of the 'projectDocCount' query (its projection). */
export interface ProjectDocCountRow {
  projectId: string;
  docCount: number | null;
}

/** Tables 'projectDocCount' reads (compatibility/export surface). */
export const projectDocCountTables = ['docs'] as const;

const projectDocCountSql = 'SELECT project_id AS projectId, count(*) AS docCount FROM docs GROUP BY project_id';

/** Run the 'projectDocCount' named query (SELECT-only). */
export async function projectDocCount(client: QueryClient): Promise<ProjectDocCountRow[]> {
  const rows = await client.query(projectDocCountSql);
  return rows as unknown as ProjectDocCountRow[];
}

/** Revisioned reactive descriptor for `useQuery(projectDocCountQuery)`. */
export const projectDocCountQuery: NamedQuery<ProjectDocCountRow, undefined> = {
  id: 'sha256:6e01ecdced6eba6808eb5dc2c70b8d8b1dcdf9ee22d49f49e03e0bd9ab6dab9e/projectDocCount',
  hasParams: false,
  sql: projectDocCountSql,
  tables: projectDocCountTables,
  dependencies: () => [
    { table: 'docs' },
  ],
  coverage: () => [
  ],
  bind: () => [],
};

/** One row of the 'reportingTasksByPriority' query (its projection). */
export interface ReportingTasksByPriorityRow {
  id: string;
  title: string;
  priority: number | null;
}

/** Named parameters for 'reportingTasksByPriority'. */
export interface ReportingTasksByPriorityParams {
  priority: number;
}

/** Tables 'reportingTasksByPriority' reads (compatibility/export surface). */
export const reportingTasksByPriorityTables = ['tasks'] as const;

const reportingTasksByPrioritySql = 'SELECT id, title, priority FROM tasks WHERE priority = ? ORDER BY id';

/** Run the 'reportingTasksByPriority' named query (SELECT-only). */
export async function reportingTasksByPriority(client: QueryClient, params: ReportingTasksByPriorityParams): Promise<ReportingTasksByPriorityRow[]> {
  const rows = await client.query(reportingTasksByPrioritySql, [params.priority]);
  return rows as unknown as ReportingTasksByPriorityRow[];
}

/** Revisioned reactive descriptor for `useQuery(reportingTasksByPriorityQuery, params)`. */
export const reportingTasksByPriorityQuery: NamedQuery<ReportingTasksByPriorityRow, ReportingTasksByPriorityParams> = {
  id: 'sha256:6e01ecdced6eba6808eb5dc2c70b8d8b1dcdf9ee22d49f49e03e0bd9ab6dab9e/reportingTasksByPriority',
  hasParams: true,
  sql: reportingTasksByPrioritySql,
  tables: reportingTasksByPriorityTables,
  dependencies: () => [
    { table: 'tasks' },
  ],
  coverage: () => [
  ],
  bind: (params: ReportingTasksByPriorityParams) => [params.priority],
  rowKey: (row) => [row.id],
};

/** One row of the 'reportOpenTasks' query (its projection). */
export interface ReportOpenTasksRow {
  id: string;
  title: string;
  done: boolean;
}

/** Named parameters for 'reportOpenTasks'. */
export interface ReportOpenTasksParams {
  projectId: string;
}

/** Tables 'reportOpenTasks' reads (compatibility/export surface). */
export const reportOpenTasksTables = ['tasks'] as const;

const reportOpenTasksSql = 'SELECT id, title, done FROM tasks WHERE project_id = ? AND done = 0 ORDER BY id';

/** Run the 'reportOpenTasks' named query (SELECT-only). */
export async function reportOpenTasks(client: QueryClient, params: ReportOpenTasksParams): Promise<ReportOpenTasksRow[]> {
  const rows = await client.query(reportOpenTasksSql, [params.projectId]);
  return rows as unknown as ReportOpenTasksRow[];
}

/** Revisioned reactive descriptor for `useQuery(reportOpenTasksQuery, params)`. */
export const reportOpenTasksQuery: NamedQuery<ReportOpenTasksRow, ReportOpenTasksParams> = {
  id: 'sha256:6e01ecdced6eba6808eb5dc2c70b8d8b1dcdf9ee22d49f49e03e0bd9ab6dab9e/reportOpenTasks',
  hasParams: true,
  sql: reportOpenTasksSql,
  tables: reportOpenTasksTables,
  dependencies: (params) => [
    { table: 'tasks', scopeKeys: ['project:' + String(params.projectId) + ''] },
  ],
  coverage: (params) => [
    { base: { table: 'tasks', variable: 'project_id' }, units: [String(params.projectId)] },
  ],
  bind: (params: ReportOpenTasksParams) => [params.projectId],
  rowKey: (row) => [row.id],
};

/** One row of the 'reportDocScores' query (its projection). */
export interface ReportDocScoresRow {
  id: string;
  orgId: string;
  score: number | null;
}

/** Named parameters for 'reportDocScores'. */
export interface ReportDocScoresParams {
  minScore: number;
}

/** Tables 'reportDocScores' reads (compatibility/export surface). */
export const reportDocScoresTables = ['docs'] as const;

const reportDocScoresSql = 'SELECT id, org_id AS orgId, score FROM docs WHERE score > ? * 1.0 ORDER BY id';

/** Run the 'reportDocScores' named query (SELECT-only). */
export async function reportDocScores(client: QueryClient, params: ReportDocScoresParams): Promise<ReportDocScoresRow[]> {
  const rows = await client.query(reportDocScoresSql, [params.minScore]);
  return rows as unknown as ReportDocScoresRow[];
}

/** Revisioned reactive descriptor for `useQuery(reportDocScoresQuery, params)`. */
export const reportDocScoresQuery: NamedQuery<ReportDocScoresRow, ReportDocScoresParams> = {
  id: 'sha256:6e01ecdced6eba6808eb5dc2c70b8d8b1dcdf9ee22d49f49e03e0bd9ab6dab9e/reportDocScores',
  hasParams: true,
  sql: reportDocScoresSql,
  tables: reportDocScoresTables,
  dependencies: () => [
    { table: 'docs' },
  ],
  coverage: () => [
  ],
  bind: (params: ReportDocScoresParams) => [params.minScore],
  rowKey: (row) => [row.id],
};

/** One row of the 'taskTitles' query (its projection). */
export interface TaskTitlesRow {
  id: string;
  title: string;
}

/** Tables 'taskTitles' reads (compatibility/export surface). */
export const taskTitlesTables = ['tasks'] as const;

const taskTitlesSql = 'SELECT id, title FROM tasks';

/** Run the 'taskTitles' named query (SELECT-only). */
export async function taskTitles(client: QueryClient): Promise<TaskTitlesRow[]> {
  const rows = await client.query(taskTitlesSql);
  return rows as unknown as TaskTitlesRow[];
}

/** Revisioned reactive descriptor for `useQuery(taskTitlesQuery)`. */
export const taskTitlesQuery: NamedQuery<TaskTitlesRow, undefined> = {
  id: 'sha256:6e01ecdced6eba6808eb5dc2c70b8d8b1dcdf9ee22d49f49e03e0bd9ab6dab9e/taskTitles',
  hasParams: false,
  sql: taskTitlesSql,
  tables: taskTitlesTables,
  dependencies: () => [
    { table: 'tasks' },
  ],
  coverage: () => [
  ],
  bind: () => [],
  rowKey: (row) => [row.id],
};

/** One row of the 'taskValueTypes' query (its projection). */
export interface TaskValueTypesRow {
  id: string;
  done: boolean;
  priority: number | null;
  estimate: number | null;
  meta: string | null;
}

/** Named parameters for 'taskValueTypes'. */
export interface TaskValueTypesParams {
  id: string;
}

/** Tables 'taskValueTypes' reads (compatibility/export surface). */
export const taskValueTypesTables = ['tasks'] as const;

const taskValueTypesSql = 'SELECT id, done, priority, estimate, meta FROM tasks WHERE id = ?';

/** Run the 'taskValueTypes' named query (SELECT-only). */
export async function taskValueTypes(client: QueryClient, params: TaskValueTypesParams): Promise<TaskValueTypesRow[]> {
  const rows = await client.query(taskValueTypesSql, [params.id]);
  return rows as unknown as TaskValueTypesRow[];
}

/** Revisioned reactive descriptor for `useQuery(taskValueTypesQuery, params)`. */
export const taskValueTypesQuery: NamedQuery<TaskValueTypesRow, TaskValueTypesParams> = {
  id: 'sha256:6e01ecdced6eba6808eb5dc2c70b8d8b1dcdf9ee22d49f49e03e0bd9ab6dab9e/taskValueTypes',
  hasParams: true,
  sql: taskValueTypesSql,
  tables: taskValueTypesTables,
  dependencies: () => [
    { table: 'tasks' },
  ],
  coverage: () => [
  ],
  bind: (params: TaskValueTypesParams) => [params.id],
  rowKey: (row) => [row.id],
};

/** One row of the 'tasksInProjects' query (its projection). */
export interface TasksInProjectsRow {
  id: string;
  title: string;
}

/** Named parameters for 'tasksInProjects'. */
export interface TasksInProjectsParams {
  first: string;
  second: string;
}

/** Tables 'tasksInProjects' reads (compatibility/export surface). */
export const tasksInProjectsTables = ['tasks'] as const;

const tasksInProjectsSql = 'SELECT id, title FROM tasks WHERE project_id IN (?, ?)';

/** Run the 'tasksInProjects' named query (SELECT-only). */
export async function tasksInProjects(client: QueryClient, params: TasksInProjectsParams): Promise<TasksInProjectsRow[]> {
  const rows = await client.query(tasksInProjectsSql, [params.first, params.second]);
  return rows as unknown as TasksInProjectsRow[];
}

/** Revisioned reactive descriptor for `useQuery(tasksInProjectsQuery, params)`. */
export const tasksInProjectsQuery: NamedQuery<TasksInProjectsRow, TasksInProjectsParams> = {
  id: 'sha256:6e01ecdced6eba6808eb5dc2c70b8d8b1dcdf9ee22d49f49e03e0bd9ab6dab9e/tasksInProjects',
  hasParams: true,
  sql: tasksInProjectsSql,
  tables: tasksInProjectsTables,
  dependencies: (params) => [
    { table: 'tasks', scopeKeys: ['project:' + String(params.first) + '', 'project:' + String(params.second) + ''] },
  ],
  coverage: (params) => [
    { base: { table: 'tasks', variable: 'project_id' }, units: [String(params.first), String(params.second)] },
  ],
  bind: (params: TasksInProjectsParams) => [params.first, params.second],
  rowKey: (row) => [row.id],
};

/** One row of the 'tasksSince' query (its projection). */
export interface TasksSinceRow {
  id: string;
  title: string;
}

/** Named parameters for 'tasksSince'. */
export interface TasksSinceParams {
  sinceMs: number;
}

/** Tables 'tasksSince' reads (compatibility/export surface). */
export const tasksSinceTables = ['tasks'] as const;

const tasksSinceSql = 'SELECT id, title FROM tasks WHERE estimated_at > ? + 0';

/** Run the 'tasksSince' named query (SELECT-only). */
export async function tasksSince(client: QueryClient, params: TasksSinceParams): Promise<TasksSinceRow[]> {
  const rows = await client.query(tasksSinceSql, [params.sinceMs]);
  return rows as unknown as TasksSinceRow[];
}

/** Revisioned reactive descriptor for `useQuery(tasksSinceQuery, params)`. */
export const tasksSinceQuery: NamedQuery<TasksSinceRow, TasksSinceParams> = {
  id: 'sha256:6e01ecdced6eba6808eb5dc2c70b8d8b1dcdf9ee22d49f49e03e0bd9ab6dab9e/tasksSince',
  hasParams: true,
  sql: tasksSinceSql,
  tables: tasksSinceTables,
  dependencies: () => [
    { table: 'tasks' },
  ],
  coverage: () => [
  ],
  bind: (params: TasksSinceParams) => [params.sinceMs],
  rowKey: (row) => [row.id],
};

/** One row of the 'taskMetaFilter' query (its projection). */
export interface TaskMetaFilterRow {
  id: string;
  meta: string | null;
}

/** Public revision-1 SYQL inputs for 'taskMetaFilter'. */
export interface TaskMetaFilterParams {
  projectId: string;
  meta?: SyqlPresent<string | null>;
}

function taskMetaFilterValidate(raw?: TaskMetaFilterParams): TaskMetaFilterParams {
  const params = raw ?? ({} as TaskMetaFilterParams);
  const allowed = new Set(['projectId', 'meta']);
  for (const key of Object.keys(params)) {
    if (!allowed.has(key)) throw new SyqlInputError('SYQL_RUNTIME_UNKNOWN_INPUT', 'taskMetaFilter' + ': unknown input ' + key);
  }
  if (!Object.prototype.hasOwnProperty.call(params, 'projectId')) throw new SyqlInputError('SYQL_RUNTIME_MISSING_REQUIRED_INPUT', 'taskMetaFilter: missing required input projectId');
  if (!(typeof params.projectId === 'string')) throw new SyqlInputError('SYQL_RUNTIME_INVALID_INPUT', 'taskMetaFilter: invalid input projectId');
  if (params.meta !== undefined && (typeof params.meta !== 'object' || params.meta === null || params.meta.present !== true || !(params.meta.value === null || (typeof params.meta.value === 'string')))) throw new SyqlInputError('SYQL_RUNTIME_INVALID_INPUT', 'taskMetaFilter: invalid optional input meta');
  return params;
}

/** Tables 'taskMetaFilter' reads (compatibility/export surface). */
export const taskMetaFilterTables = ['tasks'] as const;

const taskMetaFilterStatements: { sql: string; bind: (params: TaskMetaFilterParams) => QueryValue[] }[] = [
  { sql: 'select id, meta from tasks where tasks.project_id = ? and 1 order by id', bind: (params) => [params.projectId] },
  { sql: 'select id, meta from tasks where tasks.project_id = ? and ( meta is ?) order by id', bind: (params) => [params.projectId, params.meta?.value ?? null] },
];
function taskMetaFilterSelect(raw: TaskMetaFilterParams): { sql: string; bind: QueryValue[] } {
  const params = taskMetaFilterValidate(raw);
  let mask = 0;
  if (params.meta !== undefined) mask |= 1;
  const statement = taskMetaFilterStatements[mask * 1 + 0];
  if (statement === undefined) throw new Error('invalid generated SYQL statement index');
  return { sql: statement.sql, bind: statement.bind(params) };
}

/** Run the 'taskMetaFilter' named query (SELECT-only). */
export async function taskMetaFilter(client: QueryClient, params: TaskMetaFilterParams): Promise<TaskMetaFilterRow[]> {
  const selected = taskMetaFilterSelect(params);
  const rows = await client.query(selected.sql, selected.bind);
  return rows as unknown as TaskMetaFilterRow[];
}

/** Revisioned reactive descriptor for `useQuery(taskMetaFilterQuery, params)`. */
export const taskMetaFilterQuery: NamedQuery<TaskMetaFilterRow, TaskMetaFilterParams> = {
  id: 'sha256:6e01ecdced6eba6808eb5dc2c70b8d8b1dcdf9ee22d49f49e03e0bd9ab6dab9e/taskMetaFilter',
  hasParams: true,
  sql: 'select id, meta from tasks where tasks.project_id = ? and 1 order by id',
  sqlFor: (params: TaskMetaFilterParams) => taskMetaFilterSelect(params).sql,
  tables: taskMetaFilterTables,
  dependencies: (params) => [
    { table: 'tasks', scopeKeys: ['project:' + String(params.projectId) + ''] },
  ],
  coverage: () => [
  ],
  bind: (params: TaskMetaFilterParams) => taskMetaFilterSelect(params).bind,
  rowKey: (row) => [row.id],
};

/** One row of the 'searchTasks' query (its projection). */
export interface SearchTasksRow {
  id: string;
  title: string;
  done: boolean;
  priority: number | null;
  estimatedAt: number | null;
}

/** Public revision-1 SYQL inputs for 'searchTasks'. */
export interface SearchTasksParams {
  projectId: string;
  needle?: string;
  minPriority?: bigint;
  openOnly?: boolean;
  sortBy?: 'priorityAsc' | 'priorityDesc' | 'estimatedAtAsc' | 'estimatedAtDesc' | 'titleAsc' | 'titleDesc';
  pageSize?: number;
}

function searchTasksValidate(raw?: SearchTasksParams): SearchTasksParams {
  const params = raw ?? ({} as SearchTasksParams);
  const allowed = new Set(['projectId', 'needle', 'minPriority', 'openOnly', 'sortBy', 'pageSize']);
  for (const key of Object.keys(params)) {
    if (!allowed.has(key)) throw new SyqlInputError('SYQL_RUNTIME_UNKNOWN_INPUT', 'searchTasks' + ': unknown input ' + key);
  }
  if (!Object.prototype.hasOwnProperty.call(params, 'projectId')) throw new SyqlInputError('SYQL_RUNTIME_MISSING_REQUIRED_INPUT', 'searchTasks: missing required input projectId');
  if (!(typeof params.projectId === 'string')) throw new SyqlInputError('SYQL_RUNTIME_INVALID_INPUT', 'searchTasks: invalid input projectId');
  if (params.needle !== undefined && !(typeof params.needle === 'string')) throw new SyqlInputError('SYQL_RUNTIME_INVALID_INPUT', 'searchTasks: invalid optional input needle');
  if (params.minPriority !== undefined && !(typeof params.minPriority === 'bigint')) throw new SyqlInputError('SYQL_RUNTIME_INVALID_INPUT', 'searchTasks: invalid optional input minPriority');
  if (params.openOnly !== undefined && !(typeof params.openOnly === 'boolean')) throw new SyqlInputError('SYQL_RUNTIME_INVALID_INPUT', 'searchTasks: invalid optional input openOnly');
  if (params.sortBy !== undefined && !['priorityAsc', 'priorityDesc', 'estimatedAtAsc', 'estimatedAtDesc', 'titleAsc', 'titleDesc'].includes(params.sortBy)) throw new SyqlInputError('SYQL_RUNTIME_INVALID_SORT', 'searchTasks: invalid sort profile');
  if (params.pageSize !== undefined && (!Number.isSafeInteger(params.pageSize) || params.pageSize < 1 || params.pageSize > 200)) throw new SyqlInputError('SYQL_RUNTIME_INVALID_LIMIT', 'searchTasks: limit must be an integer from 1 through 200');
  return params;
}

/** Tables 'searchTasks' reads (compatibility/export surface). */
export const searchTasksTables = ['tasks'] as const;

const searchTasksStatements: { sql: string; bind: (params: SearchTasksParams) => QueryValue[] }[] = [
  { sql: 'select id, title, done, priority, estimated_at AS estimatedAt from tasks where tasks.project_id = ? and case when ? = 0 then 1 else ( ( title like \'%\' || ? || \'%\' )) end and case when ? = 0 then 1 else ( priority >= ?) end and case when ? = 0 then 1 else ( done = 0 ) end order by priority asc, id asc limit min(coalesce(?, 50), 200)', bind: (params) => [params.projectId, params.needle !== undefined, params.needle ?? null, params.minPriority !== undefined, params.minPriority ?? null, params.openOnly === true, params.pageSize ?? 50] },
  { sql: 'select id, title, done, priority, estimated_at AS estimatedAt from tasks where tasks.project_id = ? and case when ? = 0 then 1 else ( ( title like \'%\' || ? || \'%\' )) end and case when ? = 0 then 1 else ( priority >= ?) end and case when ? = 0 then 1 else ( done = 0 ) end order by priority desc, id desc limit min(coalesce(?, 50), 200)', bind: (params) => [params.projectId, params.needle !== undefined, params.needle ?? null, params.minPriority !== undefined, params.minPriority ?? null, params.openOnly === true, params.pageSize ?? 50] },
  { sql: 'select id, title, done, priority, estimated_at AS estimatedAt from tasks where tasks.project_id = ? and case when ? = 0 then 1 else ( ( title like \'%\' || ? || \'%\' )) end and case when ? = 0 then 1 else ( priority >= ?) end and case when ? = 0 then 1 else ( done = 0 ) end order by estimated_at asc, id asc limit min(coalesce(?, 50), 200)', bind: (params) => [params.projectId, params.needle !== undefined, params.needle ?? null, params.minPriority !== undefined, params.minPriority ?? null, params.openOnly === true, params.pageSize ?? 50] },
  { sql: 'select id, title, done, priority, estimated_at AS estimatedAt from tasks where tasks.project_id = ? and case when ? = 0 then 1 else ( ( title like \'%\' || ? || \'%\' )) end and case when ? = 0 then 1 else ( priority >= ?) end and case when ? = 0 then 1 else ( done = 0 ) end order by estimated_at desc, id desc limit min(coalesce(?, 50), 200)', bind: (params) => [params.projectId, params.needle !== undefined, params.needle ?? null, params.minPriority !== undefined, params.minPriority ?? null, params.openOnly === true, params.pageSize ?? 50] },
  { sql: 'select id, title, done, priority, estimated_at AS estimatedAt from tasks where tasks.project_id = ? and case when ? = 0 then 1 else ( ( title like \'%\' || ? || \'%\' )) end and case when ? = 0 then 1 else ( priority >= ?) end and case when ? = 0 then 1 else ( done = 0 ) end order by title asc, id asc limit min(coalesce(?, 50), 200)', bind: (params) => [params.projectId, params.needle !== undefined, params.needle ?? null, params.minPriority !== undefined, params.minPriority ?? null, params.openOnly === true, params.pageSize ?? 50] },
  { sql: 'select id, title, done, priority, estimated_at AS estimatedAt from tasks where tasks.project_id = ? and case when ? = 0 then 1 else ( ( title like \'%\' || ? || \'%\' )) end and case when ? = 0 then 1 else ( priority >= ?) end and case when ? = 0 then 1 else ( done = 0 ) end order by title desc, id desc limit min(coalesce(?, 50), 200)', bind: (params) => [params.projectId, params.needle !== undefined, params.needle ?? null, params.minPriority !== undefined, params.minPriority ?? null, params.openOnly === true, params.pageSize ?? 50] },
];
const searchTasksSortIndexes = { priorityAsc: 0, priorityDesc: 1, estimatedAtAsc: 2, estimatedAtDesc: 3, titleAsc: 4, titleDesc: 5 } as const;
function searchTasksSelect(raw: SearchTasksParams): { sql: string; bind: QueryValue[] } {
  const params = searchTasksValidate(raw);
  const statement = searchTasksStatements[searchTasksSortIndexes[params.sortBy ?? 'priorityDesc']];
  if (statement === undefined) throw new Error('invalid generated SYQL statement index');
  return { sql: statement.sql, bind: statement.bind(params) };
}

/** Run the 'searchTasks' named query (SELECT-only). */
export async function searchTasks(client: QueryClient, params: SearchTasksParams): Promise<SearchTasksRow[]> {
  const selected = searchTasksSelect(params);
  const rows = await client.query(selected.sql, selected.bind);
  return rows as unknown as SearchTasksRow[];
}

/** Revisioned reactive descriptor for `useQuery(searchTasksQuery, params)`. */
export const searchTasksQuery: NamedQuery<SearchTasksRow, SearchTasksParams> = {
  id: 'sha256:6e01ecdced6eba6808eb5dc2c70b8d8b1dcdf9ee22d49f49e03e0bd9ab6dab9e/searchTasks',
  hasParams: true,
  sql: 'select id, title, done, priority, estimated_at AS estimatedAt from tasks where tasks.project_id = ? and case when ? = 0 then 1 else ( ( title like \'%\' || ? || \'%\' )) end and case when ? = 0 then 1 else ( priority >= ?) end and case when ? = 0 then 1 else ( done = 0 ) end order by priority desc, id desc limit min(coalesce(?, 50), 200)',
  sqlFor: (params: SearchTasksParams) => searchTasksSelect(params).sql,
  tables: searchTasksTables,
  dependencies: (params) => [
    { table: 'tasks', scopeKeys: ['project:' + String(params.projectId) + ''] },
  ],
  coverage: () => [
  ],
  bind: (params: SearchTasksParams) => searchTasksSelect(params).bind,
  rowKey: (row) => [row.id],
};

/** One row of the 'taskEstimateRange' query (its projection). */
export interface TaskEstimateRangeRow {
  id: string;
  title: string;
  estimate: number | null;
}

export interface TaskEstimateRangeRange {
  start: bigint;
  end: bigint;
}

/** Public revision-1 SYQL inputs for 'taskEstimateRange'. */
export interface TaskEstimateRangeParams {
  projectId: string;
  range?: TaskEstimateRangeRange;
}

function taskEstimateRangeValidate(raw?: TaskEstimateRangeParams): TaskEstimateRangeParams {
  const params = raw ?? ({} as TaskEstimateRangeParams);
  const allowed = new Set(['projectId', 'range']);
  for (const key of Object.keys(params)) {
    if (!allowed.has(key)) throw new SyqlInputError('SYQL_RUNTIME_UNKNOWN_INPUT', 'taskEstimateRange' + ': unknown input ' + key);
  }
  if (!Object.prototype.hasOwnProperty.call(params, 'projectId')) throw new SyqlInputError('SYQL_RUNTIME_MISSING_REQUIRED_INPUT', 'taskEstimateRange: missing required input projectId');
  if (!(typeof params.projectId === 'string')) throw new SyqlInputError('SYQL_RUNTIME_INVALID_INPUT', 'taskEstimateRange: invalid input projectId');
  if (params.range !== undefined) {
    if (typeof params.range !== 'object' || params.range === null) throw new SyqlInputError('SYQL_RUNTIME_INVALID_GROUP', 'taskEstimateRange: invalid group range');
    const allowedMembers = new Set(['start', 'end']);
    if (Object.keys(params.range).some((key) => !allowedMembers.has(key))) throw new SyqlInputError('SYQL_RUNTIME_INVALID_GROUP', 'taskEstimateRange: unknown member in group range');
    if (!Object.prototype.hasOwnProperty.call(params.range, 'start') || !(typeof params.range.start === 'bigint')) throw new SyqlInputError('SYQL_RUNTIME_INVALID_GROUP', 'taskEstimateRange: invalid or partial group range');
    if (!Object.prototype.hasOwnProperty.call(params.range, 'end') || !(typeof params.range.end === 'bigint')) throw new SyqlInputError('SYQL_RUNTIME_INVALID_GROUP', 'taskEstimateRange: invalid or partial group range');
  }
  return params;
}

/** Tables 'taskEstimateRange' reads (compatibility/export surface). */
export const taskEstimateRangeTables = ['tasks'] as const;

const taskEstimateRangeStatements: { sql: string; bind: (params: TaskEstimateRangeParams) => QueryValue[] }[] = [
  { sql: 'select id, title, estimate from tasks where tasks.project_id = ? and 1', bind: (params) => [params.projectId] },
  { sql: 'select id, title, estimate from tasks where tasks.project_id = ? and ( estimated_at between ? and ?)', bind: (params) => [params.projectId, params.range?.start ?? null, params.range?.end ?? null] },
];
function taskEstimateRangeSelect(raw: TaskEstimateRangeParams): { sql: string; bind: QueryValue[] } {
  const params = taskEstimateRangeValidate(raw);
  let mask = 0;
  if (params.range !== undefined) mask |= 1;
  const statement = taskEstimateRangeStatements[mask * 1 + 0];
  if (statement === undefined) throw new Error('invalid generated SYQL statement index');
  return { sql: statement.sql, bind: statement.bind(params) };
}

/** Run the 'taskEstimateRange' named query (SELECT-only). */
export async function taskEstimateRange(client: QueryClient, params: TaskEstimateRangeParams): Promise<TaskEstimateRangeRow[]> {
  const selected = taskEstimateRangeSelect(params);
  const rows = await client.query(selected.sql, selected.bind);
  return rows as unknown as TaskEstimateRangeRow[];
}

/** Revisioned reactive descriptor for `useQuery(taskEstimateRangeQuery, params)`. */
export const taskEstimateRangeQuery: NamedQuery<TaskEstimateRangeRow, TaskEstimateRangeParams> = {
  id: 'sha256:6e01ecdced6eba6808eb5dc2c70b8d8b1dcdf9ee22d49f49e03e0bd9ab6dab9e/taskEstimateRange',
  hasParams: true,
  sql: 'select id, title, estimate from tasks where tasks.project_id = ? and 1',
  sqlFor: (params: TaskEstimateRangeParams) => taskEstimateRangeSelect(params).sql,
  tables: taskEstimateRangeTables,
  dependencies: (params) => [
    { table: 'tasks', scopeKeys: ['project:' + String(params.projectId) + ''] },
  ],
  coverage: () => [
  ],
  bind: (params: TaskEstimateRangeParams) => taskEstimateRangeSelect(params).bind,
  rowKey: (row) => [row.id],
};
