// Generated by @syncular/typegen — DO NOT EDIT.
// irVersion: 1
// irHash: sha256:a09c319913c22e87bc613468e0eb13d7ff50279456c71b04d06362dd2e627e56

package dev.syncular.basic

import dev.syncular.JsonValue
import dev.syncular.SyncularClient

sealed class SyncularQueryPresence<out T> {
    object Absent : SyncularQueryPresence<Nothing>()
    data class Present<T>(val value: T) : SyncularQueryPresence<T>()
}

class SyncularQueryInputException(
    val code: String,
    override val message: String,
) : IllegalArgumentException(message)

private fun queryRowBool(value: JsonValue?): Boolean? {
    value?.bool?.let { return it }
    value?.number?.let { return it != 0.0 }
    return null
}

private fun queryRowBytes(value: JsonValue?): ByteArray? {
    val hex = value?.get("\$bytes")?.string ?: return null
    if (hex.length % 2 != 0) return null
    return ByteArray(hex.length / 2) { i ->
        hex.substring(i * 2, i * 2 + 2).toInt(16).toByte()
    }
}

private fun queryBindBytes(value: ByteArray): JsonValue {
    val hex = value.joinToString("") { "%02x".format(it) }
    return JsonValue.obj("\$bytes" to JsonValue.of(hex))
}

/** One row of the findDocByOrg query (its projection). */
data class FindDocByOrgRow(
    val id: String,
    val body: String,
) {
    companion object {
        fun fromRow(row: JsonValue): FindDocByOrgRow? {
            val id = row["id"]?.string ?: return null
            val body = row["body"]?.string ?: return null
            return FindDocByOrgRow(id, body)
        }
    }
}

/** One row of the docWithBody query (its projection). */
data class DocWithBodyRow(
    val docId: String,
    val body: String,
    val taskTitle: String,
) {
    companion object {
        fun fromRow(row: JsonValue): DocWithBodyRow? {
            val docId = row["docId"]?.string ?: return null
            val body = row["body"]?.string ?: return null
            val taskTitle = row["taskTitle"]?.string ?: return null
            return DocWithBodyRow(docId, body, taskTitle)
        }
    }
}

/** One row of the listProjectTasks query (its projection). */
data class ListProjectTasksRow(
    val id: String,
    val title: String,
    val done: Boolean,
    val priority: Long?,
    val estimate: Double?,
) {
    companion object {
        fun fromRow(row: JsonValue): ListProjectTasksRow? {
            val id = row["id"]?.string ?: return null
            val title = row["title"]?.string ?: return null
            val done = queryRowBool(row["done"]) ?: return null
            val priority = row["priority"]?.number?.toLong()
            val estimate = row["estimate"]?.number
            return ListProjectTasksRow(id, title, done, priority, estimate)
        }
    }
}

/** One row of the projectDocCount query (its projection). */
data class ProjectDocCountRow(
    val projectId: String,
    val docCount: Double?,
) {
    companion object {
        fun fromRow(row: JsonValue): ProjectDocCountRow? {
            val projectId = row["projectId"]?.string ?: return null
            val docCount = row["docCount"]?.number
            return ProjectDocCountRow(projectId, docCount)
        }
    }
}

/** One row of the reportingTasksByPriority query (its projection). */
data class ReportingTasksByPriorityRow(
    val id: String,
    val title: String,
    val priority: Long?,
) {
    companion object {
        fun fromRow(row: JsonValue): ReportingTasksByPriorityRow? {
            val id = row["id"]?.string ?: return null
            val title = row["title"]?.string ?: return null
            val priority = row["priority"]?.number?.toLong()
            return ReportingTasksByPriorityRow(id, title, priority)
        }
    }
}

/** One row of the reportOpenTasks query (its projection). */
data class ReportOpenTasksRow(
    val id: String,
    val title: String,
    val done: Boolean,
) {
    companion object {
        fun fromRow(row: JsonValue): ReportOpenTasksRow? {
            val id = row["id"]?.string ?: return null
            val title = row["title"]?.string ?: return null
            val done = queryRowBool(row["done"]) ?: return null
            return ReportOpenTasksRow(id, title, done)
        }
    }
}

/** One row of the reportDocScores query (its projection). */
data class ReportDocScoresRow(
    val id: String,
    val orgId: String,
    val score: Double?,
) {
    companion object {
        fun fromRow(row: JsonValue): ReportDocScoresRow? {
            val id = row["id"]?.string ?: return null
            val orgId = row["orgId"]?.string ?: return null
            val score = row["score"]?.number
            return ReportDocScoresRow(id, orgId, score)
        }
    }
}

/** One row of the taskTitles query (its projection). */
data class TaskTitlesRow(
    val id: String,
    val title: String,
) {
    companion object {
        fun fromRow(row: JsonValue): TaskTitlesRow? {
            val id = row["id"]?.string ?: return null
            val title = row["title"]?.string ?: return null
            return TaskTitlesRow(id, title)
        }
    }
}

/** One row of the tasksInProjects query (its projection). */
data class TasksInProjectsRow(
    val id: String,
    val title: String,
) {
    companion object {
        fun fromRow(row: JsonValue): TasksInProjectsRow? {
            val id = row["id"]?.string ?: return null
            val title = row["title"]?.string ?: return null
            return TasksInProjectsRow(id, title)
        }
    }
}

/** One row of the tasksSince query (its projection). */
data class TasksSinceRow(
    val id: String,
    val title: String,
) {
    companion object {
        fun fromRow(row: JsonValue): TasksSinceRow? {
            val id = row["id"]?.string ?: return null
            val title = row["title"]?.string ?: return null
            return TasksSinceRow(id, title)
        }
    }
}

enum class SearchTasksSortBy(val index: Int) {
    priorityAsc(0),
    priorityDesc(1),
    estimatedAtAsc(2),
    estimatedAtDesc(3),
    titleAsc(4),
    titleDesc(5);
}

/** One row of the searchTasks query (its projection). */
data class SearchTasksRow(
    val id: String,
    val title: String,
    val done: Boolean,
    val priority: Long?,
    val estimatedAt: Long?,
) {
    companion object {
        fun fromRow(row: JsonValue): SearchTasksRow? {
            val id = row["id"]?.string ?: return null
            val title = row["title"]?.string ?: return null
            val done = queryRowBool(row["done"]) ?: return null
            val priority = row["priority"]?.number?.toLong()
            val estimatedAt = row["estimatedAt"]?.number?.toLong()
            return SearchTasksRow(id, title, done, priority, estimatedAt)
        }
    }
}

data class TaskEstimateRangeRange(
    val start: Long,
    val end: Long,
)

/** One row of the taskEstimateRange query (its projection). */
data class TaskEstimateRangeRow(
    val id: String,
    val title: String,
    val estimate: Double?,
) {
    companion object {
        fun fromRow(row: JsonValue): TaskEstimateRangeRow? {
            val id = row["id"]?.string ?: return null
            val title = row["title"]?.string ?: return null
            val estimate = row["estimate"]?.number
            return TaskEstimateRangeRow(id, title, estimate)
        }
    }
}

/** Typed named queries (the sqlc/SQLDelight tier). */
object BasicSchemaQueries {
        val findDocByOrgTables = listOf("docs")
        private const val findDocByOrgSql = "SELECT id, body FROM docs WHERE org_id = ? ORDER BY id"

        /** Run the findDocByOrg named query (SELECT-only). */
        fun findDocByOrg(client: SyncularClient, orgId: String): List<FindDocByOrgRow> {
            val params = listOf(JsonValue.of(orgId))
            return client.query(findDocByOrgSql, params).mapNotNull { FindDocByOrgRow.fromRow(it) }
        }

        val docWithBodyTables = listOf("docs", "tasks")
        private const val docWithBodySql = "SELECT d.id AS docId, d.body, t.title AS taskTitle FROM docs d JOIN tasks t ON t.project_id = d.project_id WHERE d.org_id = ?"

        /** Run the docWithBody named query (SELECT-only). */
        fun docWithBody(client: SyncularClient, orgId: String): List<DocWithBodyRow> {
            val params = listOf(JsonValue.of(orgId))
            return client.query(docWithBodySql, params).mapNotNull { DocWithBodyRow.fromRow(it) }
        }

        val listProjectTasksTables = listOf("tasks")
        private const val listProjectTasksSql = "SELECT id, title, done, priority, estimate FROM tasks WHERE project_id = ? ORDER BY priority"

        /** Run the listProjectTasks named query (SELECT-only). */
        fun listProjectTasks(client: SyncularClient, projectId: String): List<ListProjectTasksRow> {
            val params = listOf(JsonValue.of(projectId))
            return client.query(listProjectTasksSql, params).mapNotNull { ListProjectTasksRow.fromRow(it) }
        }

        val projectDocCountTables = listOf("docs")
        private const val projectDocCountSql = "SELECT project_id AS projectId, count(*) AS docCount FROM docs GROUP BY project_id"

        /** Run the projectDocCount named query (SELECT-only). */
        fun projectDocCount(client: SyncularClient): List<ProjectDocCountRow> {
            return client.query(projectDocCountSql).mapNotNull { ProjectDocCountRow.fromRow(it) }
        }

        val reportingTasksByPriorityTables = listOf("tasks")
        private const val reportingTasksByPrioritySql = "SELECT id, title, priority FROM tasks WHERE priority = ? ORDER BY id"

        /** Run the reportingTasksByPriority named query (SELECT-only). */
        fun reportingTasksByPriority(client: SyncularClient, priority: Long): List<ReportingTasksByPriorityRow> {
            val params = listOf(JsonValue.of(priority.toDouble()))
            return client.query(reportingTasksByPrioritySql, params).mapNotNull { ReportingTasksByPriorityRow.fromRow(it) }
        }

        val reportOpenTasksTables = listOf("tasks")
        private const val reportOpenTasksSql = "SELECT id, title, done FROM tasks WHERE project_id = ? AND done = 0 ORDER BY id"

        /** Run the reportOpenTasks named query (SELECT-only). */
        fun reportOpenTasks(client: SyncularClient, projectId: String): List<ReportOpenTasksRow> {
            val params = listOf(JsonValue.of(projectId))
            return client.query(reportOpenTasksSql, params).mapNotNull { ReportOpenTasksRow.fromRow(it) }
        }

        val reportDocScoresTables = listOf("docs")
        private const val reportDocScoresSql = "SELECT id, org_id AS orgId, score FROM docs WHERE score > ? * 1.0 ORDER BY id"

        /** Run the reportDocScores named query (SELECT-only). */
        fun reportDocScores(client: SyncularClient, minScore: Double): List<ReportDocScoresRow> {
            val params = listOf(JsonValue.of(minScore))
            return client.query(reportDocScoresSql, params).mapNotNull { ReportDocScoresRow.fromRow(it) }
        }

        val taskTitlesTables = listOf("tasks")
        private const val taskTitlesSql = "SELECT id, title FROM tasks"

        /** Run the taskTitles named query (SELECT-only). */
        fun taskTitles(client: SyncularClient): List<TaskTitlesRow> {
            return client.query(taskTitlesSql).mapNotNull { TaskTitlesRow.fromRow(it) }
        }

        val tasksInProjectsTables = listOf("tasks")
        private const val tasksInProjectsSql = "SELECT id, title FROM tasks WHERE project_id IN (?, ?)"

        /** Run the tasksInProjects named query (SELECT-only). */
        fun tasksInProjects(client: SyncularClient, first: String, second: String): List<TasksInProjectsRow> {
            val params = listOf(JsonValue.of(first), JsonValue.of(second))
            return client.query(tasksInProjectsSql, params).mapNotNull { TasksInProjectsRow.fromRow(it) }
        }

        val tasksSinceTables = listOf("tasks")
        private const val tasksSinceSql = "SELECT id, title FROM tasks WHERE estimated_at > ? + 0"

        /** Run the tasksSince named query (SELECT-only). */
        fun tasksSince(client: SyncularClient, sinceMs: Long): List<TasksSinceRow> {
            val params = listOf(JsonValue.of(sinceMs.toDouble()))
            return client.query(tasksSinceSql, params).mapNotNull { TasksSinceRow.fromRow(it) }
        }

        val searchTasksTables = listOf("tasks")

        /** Run the searchTasks revision-1 SYQL query. */
        fun searchTasks(client: SyncularClient, projectId: String, needle: String? = null, minPriority: Long? = null, openOnly: Boolean = false, sortBy: SearchTasksSortBy = SearchTasksSortBy.priorityDesc, pageSize: Long? = null): List<SearchTasksRow> {
            val effectivePageSize = pageSize ?: 50L
            if (effectivePageSize < 1L || effectivePageSize > 200L) {
                throw SyncularQueryInputException("SYQL_RUNTIME_INVALID_PAGE", "searchTasks: invalid page size")
            }
            val statementIndex = sortBy.index
            val selected: Pair<String, List<JsonValue>> = when (statementIndex) {
                0 -> Pair("select id, title, done, priority, estimated_at AS estimatedAt from tasks where (tasks.project_id = ?) and case when ? = 0 then 1 else ( ( title like '%' || ? || '%' ) ) end and case when ? = 0 then 1 else ( priority >= ? ) end and case when ? = 0 then 1 else ( done = 0 ) end order by priority asc, id asc limit min(coalesce(?, 50), 200)", listOf(JsonValue.of(projectId), JsonValue.of(needle != null), needle?.let { JsonValue.of(it) } ?: JsonValue.Null, JsonValue.of(minPriority != null), minPriority?.let { JsonValue.of(it.toDouble()) } ?: JsonValue.Null, JsonValue.of(openOnly), JsonValue.of(effectivePageSize.toDouble())))
                1 -> Pair("select id, title, done, priority, estimated_at AS estimatedAt from tasks where (tasks.project_id = ?) and case when ? = 0 then 1 else ( ( title like '%' || ? || '%' ) ) end and case when ? = 0 then 1 else ( priority >= ? ) end and case when ? = 0 then 1 else ( done = 0 ) end order by priority desc, id desc limit min(coalesce(?, 50), 200)", listOf(JsonValue.of(projectId), JsonValue.of(needle != null), needle?.let { JsonValue.of(it) } ?: JsonValue.Null, JsonValue.of(minPriority != null), minPriority?.let { JsonValue.of(it.toDouble()) } ?: JsonValue.Null, JsonValue.of(openOnly), JsonValue.of(effectivePageSize.toDouble())))
                2 -> Pair("select id, title, done, priority, estimated_at AS estimatedAt from tasks where (tasks.project_id = ?) and case when ? = 0 then 1 else ( ( title like '%' || ? || '%' ) ) end and case when ? = 0 then 1 else ( priority >= ? ) end and case when ? = 0 then 1 else ( done = 0 ) end order by estimated_at asc, id asc limit min(coalesce(?, 50), 200)", listOf(JsonValue.of(projectId), JsonValue.of(needle != null), needle?.let { JsonValue.of(it) } ?: JsonValue.Null, JsonValue.of(minPriority != null), minPriority?.let { JsonValue.of(it.toDouble()) } ?: JsonValue.Null, JsonValue.of(openOnly), JsonValue.of(effectivePageSize.toDouble())))
                3 -> Pair("select id, title, done, priority, estimated_at AS estimatedAt from tasks where (tasks.project_id = ?) and case when ? = 0 then 1 else ( ( title like '%' || ? || '%' ) ) end and case when ? = 0 then 1 else ( priority >= ? ) end and case when ? = 0 then 1 else ( done = 0 ) end order by estimated_at desc, id desc limit min(coalesce(?, 50), 200)", listOf(JsonValue.of(projectId), JsonValue.of(needle != null), needle?.let { JsonValue.of(it) } ?: JsonValue.Null, JsonValue.of(minPriority != null), minPriority?.let { JsonValue.of(it.toDouble()) } ?: JsonValue.Null, JsonValue.of(openOnly), JsonValue.of(effectivePageSize.toDouble())))
                4 -> Pair("select id, title, done, priority, estimated_at AS estimatedAt from tasks where (tasks.project_id = ?) and case when ? = 0 then 1 else ( ( title like '%' || ? || '%' ) ) end and case when ? = 0 then 1 else ( priority >= ? ) end and case when ? = 0 then 1 else ( done = 0 ) end order by title asc, id asc limit min(coalesce(?, 50), 200)", listOf(JsonValue.of(projectId), JsonValue.of(needle != null), needle?.let { JsonValue.of(it) } ?: JsonValue.Null, JsonValue.of(minPriority != null), minPriority?.let { JsonValue.of(it.toDouble()) } ?: JsonValue.Null, JsonValue.of(openOnly), JsonValue.of(effectivePageSize.toDouble())))
                5 -> Pair("select id, title, done, priority, estimated_at AS estimatedAt from tasks where (tasks.project_id = ?) and case when ? = 0 then 1 else ( ( title like '%' || ? || '%' ) ) end and case when ? = 0 then 1 else ( priority >= ? ) end and case when ? = 0 then 1 else ( done = 0 ) end order by title desc, id desc limit min(coalesce(?, 50), 200)", listOf(JsonValue.of(projectId), JsonValue.of(needle != null), needle?.let { JsonValue.of(it) } ?: JsonValue.Null, JsonValue.of(minPriority != null), minPriority?.let { JsonValue.of(it.toDouble()) } ?: JsonValue.Null, JsonValue.of(openOnly), JsonValue.of(effectivePageSize.toDouble())))
                else -> error("invalid generated SYQL statement index")
            }
            return client.query(selected.first, selected.second).mapNotNull { SearchTasksRow.fromRow(it) }
        }

        val taskEstimateRangeTables = listOf("tasks")

        /** Run the taskEstimateRange revision-1 SYQL query. */
        fun taskEstimateRange(client: SyncularClient, projectId: String, range: TaskEstimateRangeRange? = null): List<TaskEstimateRangeRow> {
            var activationMask = 0
            if (range != null) activationMask = activationMask or 1
            val statementIndex = activationMask * 1 + 0
            val selected: Pair<String, List<JsonValue>> = when (statementIndex) {
                0 -> Pair("select id, title, estimate from tasks where (tasks.project_id = ?) and 1", listOf(JsonValue.of(projectId)))
                1 -> Pair("select id, title, estimate from tasks where (tasks.project_id = ?) and ( estimated_at between ? and ? )", listOf(JsonValue.of(projectId), range?.let { value -> JsonValue.of(value.start.toDouble()) } ?: JsonValue.Null, range?.let { value -> JsonValue.of(value.end.toDouble()) } ?: JsonValue.Null))
                else -> error("invalid generated SYQL statement index")
            }
            return client.query(selected.first, selected.second).mapNotNull { TaskEstimateRangeRow.fromRow(it) }
        }
}
