// Generated by @syncular/typegen — DO NOT EDIT.
// irVersion: 1
// irHash: sha256:a09c319913c22e87bc613468e0eb13d7ff50279456c71b04d06362dd2e627e56

import Foundation
import Syncular

public enum SyncularQueryPresence<Value: Sendable>: Sendable {
    case absent
    case present(Value)
}

public struct SyncularQueryInputError: Error, Sendable {
    public let code: String
    public let message: String
    public init(code: String, message: String) {
        self.code = code
        self.message = message
    }
}

/// Param-bind helpers shared by the generated query runners.
enum SyncularSchemaQueryBind {
    static func bytes(_ value: [UInt8]) -> JSONValue {
        let hex = value.map { String(format: "%02x", $0) }.joined()
        return .object(["$bytes": .string(hex)])
    }
}

/// One row of the findDocByOrg query (its projection).
public struct FindDocByOrgRow: Sendable, Equatable {
    public let id: String
    public let body: String

    public init?(row: [String: JSONValue]) {
        guard let id = row["id"]?.stringValue else { return nil }
        self.id = id
        guard let body = row["body"]?.stringValue else { return nil }
        self.body = body
    }
}

/// One row of the docWithBody query (its projection).
public struct DocWithBodyRow: Sendable, Equatable {
    public let docId: String
    public let body: String
    public let taskTitle: String

    public init?(row: [String: JSONValue]) {
        guard let docId = row["docId"]?.stringValue else { return nil }
        self.docId = docId
        guard let body = row["body"]?.stringValue else { return nil }
        self.body = body
        guard let taskTitle = row["taskTitle"]?.stringValue else { return nil }
        self.taskTitle = taskTitle
    }
}

/// One row of the listProjectTasks query (its projection).
public struct ListProjectTasksRow: Sendable, Equatable {
    public let id: String
    public let title: String
    public let done: Bool
    public let priority: Int?
    public let estimate: Double?

    public init?(row: [String: JSONValue]) {
        guard let id = row["id"]?.stringValue else { return nil }
        self.id = id
        guard let title = row["title"]?.stringValue else { return nil }
        self.title = title
        guard let done = SyncularSchemaRow.bool(row["done"]) else { return nil }
        self.done = done
        self.priority = row["priority"]?.numberValue.map(Int.init)
        self.estimate = row["estimate"]?.numberValue
    }
}

/// One row of the projectDocCount query (its projection).
public struct ProjectDocCountRow: Sendable, Equatable {
    public let projectId: String
    public let docCount: Double?

    public init?(row: [String: JSONValue]) {
        guard let projectId = row["projectId"]?.stringValue else { return nil }
        self.projectId = projectId
        self.docCount = row["docCount"]?.numberValue
    }
}

/// One row of the reportingTasksByPriority query (its projection).
public struct ReportingTasksByPriorityRow: Sendable, Equatable {
    public let id: String
    public let title: String
    public let priority: Int?

    public init?(row: [String: JSONValue]) {
        guard let id = row["id"]?.stringValue else { return nil }
        self.id = id
        guard let title = row["title"]?.stringValue else { return nil }
        self.title = title
        self.priority = row["priority"]?.numberValue.map(Int.init)
    }
}

/// One row of the reportOpenTasks query (its projection).
public struct ReportOpenTasksRow: Sendable, Equatable {
    public let id: String
    public let title: String
    public let done: Bool

    public init?(row: [String: JSONValue]) {
        guard let id = row["id"]?.stringValue else { return nil }
        self.id = id
        guard let title = row["title"]?.stringValue else { return nil }
        self.title = title
        guard let done = SyncularSchemaRow.bool(row["done"]) else { return nil }
        self.done = done
    }
}

/// One row of the reportDocScores query (its projection).
public struct ReportDocScoresRow: Sendable, Equatable {
    public let id: String
    public let orgId: String
    public let score: Double?

    public init?(row: [String: JSONValue]) {
        guard let id = row["id"]?.stringValue else { return nil }
        self.id = id
        guard let orgId = row["orgId"]?.stringValue else { return nil }
        self.orgId = orgId
        self.score = row["score"]?.numberValue
    }
}

/// One row of the taskTitles query (its projection).
public struct TaskTitlesRow: Sendable, Equatable {
    public let id: String
    public let title: String

    public init?(row: [String: JSONValue]) {
        guard let id = row["id"]?.stringValue else { return nil }
        self.id = id
        guard let title = row["title"]?.stringValue else { return nil }
        self.title = title
    }
}

/// One row of the tasksInProjects query (its projection).
public struct TasksInProjectsRow: Sendable, Equatable {
    public let id: String
    public let title: String

    public init?(row: [String: JSONValue]) {
        guard let id = row["id"]?.stringValue else { return nil }
        self.id = id
        guard let title = row["title"]?.stringValue else { return nil }
        self.title = title
    }
}

/// One row of the tasksSince query (its projection).
public struct TasksSinceRow: Sendable, Equatable {
    public let id: String
    public let title: String

    public init?(row: [String: JSONValue]) {
        guard let id = row["id"]?.stringValue else { return nil }
        self.id = id
        guard let title = row["title"]?.stringValue else { return nil }
        self.title = title
    }
}

public enum SearchTasksSortBy: Int, Sendable {
    case priorityAsc = 0
    case priorityDesc = 1
    case estimatedAtAsc = 2
    case estimatedAtDesc = 3
    case titleAsc = 4
    case titleDesc = 5
}

/// One row of the searchTasks query (its projection).
public struct SearchTasksRow: Sendable, Equatable {
    public let id: String
    public let title: String
    public let done: Bool
    public let priority: Int?
    public let estimatedAt: Int?

    public init?(row: [String: JSONValue]) {
        guard let id = row["id"]?.stringValue else { return nil }
        self.id = id
        guard let title = row["title"]?.stringValue else { return nil }
        self.title = title
        guard let done = SyncularSchemaRow.bool(row["done"]) else { return nil }
        self.done = done
        self.priority = row["priority"]?.numberValue.map(Int.init)
        self.estimatedAt = row["estimatedAt"]?.numberValue.map(Int.init)
    }
}

public struct TaskEstimateRangeRange: Sendable {
    public let start: Int64
    public let end: Int64
    public init(start: Int64, end: Int64) {
        self.start = start
        self.end = end
    }
}

/// One row of the taskEstimateRange query (its projection).
public struct TaskEstimateRangeRow: Sendable, Equatable {
    public let id: String
    public let title: String
    public let estimate: Double?

    public init?(row: [String: JSONValue]) {
        guard let id = row["id"]?.stringValue else { return nil }
        self.id = id
        guard let title = row["title"]?.stringValue else { return nil }
        self.title = title
        self.estimate = row["estimate"]?.numberValue
    }
}

/// Typed named queries (the sqlc/SQLDelight tier).
public enum BasicSchemaQueries {
    public static let findDocByOrgTables = ["docs"]
    private static let findDocByOrgSql = "SELECT id, body FROM docs WHERE org_id = ? ORDER BY id"

    /// Run the findDocByOrg named query (SELECT-only).
    public static func findDocByOrg(client: SyncularClient, orgId: String) throws -> [FindDocByOrgRow] {
        let params: [JSONValue] = [.string(orgId)]
        return try client.query(findDocByOrgSql, params: params).compactMap { row in
            guard case let .object(fields) = row else { return nil }
            return FindDocByOrgRow(row: fields)
        }
    }

    public static let docWithBodyTables = ["docs", "tasks"]
    private static let docWithBodySql = "SELECT d.id AS docId, d.body, t.title AS taskTitle FROM docs d JOIN tasks t ON t.project_id = d.project_id WHERE d.org_id = ?"

    /// Run the docWithBody named query (SELECT-only).
    public static func docWithBody(client: SyncularClient, orgId: String) throws -> [DocWithBodyRow] {
        let params: [JSONValue] = [.string(orgId)]
        return try client.query(docWithBodySql, params: params).compactMap { row in
            guard case let .object(fields) = row else { return nil }
            return DocWithBodyRow(row: fields)
        }
    }

    public static let listProjectTasksTables = ["tasks"]
    private static let listProjectTasksSql = "SELECT id, title, done, priority, estimate FROM tasks WHERE project_id = ? ORDER BY priority"

    /// Run the listProjectTasks named query (SELECT-only).
    public static func listProjectTasks(client: SyncularClient, projectId: String) throws -> [ListProjectTasksRow] {
        let params: [JSONValue] = [.string(projectId)]
        return try client.query(listProjectTasksSql, params: params).compactMap { row in
            guard case let .object(fields) = row else { return nil }
            return ListProjectTasksRow(row: fields)
        }
    }

    public static let projectDocCountTables = ["docs"]
    private static let projectDocCountSql = "SELECT project_id AS projectId, count(*) AS docCount FROM docs GROUP BY project_id"

    /// Run the projectDocCount named query (SELECT-only).
    public static func projectDocCount(client: SyncularClient) throws -> [ProjectDocCountRow] {
        return try client.query(projectDocCountSql).compactMap { row in
            guard case let .object(fields) = row else { return nil }
            return ProjectDocCountRow(row: fields)
        }
    }

    public static let reportingTasksByPriorityTables = ["tasks"]
    private static let reportingTasksByPrioritySql = "SELECT id, title, priority FROM tasks WHERE priority = ? ORDER BY id"

    /// Run the reportingTasksByPriority named query (SELECT-only).
    public static func reportingTasksByPriority(client: SyncularClient, priority: Int) throws -> [ReportingTasksByPriorityRow] {
        let params: [JSONValue] = [.number(Double(priority))]
        return try client.query(reportingTasksByPrioritySql, params: params).compactMap { row in
            guard case let .object(fields) = row else { return nil }
            return ReportingTasksByPriorityRow(row: fields)
        }
    }

    public static let reportOpenTasksTables = ["tasks"]
    private static let reportOpenTasksSql = "SELECT id, title, done FROM tasks WHERE project_id = ? AND done = 0 ORDER BY id"

    /// Run the reportOpenTasks named query (SELECT-only).
    public static func reportOpenTasks(client: SyncularClient, projectId: String) throws -> [ReportOpenTasksRow] {
        let params: [JSONValue] = [.string(projectId)]
        return try client.query(reportOpenTasksSql, params: params).compactMap { row in
            guard case let .object(fields) = row else { return nil }
            return ReportOpenTasksRow(row: fields)
        }
    }

    public static let reportDocScoresTables = ["docs"]
    private static let reportDocScoresSql = "SELECT id, org_id AS orgId, score FROM docs WHERE score > ? * 1.0 ORDER BY id"

    /// Run the reportDocScores named query (SELECT-only).
    public static func reportDocScores(client: SyncularClient, minScore: Double) throws -> [ReportDocScoresRow] {
        let params: [JSONValue] = [.number(Double(minScore))]
        return try client.query(reportDocScoresSql, params: params).compactMap { row in
            guard case let .object(fields) = row else { return nil }
            return ReportDocScoresRow(row: fields)
        }
    }

    public static let taskTitlesTables = ["tasks"]
    private static let taskTitlesSql = "SELECT id, title FROM tasks"

    /// Run the taskTitles named query (SELECT-only).
    public static func taskTitles(client: SyncularClient) throws -> [TaskTitlesRow] {
        return try client.query(taskTitlesSql).compactMap { row in
            guard case let .object(fields) = row else { return nil }
            return TaskTitlesRow(row: fields)
        }
    }

    public static let tasksInProjectsTables = ["tasks"]
    private static let tasksInProjectsSql = "SELECT id, title FROM tasks WHERE project_id IN (?, ?)"

    /// Run the tasksInProjects named query (SELECT-only).
    public static func tasksInProjects(client: SyncularClient, first: String, second: String) throws -> [TasksInProjectsRow] {
        let params: [JSONValue] = [.string(first), .string(second)]
        return try client.query(tasksInProjectsSql, params: params).compactMap { row in
            guard case let .object(fields) = row else { return nil }
            return TasksInProjectsRow(row: fields)
        }
    }

    public static let tasksSinceTables = ["tasks"]
    private static let tasksSinceSql = "SELECT id, title FROM tasks WHERE estimated_at > ? + 0"

    /// Run the tasksSince named query (SELECT-only).
    public static func tasksSince(client: SyncularClient, sinceMs: Int) throws -> [TasksSinceRow] {
        let params: [JSONValue] = [.number(Double(sinceMs))]
        return try client.query(tasksSinceSql, params: params).compactMap { row in
            guard case let .object(fields) = row else { return nil }
            return TasksSinceRow(row: fields)
        }
    }

    public static let searchTasksTables = ["tasks"]

    /// Run the searchTasks revision-1 SYQL query.
    public static func searchTasks(client: SyncularClient, projectId: String, needle: String? = nil, minPriority: Int64? = nil, openOnly: Bool = false, sortBy: SearchTasksSortBy = .priorityDesc, pageSize: Int? = nil) throws -> [SearchTasksRow] {
        let effectivePageSize = pageSize ?? 50
        guard effectivePageSize >= 1 && effectivePageSize <= 200 else {
            throw SyncularQueryInputError(code: "SYQL_RUNTIME_INVALID_PAGE", message: "searchTasks: invalid page size")
        }
        let statementIndex = sortBy.rawValue
        let selected: (String, [JSONValue])
        switch statementIndex {
        case 0: selected = ("select id, title, done, priority, estimated_at AS estimatedAt from tasks where (tasks.project_id = ?) and case when ? = 0 then 1 else ( ( title like '%' || ? || '%' ) ) end and case when ? = 0 then 1 else ( priority >= ? ) end and case when ? = 0 then 1 else ( done = 0 ) end order by priority asc, id asc limit min(coalesce(?, 50), 200)", [.string(projectId), .bool(needle != nil), needle.map { JSONValue.string($0) } ?? .null, .bool(minPriority != nil), minPriority.map { JSONValue.number(Double($0)) } ?? .null, .bool(openOnly), .number(Double(effectivePageSize))])
        case 1: selected = ("select id, title, done, priority, estimated_at AS estimatedAt from tasks where (tasks.project_id = ?) and case when ? = 0 then 1 else ( ( title like '%' || ? || '%' ) ) end and case when ? = 0 then 1 else ( priority >= ? ) end and case when ? = 0 then 1 else ( done = 0 ) end order by priority desc, id desc limit min(coalesce(?, 50), 200)", [.string(projectId), .bool(needle != nil), needle.map { JSONValue.string($0) } ?? .null, .bool(minPriority != nil), minPriority.map { JSONValue.number(Double($0)) } ?? .null, .bool(openOnly), .number(Double(effectivePageSize))])
        case 2: selected = ("select id, title, done, priority, estimated_at AS estimatedAt from tasks where (tasks.project_id = ?) and case when ? = 0 then 1 else ( ( title like '%' || ? || '%' ) ) end and case when ? = 0 then 1 else ( priority >= ? ) end and case when ? = 0 then 1 else ( done = 0 ) end order by estimated_at asc, id asc limit min(coalesce(?, 50), 200)", [.string(projectId), .bool(needle != nil), needle.map { JSONValue.string($0) } ?? .null, .bool(minPriority != nil), minPriority.map { JSONValue.number(Double($0)) } ?? .null, .bool(openOnly), .number(Double(effectivePageSize))])
        case 3: selected = ("select id, title, done, priority, estimated_at AS estimatedAt from tasks where (tasks.project_id = ?) and case when ? = 0 then 1 else ( ( title like '%' || ? || '%' ) ) end and case when ? = 0 then 1 else ( priority >= ? ) end and case when ? = 0 then 1 else ( done = 0 ) end order by estimated_at desc, id desc limit min(coalesce(?, 50), 200)", [.string(projectId), .bool(needle != nil), needle.map { JSONValue.string($0) } ?? .null, .bool(minPriority != nil), minPriority.map { JSONValue.number(Double($0)) } ?? .null, .bool(openOnly), .number(Double(effectivePageSize))])
        case 4: selected = ("select id, title, done, priority, estimated_at AS estimatedAt from tasks where (tasks.project_id = ?) and case when ? = 0 then 1 else ( ( title like '%' || ? || '%' ) ) end and case when ? = 0 then 1 else ( priority >= ? ) end and case when ? = 0 then 1 else ( done = 0 ) end order by title asc, id asc limit min(coalesce(?, 50), 200)", [.string(projectId), .bool(needle != nil), needle.map { JSONValue.string($0) } ?? .null, .bool(minPriority != nil), minPriority.map { JSONValue.number(Double($0)) } ?? .null, .bool(openOnly), .number(Double(effectivePageSize))])
        case 5: selected = ("select id, title, done, priority, estimated_at AS estimatedAt from tasks where (tasks.project_id = ?) and case when ? = 0 then 1 else ( ( title like '%' || ? || '%' ) ) end and case when ? = 0 then 1 else ( priority >= ? ) end and case when ? = 0 then 1 else ( done = 0 ) end order by title desc, id desc limit min(coalesce(?, 50), 200)", [.string(projectId), .bool(needle != nil), needle.map { JSONValue.string($0) } ?? .null, .bool(minPriority != nil), minPriority.map { JSONValue.number(Double($0)) } ?? .null, .bool(openOnly), .number(Double(effectivePageSize))])
        default: preconditionFailure("invalid generated SYQL statement index")
        }
        return try client.query(selected.0, params: selected.1).compactMap { row in
            guard case let .object(fields) = row else { return nil }
            return SearchTasksRow(row: fields)
        }
    }

    public static let taskEstimateRangeTables = ["tasks"]

    /// Run the taskEstimateRange revision-1 SYQL query.
    public static func taskEstimateRange(client: SyncularClient, projectId: String, range: TaskEstimateRangeRange? = nil) throws -> [TaskEstimateRangeRow] {
        var activationMask = 0
        if range != nil { activationMask |= 1 }
        let statementIndex = activationMask * 1 + 0
        let selected: (String, [JSONValue])
        switch statementIndex {
        case 0: selected = ("select id, title, estimate from tasks where (tasks.project_id = ?) and 1", [.string(projectId)])
        case 1: selected = ("select id, title, estimate from tasks where (tasks.project_id = ?) and ( estimated_at between ? and ? )", [.string(projectId), range.map { value in .number(Double(value.start)) } ?? .null, range.map { value in .number(Double(value.end)) } ?? .null])
        default: preconditionFailure("invalid generated SYQL statement index")
        }
        return try client.query(selected.0, params: selected.1).compactMap { row in
            guard case let .object(fields) = row else { return nil }
            return TaskEstimateRangeRow(row: fields)
        }
    }
}
