// Generated by @syncular-v2/typegen — DO NOT EDIT.
// irVersion: 1
// irHash: sha256:7206380358bb01c1ca51e8992be93a4fb77ef4cb05755016cb8e79aae08997e6

import Foundation
import Syncular

/// Param-bind helpers shared by the generated query runners.
enum SyncularSchemaQueryBind {
    static func bytes(_ value: [UInt8]) -> JSONValue {
        let hex = value.map { String(format: "%02x", $0) }.joined()
        return .object(["$bytes": .string(hex)])
    }
}

/// One row of the docWithBody query (its projection).
public struct DocWithBodyRow: Sendable, Equatable {
    public let docId: String
    public let body: String
    public let taskTitle: String

    public init?(row: [String: JSONValue]) {
        guard let docId = row["doc_id"]?.stringValue else { return nil }
        self.docId = docId
        guard let body = row["body"]?.stringValue else { return nil }
        self.body = body
        guard let taskTitle = row["task_title"]?.stringValue else { return nil }
        self.taskTitle = taskTitle
    }
}

/// One row of the listProjectTasks query (its projection).
public struct ListProjectTasksRow: Sendable, Equatable {
    public let id: String
    public let title: String
    public let done: Bool
    public let priority: Int?
    public let estimate: Double?

    public init?(row: [String: JSONValue]) {
        guard let id = row["id"]?.stringValue else { return nil }
        self.id = id
        guard let title = row["title"]?.stringValue else { return nil }
        self.title = title
        guard let done = SyncularSchemaRow.bool(row["done"]) else { return nil }
        self.done = done
        self.priority = row["priority"]?.numberValue.map(Int.init)
        self.estimate = row["estimate"]?.numberValue
    }
}

/// One row of the projectDocCount query (its projection).
public struct ProjectDocCountRow: Sendable, Equatable {
    public let projectId: String
    public let docCount: Double?

    public init?(row: [String: JSONValue]) {
        guard let projectId = row["project_id"]?.stringValue else { return nil }
        self.projectId = projectId
        self.docCount = row["doc_count"]?.numberValue
    }
}

/// One row of the taskTitles query (its projection).
public struct TaskTitlesRow: Sendable, Equatable {
    public let id: String
    public let title: String

    public init?(row: [String: JSONValue]) {
        guard let id = row["id"]?.stringValue else { return nil }
        self.id = id
        guard let title = row["title"]?.stringValue else { return nil }
        self.title = title
    }
}

/// One row of the tasksInProjects query (its projection).
public struct TasksInProjectsRow: Sendable, Equatable {
    public let id: String
    public let title: String

    public init?(row: [String: JSONValue]) {
        guard let id = row["id"]?.stringValue else { return nil }
        self.id = id
        guard let title = row["title"]?.stringValue else { return nil }
        self.title = title
    }
}

/// One row of the tasksSince query (its projection).
public struct TasksSinceRow: Sendable, Equatable {
    public let id: String
    public let title: String

    public init?(row: [String: JSONValue]) {
        guard let id = row["id"]?.stringValue else { return nil }
        self.id = id
        guard let title = row["title"]?.stringValue else { return nil }
        self.title = title
    }
}

/// Typed named queries (the sqlc/SQLDelight tier).
public enum BasicSchemaQueries {
    public static let docWithBodyTables = ["docs", "tasks"]
    private static let docWithBodySql = "SELECT d.id AS doc_id, d.body, t.title AS task_title FROM docs d JOIN tasks t ON t.project_id = d.project_id WHERE d.org_id = ?"

    /// Run the docWithBody named query (SELECT-only).
    public static func docWithBody(client: SyncularClient, orgId: String) throws -> [DocWithBodyRow] {
        let params: [JSONValue] = [.string(orgId)]
        return try client.query(docWithBodySql, params: params).compactMap { row in
            guard case let .object(fields) = row else { return nil }
            return DocWithBodyRow(row: fields)
        }
    }

    public static let listProjectTasksTables = ["tasks"]
    private static let listProjectTasksSql = "SELECT id, title, done, priority, estimate FROM tasks WHERE project_id = ? ORDER BY priority"

    /// Run the listProjectTasks named query (SELECT-only).
    public static func listProjectTasks(client: SyncularClient, projectId: String) throws -> [ListProjectTasksRow] {
        let params: [JSONValue] = [.string(projectId)]
        return try client.query(listProjectTasksSql, params: params).compactMap { row in
            guard case let .object(fields) = row else { return nil }
            return ListProjectTasksRow(row: fields)
        }
    }

    public static let projectDocCountTables = ["docs"]
    private static let projectDocCountSql = "SELECT project_id, count(*) AS doc_count FROM docs GROUP BY project_id"

    /// Run the projectDocCount named query (SELECT-only).
    public static func projectDocCount(client: SyncularClient) throws -> [ProjectDocCountRow] {
        return try client.query(projectDocCountSql).compactMap { row in
            guard case let .object(fields) = row else { return nil }
            return ProjectDocCountRow(row: fields)
        }
    }

    public static let taskTitlesTables = ["tasks"]
    private static let taskTitlesSql = "SELECT id, title FROM tasks"

    /// Run the taskTitles named query (SELECT-only).
    public static func taskTitles(client: SyncularClient) throws -> [TaskTitlesRow] {
        return try client.query(taskTitlesSql).compactMap { row in
            guard case let .object(fields) = row else { return nil }
            return TaskTitlesRow(row: fields)
        }
    }

    public static let tasksInProjectsTables = ["tasks"]
    private static let tasksInProjectsSql = "SELECT id, title FROM tasks WHERE project_id IN (?, ?)"

    /// Run the tasksInProjects named query (SELECT-only).
    public static func tasksInProjects(client: SyncularClient, first: String, second: String) throws -> [TasksInProjectsRow] {
        let params: [JSONValue] = [.string(first), .string(second)]
        return try client.query(tasksInProjectsSql, params: params).compactMap { row in
            guard case let .object(fields) = row else { return nil }
            return TasksInProjectsRow(row: fields)
        }
    }

    public static let tasksSinceTables = ["tasks"]
    private static let tasksSinceSql = "SELECT id, title FROM tasks WHERE estimated_at > ? + 0"

    /// Run the tasksSince named query (SELECT-only).
    public static func tasksSince(client: SyncularClient, sinceMs: Int) throws -> [TasksSinceRow] {
        let params: [JSONValue] = [.number(Double(sinceMs))]
        return try client.query(tasksSinceSql, params: params).compactMap { row in
            guard case let .object(fields) = row else { return nil }
            return TasksSinceRow(row: fields)
        }
    }
}
