// Generated by @syncular-v2/typegen — DO NOT EDIT.
// irVersion: 1
// irHash: sha256:7206380358bb01c1ca51e8992be93a4fb77ef4cb05755016cb8e79aae08997e6

import Foundation
import Syncular

/// The generated syncular schema (SPEC §2.4, §3.1) + typed rows.
public enum BasicSchema {
    /// ServerSchema-compatible schema — pass to `SyncularClient(schema:)`.
    public static let schema: JSONValue =
        .object([
          "version": .number(3),
          "tables": .array([
            .object([
              "name": .string("tasks"),
              "primaryKey": .string("id"),
              "columns": .array([
                .object(["name": .string("id"), "type": .string("string"), "nullable": .bool(false)]),
                .object(["name": .string("project_id"), "type": .string("string"), "nullable": .bool(false)]),
                .object(["name": .string("title"), "type": .string("string"), "nullable": .bool(false)]),
                .object(["name": .string("done"), "type": .string("boolean"), "nullable": .bool(false)]),
                .object(["name": .string("priority"), "type": .string("integer"), "nullable": .bool(true)]),
                .object(["name": .string("meta"), "type": .string("json"), "nullable": .bool(true)]),
                .object(["name": .string("estimate"), "type": .string("float"), "nullable": .bool(true)]),
                .object(["name": .string("estimated_at"), "type": .string("integer"), "nullable": .bool(true)]),
              ]),
              "scopes": .array([
                .object(["pattern": .string("project:{project_id}"), "column": .string("project_id")]),
              ]),
            ]),
            .object([
              "name": .string("docs"),
              "primaryKey": .string("id"),
              "columns": .array([
                .object(["name": .string("id"), "type": .string("string"), "nullable": .bool(false)]),
                .object(["name": .string("org_id"), "type": .string("string"), "nullable": .bool(false)]),
                .object(["name": .string("project_id"), "type": .string("string"), "nullable": .bool(false)]),
                .object(["name": .string("body"), "type": .string("string"), "nullable": .bool(false)]),
                .object(["name": .string("score"), "type": .string("float"), "nullable": .bool(true)]),
                .object(["name": .string("attachment"), "type": .string("bytes"), "nullable": .bool(true)]),
                .object(["name": .string("body_doc"), "type": .string("crdt"), "nullable": .bool(true), "crdtType": .string("yjs-doc")]),
              ]),
              "scopes": .array([
                .object(["pattern": .string("org:{org_id}"), "column": .string("org_id")]),
                .object(["pattern": .string("project:{projectId}"), "column": .string("project_id")]),
              ]),
            ]),
          ]),
        ])

    /// Typed requested-scope builders per subscription.
    public enum subscriptions {
        /// Requested-scope template for the "projectTasks" subscription.
        public enum ProjectTasks {
            public static let name = "projectTasks"
            public static let table = "tasks"
            public static func scopes(projectId: String) -> [String: [String]] {
                [
                    "project_id": [projectId],
                ]
            }
        }
        /// Requested-scope template for the "acmeDocs" subscription.
        public enum AcmeDocs {
            public static let name = "acmeDocs"
            public static let table = "docs"
            public static func scopes(projectId: String) -> [String: [String]] {
                [
                    "org_id": ["acme"],
                    "projectId": [projectId],
                ]
            }
        }
    }
}

/// Row-decode helpers shared by the generated structs.
enum SyncularSchemaRow {
    /// Lift a SQLite boolean: a real JSON bool, or 0/1 as a number.
    static func bool(_ value: JSONValue?) -> Bool? {
        if let b = value?.boolValue { return b }
        if let n = value?.numberValue { return n != 0 }
        return nil
    }

    /// Decode the core's `{"$bytes":"<hex>"}` marshaling into bytes.
    static func bytes(_ value: JSONValue?) -> [UInt8]? {
        guard let hex = value?["$bytes"]?.stringValue else { return nil }
        var out: [UInt8] = []
        out.reserveCapacity(hex.count / 2)
        var index = hex.startIndex
        while index < hex.endIndex {
            let next = hex.index(index, offsetBy: 2, limitedBy: hex.endIndex) ?? hex.endIndex
            guard let byte = UInt8(hex[index..<next], radix: 16) else { return nil }
            out.append(byte)
            index = next
        }
        return out
    }
}

/// One tasks row (§2.4 column order).
public struct Tasks: Sendable, Equatable {
    public let id: String
    public let projectId: String
    public let title: String
    public let done: Bool
    public let priority: Int?
    public let meta: String?
    public let estimate: Double?
    public let estimatedAt: Int?

    public init(id: String, projectId: String, title: String, done: Bool, priority: Int? = nil, meta: String? = nil, estimate: Double? = nil, estimatedAt: Int? = nil) {
        self.id = id
        self.projectId = projectId
        self.title = title
        self.done = done
        self.priority = priority
        self.meta = meta
        self.estimate = estimate
        self.estimatedAt = estimatedAt
    }

    /// Build from a `query`/`readRows` row (`[String: JSONValue]`).
    /// Returns nil when a non-nullable column is missing or mistyped.
    public init?(row: [String: JSONValue]) {
        guard let id = row["id"]?.stringValue else { return nil }
        self.id = id
        guard let projectId = row["project_id"]?.stringValue else { return nil }
        self.projectId = projectId
        guard let title = row["title"]?.stringValue else { return nil }
        self.title = title
        guard let done = SyncularSchemaRow.bool(row["done"]) else { return nil }
        self.done = done
        self.priority = row["priority"]?.numberValue.map(Int.init)
        self.meta = row["meta"]?.stringValue
        self.estimate = row["estimate"]?.numberValue
        self.estimatedAt = row["estimated_at"]?.numberValue.map(Int.init)
    }
}

/// One docs row (§2.4 column order).
public struct Docs: Sendable, Equatable {
    public let id: String
    public let orgId: String
    public let projectId: String
    public let body: String
    public let score: Double?
    public let attachment: [UInt8]?
    public let bodyDoc: [UInt8]?

    public init(id: String, orgId: String, projectId: String, body: String, score: Double? = nil, attachment: [UInt8]? = nil, bodyDoc: [UInt8]? = nil) {
        self.id = id
        self.orgId = orgId
        self.projectId = projectId
        self.body = body
        self.score = score
        self.attachment = attachment
        self.bodyDoc = bodyDoc
    }

    /// Build from a `query`/`readRows` row (`[String: JSONValue]`).
    /// Returns nil when a non-nullable column is missing or mistyped.
    public init?(row: [String: JSONValue]) {
        guard let id = row["id"]?.stringValue else { return nil }
        self.id = id
        guard let orgId = row["org_id"]?.stringValue else { return nil }
        self.orgId = orgId
        guard let projectId = row["project_id"]?.stringValue else { return nil }
        self.projectId = projectId
        guard let body = row["body"]?.stringValue else { return nil }
        self.body = body
        self.score = row["score"]?.numberValue
        self.attachment = SyncularSchemaRow.bytes(row["attachment"])
        self.bodyDoc = SyncularSchemaRow.bytes(row["body_doc"])
    }
}
