// Generated by @syncular-v2/typegen — DO NOT EDIT.
// irVersion: 1
// irHash: sha256:7206380358bb01c1ca51e8992be93a4fb77ef4cb05755016cb8e79aae08997e6

/** A bindable SQL param/row value (the wrapper's SqlValue subset). */
export type QueryValue =
  | string
  | number
  | bigint
  | boolean
  | Uint8Array
  | null;

/** Minimal structural client surface — the wrapper's positional
 *  `query(sql, params?)`. `SyncClient`/`SyncClientHandle`/`SyncClientLike`
 *  all satisfy it, so this module imports nothing. */
export interface QueryClient {
  query(
    sql: string,
    params?: readonly QueryValue[],
  ): unknown[] | Promise<unknown[]>;
}

/** A named-query descriptor — sql + its exact table dependency set + a
 *  `bind(params)` → positional args. Consumed by
 *  `@syncular-v2/react`'s `useNamedQuery`. `Row` is the projection row
 *  type; `Params` is `undefined` for a param-less query. */
export interface NamedQuery<Row, Params = undefined> {
  readonly sql: string;
  readonly tables: readonly string[];
  readonly bind: (params: Params) => readonly QueryValue[];
  /** Phantom — carries the Row type for `useNamedQuery` inference. */
  readonly __row?: Row;
}

/** One row of the 'docWithBody' query (its projection). */
export interface DocWithBodyRow {
  doc_id: string;
  body: string;
  task_title: string;
}

/** Named parameters for 'docWithBody'. */
export interface DocWithBodyParams {
  orgId: string;
}

/** Tables 'docWithBody' reads — the exact useSyncQuery `{tables}` set. */
export const docWithBodyTables = ['docs', 'tasks'] as const;

const docWithBodySql = 'SELECT d.id AS doc_id, d.body, t.title AS task_title FROM docs d JOIN tasks t ON t.project_id = d.project_id WHERE d.org_id = ?';

/** Run the 'docWithBody' named query (SELECT-only). */
export async function docWithBody(client: QueryClient, params: DocWithBodyParams): Promise<DocWithBodyRow[]> {
  const rows = await client.query(docWithBodySql, [params.orgId]);
  return rows as unknown as DocWithBodyRow[];
}

/** Descriptor for `useNamedQuery(docWithBodyQuery, params)` — sql + tables + row type. */
export const docWithBodyQuery: NamedQuery<DocWithBodyRow, DocWithBodyParams> = {
  sql: docWithBodySql,
  tables: docWithBodyTables,
  bind: (params: DocWithBodyParams) => [params.orgId],
};

/** One row of the 'listProjectTasks' query (its projection). */
export interface ListProjectTasksRow {
  id: string;
  title: string;
  done: boolean;
  priority: number | null;
  estimate: number | null;
}

/** Named parameters for 'listProjectTasks'. */
export interface ListProjectTasksParams {
  projectId: string;
}

/** Tables 'listProjectTasks' reads — the exact useSyncQuery `{tables}` set. */
export const listProjectTasksTables = ['tasks'] as const;

const listProjectTasksSql = 'SELECT id, title, done, priority, estimate FROM tasks WHERE project_id = ? ORDER BY priority';

/** Run the 'listProjectTasks' named query (SELECT-only). */
export async function listProjectTasks(client: QueryClient, params: ListProjectTasksParams): Promise<ListProjectTasksRow[]> {
  const rows = await client.query(listProjectTasksSql, [params.projectId]);
  return rows as unknown as ListProjectTasksRow[];
}

/** Descriptor for `useNamedQuery(listProjectTasksQuery, params)` — sql + tables + row type. */
export const listProjectTasksQuery: NamedQuery<ListProjectTasksRow, ListProjectTasksParams> = {
  sql: listProjectTasksSql,
  tables: listProjectTasksTables,
  bind: (params: ListProjectTasksParams) => [params.projectId],
};

/** One row of the 'projectDocCount' query (its projection). */
export interface ProjectDocCountRow {
  project_id: string;
  doc_count: number | null;
}

/** Tables 'projectDocCount' reads — the exact useSyncQuery `{tables}` set. */
export const projectDocCountTables = ['docs'] as const;

const projectDocCountSql = 'SELECT project_id, count(*) AS doc_count FROM docs GROUP BY project_id';

/** Run the 'projectDocCount' named query (SELECT-only). */
export async function projectDocCount(client: QueryClient): Promise<ProjectDocCountRow[]> {
  const rows = await client.query(projectDocCountSql);
  return rows as unknown as ProjectDocCountRow[];
}

/** Descriptor for `useNamedQuery(projectDocCountQuery)` — sql + tables + row type. */
export const projectDocCountQuery: NamedQuery<ProjectDocCountRow, undefined> = {
  sql: projectDocCountSql,
  tables: projectDocCountTables,
  bind: () => [],
};

/** One row of the 'taskTitles' query (its projection). */
export interface TaskTitlesRow {
  id: string;
  title: string;
}

/** Tables 'taskTitles' reads — the exact useSyncQuery `{tables}` set. */
export const taskTitlesTables = ['tasks'] as const;

const taskTitlesSql = 'SELECT id, title FROM tasks';

/** Run the 'taskTitles' named query (SELECT-only). */
export async function taskTitles(client: QueryClient): Promise<TaskTitlesRow[]> {
  const rows = await client.query(taskTitlesSql);
  return rows as unknown as TaskTitlesRow[];
}

/** Descriptor for `useNamedQuery(taskTitlesQuery)` — sql + tables + row type. */
export const taskTitlesQuery: NamedQuery<TaskTitlesRow, undefined> = {
  sql: taskTitlesSql,
  tables: taskTitlesTables,
  bind: () => [],
};

/** One row of the 'tasksInProjects' query (its projection). */
export interface TasksInProjectsRow {
  id: string;
  title: string;
}

/** Named parameters for 'tasksInProjects'. */
export interface TasksInProjectsParams {
  first: string;
  second: string;
}

/** Tables 'tasksInProjects' reads — the exact useSyncQuery `{tables}` set. */
export const tasksInProjectsTables = ['tasks'] as const;

const tasksInProjectsSql = 'SELECT id, title FROM tasks WHERE project_id IN (?, ?)';

/** Run the 'tasksInProjects' named query (SELECT-only). */
export async function tasksInProjects(client: QueryClient, params: TasksInProjectsParams): Promise<TasksInProjectsRow[]> {
  const rows = await client.query(tasksInProjectsSql, [params.first, params.second]);
  return rows as unknown as TasksInProjectsRow[];
}

/** Descriptor for `useNamedQuery(tasksInProjectsQuery, params)` — sql + tables + row type. */
export const tasksInProjectsQuery: NamedQuery<TasksInProjectsRow, TasksInProjectsParams> = {
  sql: tasksInProjectsSql,
  tables: tasksInProjectsTables,
  bind: (params: TasksInProjectsParams) => [params.first, params.second],
};

/** One row of the 'tasksSince' query (its projection). */
export interface TasksSinceRow {
  id: string;
  title: string;
}

/** Named parameters for 'tasksSince'. */
export interface TasksSinceParams {
  sinceMs: number;
}

/** Tables 'tasksSince' reads — the exact useSyncQuery `{tables}` set. */
export const tasksSinceTables = ['tasks'] as const;

const tasksSinceSql = 'SELECT id, title FROM tasks WHERE estimated_at > ? + 0';

/** Run the 'tasksSince' named query (SELECT-only). */
export async function tasksSince(client: QueryClient, params: TasksSinceParams): Promise<TasksSinceRow[]> {
  const rows = await client.query(tasksSinceSql, [params.sinceMs]);
  return rows as unknown as TasksSinceRow[];
}

/** Descriptor for `useNamedQuery(tasksSinceQuery, params)` — sql + tables + row type. */
export const tasksSinceQuery: NamedQuery<TasksSinceRow, TasksSinceParams> = {
  sql: tasksSinceSql,
  tables: tasksSinceTables,
  bind: (params: TasksSinceParams) => [params.sinceMs],
};
