// Generated by @syncular-v2/typegen — DO NOT EDIT.
// irVersion: 1
// irHash: sha256:7206380358bb01c1ca51e8992be93a4fb77ef4cb05755016cb8e79aae08997e6
// ignore_for_file: type=lint

import 'package:syncular/syncular.dart';

/// Lift a SQLite boolean: a real bool, or 0/1 as a number.
bool? _queryRowBool(Object? value) {
  if (value is bool) return value;
  if (value is num) return value != 0;
  return null;
}

/// Decode the core's {'\$bytes': '<hex>'} marshaling (bytes as hex).
List<int>? _queryRowBytes(Object? value) {
  if (value is! Map) return null;
  final hex = value[r'$bytes'];
  if (hex is! String || hex.length % 2 != 0) return null;
  return [
    for (var i = 0; i < hex.length; i += 2)
      int.parse(hex.substring(i, i + 2), radix: 16),
  ];
}

/// Encode bytes as the core's {'\$bytes': '<hex>'} marshaling for binding.
Map<String, Object?> _queryBindBytes(List<int> value) {
  final hex = value.map((b) => b.toRadixString(16).padLeft(2, '0')).join();
  return {r'$bytes': hex};
}

/// One row of the docWithBody query (its projection).
class DocWithBodyRow {
  final String docId;
  final String body;
  final String taskTitle;

  const DocWithBodyRow({required this.docId, required this.body, required this.taskTitle});

  static DocWithBodyRow? fromRow(Map<String, Object?> row) {
    final docId = row['doc_id'] as String?;
    if (docId == null) return null;
    final body = row['body'] as String?;
    if (body == null) return null;
    final taskTitle = row['task_title'] as String?;
    if (taskTitle == null) return null;
    return DocWithBodyRow(docId: docId, body: body, taskTitle: taskTitle);
  }
}

/// One row of the listProjectTasks query (its projection).
class ListProjectTasksRow {
  final String id;
  final String title;
  final bool done;
  final int? priority;
  final double? estimate;

  const ListProjectTasksRow({required this.id, required this.title, required this.done, this.priority, this.estimate});

  static ListProjectTasksRow? fromRow(Map<String, Object?> row) {
    final id = row['id'] as String?;
    if (id == null) return null;
    final title = row['title'] as String?;
    if (title == null) return null;
    final done = _queryRowBool(row['done']);
    if (done == null) return null;
    return ListProjectTasksRow(id: id, title: title, done: done, priority: (row['priority'] as num?)?.toInt(), estimate: (row['estimate'] as num?)?.toDouble());
  }
}

/// One row of the projectDocCount query (its projection).
class ProjectDocCountRow {
  final String projectId;
  final double? docCount;

  const ProjectDocCountRow({required this.projectId, this.docCount});

  static ProjectDocCountRow? fromRow(Map<String, Object?> row) {
    final projectId = row['project_id'] as String?;
    if (projectId == null) return null;
    return ProjectDocCountRow(projectId: projectId, docCount: (row['doc_count'] as num?)?.toDouble());
  }
}

/// One row of the taskTitles query (its projection).
class TaskTitlesRow {
  final String id;
  final String title;

  const TaskTitlesRow({required this.id, required this.title});

  static TaskTitlesRow? fromRow(Map<String, Object?> row) {
    final id = row['id'] as String?;
    if (id == null) return null;
    final title = row['title'] as String?;
    if (title == null) return null;
    return TaskTitlesRow(id: id, title: title);
  }
}

/// One row of the tasksInProjects query (its projection).
class TasksInProjectsRow {
  final String id;
  final String title;

  const TasksInProjectsRow({required this.id, required this.title});

  static TasksInProjectsRow? fromRow(Map<String, Object?> row) {
    final id = row['id'] as String?;
    if (id == null) return null;
    final title = row['title'] as String?;
    if (title == null) return null;
    return TasksInProjectsRow(id: id, title: title);
  }
}

/// One row of the tasksSince query (its projection).
class TasksSinceRow {
  final String id;
  final String title;

  const TasksSinceRow({required this.id, required this.title});

  static TasksSinceRow? fromRow(Map<String, Object?> row) {
    final id = row['id'] as String?;
    if (id == null) return null;
    final title = row['title'] as String?;
    if (title == null) return null;
    return TasksSinceRow(id: id, title: title);
  }
}

/// Tables the docWithBody query reads (exact invalidation set).
const List<String> syncularDocWithBodyQueryTables = ['docs', 'tasks'];

const String _docWithBodySql = 'SELECT d.id AS doc_id, d.body, t.title AS task_title FROM docs d JOIN tasks t ON t.project_id = d.project_id WHERE d.org_id = ?';

/// Run the docWithBody named query (SELECT-only).
List<DocWithBodyRow> syncularDocWithBodyQuery(SyncularClient client, {required String orgId}) {
  final params = <Object?>[orgId];
  return client.query(_docWithBodySql, params: params).map(DocWithBodyRow.fromRow).whereType<DocWithBodyRow>().toList();
}

/// Tables the listProjectTasks query reads (exact invalidation set).
const List<String> syncularListProjectTasksQueryTables = ['tasks'];

const String _listProjectTasksSql = 'SELECT id, title, done, priority, estimate FROM tasks WHERE project_id = ? ORDER BY priority';

/// Run the listProjectTasks named query (SELECT-only).
List<ListProjectTasksRow> syncularListProjectTasksQuery(SyncularClient client, {required String projectId}) {
  final params = <Object?>[projectId];
  return client.query(_listProjectTasksSql, params: params).map(ListProjectTasksRow.fromRow).whereType<ListProjectTasksRow>().toList();
}

/// Tables the projectDocCount query reads (exact invalidation set).
const List<String> syncularProjectDocCountQueryTables = ['docs'];

const String _projectDocCountSql = 'SELECT project_id, count(*) AS doc_count FROM docs GROUP BY project_id';

/// Run the projectDocCount named query (SELECT-only).
List<ProjectDocCountRow> syncularProjectDocCountQuery(SyncularClient client) {
  return client.query(_projectDocCountSql).map(ProjectDocCountRow.fromRow).whereType<ProjectDocCountRow>().toList();
}

/// Tables the taskTitles query reads (exact invalidation set).
const List<String> syncularTaskTitlesQueryTables = ['tasks'];

const String _taskTitlesSql = 'SELECT id, title FROM tasks';

/// Run the taskTitles named query (SELECT-only).
List<TaskTitlesRow> syncularTaskTitlesQuery(SyncularClient client) {
  return client.query(_taskTitlesSql).map(TaskTitlesRow.fromRow).whereType<TaskTitlesRow>().toList();
}

/// Tables the tasksInProjects query reads (exact invalidation set).
const List<String> syncularTasksInProjectsQueryTables = ['tasks'];

const String _tasksInProjectsSql = 'SELECT id, title FROM tasks WHERE project_id IN (?, ?)';

/// Run the tasksInProjects named query (SELECT-only).
List<TasksInProjectsRow> syncularTasksInProjectsQuery(SyncularClient client, {required String first, required String second}) {
  final params = <Object?>[first, second];
  return client.query(_tasksInProjectsSql, params: params).map(TasksInProjectsRow.fromRow).whereType<TasksInProjectsRow>().toList();
}

/// Tables the tasksSince query reads (exact invalidation set).
const List<String> syncularTasksSinceQueryTables = ['tasks'];

const String _tasksSinceSql = 'SELECT id, title FROM tasks WHERE estimated_at > ? + 0';

/// Run the tasksSince named query (SELECT-only).
List<TasksSinceRow> syncularTasksSinceQuery(SyncularClient client, {required int sinceMs}) {
  final params = <Object?>[sinceMs];
  return client.query(_tasksSinceSql, params: params).map(TasksSinceRow.fromRow).whereType<TasksSinceRow>().toList();
}
