/**
 * Golden-file tests for the named-query emitters (TS/Swift/Kotlin/Dart/Rust),
 * mirroring the schema goldens: the committed `*.queries.*` fixtures are the
 * snapshots; regeneration must reproduce them byte-exactly + deterministically,
 * each carries the DO-NOT-EDIT header + IR hash, and `--check` covers them.
 *
 * The fixture `queries/` set covers the analysis surface: plain select, a
 * projection subset, a join, param inference (equality + IN), a
 * comment-typed param, and an aggregate fallback column.
 */
import { describe, expect, test } from 'bun:test';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  analyzeQueries,
  checkOutputs,
  generate,
  loadQueries,
  serializeQueryIr,
} from '../src';

const FIXTURE = join(import.meta.dir, 'fixtures', 'basic');

const QUERY_FILES = {
  ts: 'syncular.queries.ts',
  swift: 'Syncular.queries.swift',
  kotlin: 'Syncular.queries.kt',
  dart: 'syncular.queries.dart',
  rust: 'syncular.queries.rs',
} as const;

function outputFor(basename: string): string {
  const result = generate(FIXTURE);
  const output = result.outputs.find((o) => o.path.endsWith(`/${basename}`));
  if (output === undefined) throw new Error(`fixture did not emit ${basename}`);
  return output.content;
}

describe('named-query emitter goldens', () => {
  for (const [lang, basename] of Object.entries(QUERY_FILES)) {
    describe(lang, () => {
      test('snapshot matches byte-exactly', () => {
        const committed = readFileSync(join(FIXTURE, basename), 'utf8');
        expect(outputFor(basename)).toBe(committed);
      });

      test('two runs are byte-identical (determinism)', () => {
        expect(outputFor(basename)).toBe(outputFor(basename));
      });

      test('carries the DO-NOT-EDIT header + IR hash', () => {
        const content = outputFor(basename);
        expect(content.startsWith('// Generated by @syncular/typegen')).toBe(
          true,
        );
        expect(content).toContain(`// irHash: ${generate(FIXTURE).queryHash}`);
      });
    });
  }

  test('all five query files appear in outputs after the schema files', () => {
    const names = generate(FIXTURE).outputs.map((o) => o.path.split('/').pop());
    // schema outputs then query outputs, one queries file per emitter.
    expect(names).toContain(QUERY_FILES.ts);
    expect(names).toContain(QUERY_FILES.swift);
    expect(names).toContain(QUERY_FILES.kotlin);
    expect(names).toContain(QUERY_FILES.dart);
    expect(names).toContain(QUERY_FILES.rust);
  });

  test('checkOutputs covers the query files (no drift on committed)', () => {
    expect(checkOutputs(generate(FIXTURE))).toEqual([]);
  });

  test('the QueryIR JSON matches the committed golden byte-exactly', () => {
    // The frontend-equivalence contract (DESIGN-queries.md §1): whatever
    // frontend produced these queries, this exact IR JSON must come out.
    const committed = readFileSync(
      join(FIXTURE, 'syncular.queries.ir.json'),
      'utf8',
    );
    const result = generate(FIXTURE);
    expect(result.queryIrJson).toBe(committed);
    expect(serializeQueryIr(result.queries)).toBe(committed);
    expect(
      result.outputs.find((output) => output.path.endsWith('.ir.json')),
    ).toBeDefined();
  });
});

describe('named-query analysis fidelity', () => {
  const ir = generate(FIXTURE).ir;
  const analyzed = analyzeQueries(ir, loadQueries(join(FIXTURE, 'queries')));
  const byName = new Map(analyzed.map((q) => [q.name, q] as const));

  test('plain column refs get EXACT IR type + nullability', () => {
    const q = byName.get('listProjectTasks');
    expect(q).toBeDefined();
    const cols = new Map(q?.columns.map((c) => [c.name, c]) ?? []);
    // done → boolean, non-nullable (NOT NULL in schema).
    expect(cols.get('done')).toMatchObject({
      type: 'boolean',
      nullable: false,
      fidelity: 'exact',
    });
    // priority → integer, nullable; estimate → float, nullable.
    expect(cols.get('priority')).toMatchObject({
      type: 'integer',
      nullable: true,
      fidelity: 'exact',
    });
    expect(cols.get('estimate')).toMatchObject({
      type: 'float',
      fidelity: 'exact',
    });
  });

  test('param types are inferred from equality + IN comparisons', () => {
    expect(byName.get('listProjectTasks')?.params).toEqual([
      {
        name: 'projectId',
        langName: 'projectId',
        type: 'string',
        source: 'inferred',
      },
    ]);
    expect(byName.get('tasksInProjects')?.params).toEqual([
      { name: 'first', langName: 'first', type: 'string', source: 'inferred' },
      {
        name: 'second',
        langName: 'second',
        type: 'string',
        source: 'inferred',
      },
    ]);
  });

  test('a comment overrides an un-inferable param', () => {
    expect(byName.get('tasksSince')?.params).toEqual([
      {
        name: 'sinceMs',
        langName: 'sinceMs',
        type: 'integer',
        source: 'comment',
      },
    ]);
  });

  test('a computed aggregate column is the documented fallback', () => {
    const cols = byName.get('projectDocCount')?.columns ?? [];
    const count = cols.find((c) => c.name === 'doc_count');
    expect(count).toMatchObject({ nullable: true, fidelity: 'fallback' });
    // project_id (a plain grouped ref) stays exact + non-nullable.
    expect(cols.find((c) => c.name === 'project_id')).toMatchObject({
      type: 'string',
      nullable: false,
      fidelity: 'exact',
    });
  });

  test('the tables set is the resolved FROM/JOIN IR tables (exact deps)', () => {
    expect(byName.get('docWithBody')?.tables).toEqual(['docs', 'tasks']);
    expect(byName.get('listProjectTasks')?.tables).toEqual(['tasks']);
  });

  test('emitted SQL is positional (? placeholders), comment-free, one line', () => {
    const sql = byName.get('listProjectTasks')?.positionalSql ?? '';
    expect(sql).toBe(
      'SELECT id, title, done, priority, estimate FROM tasks WHERE project_id = ? ORDER BY priority',
    );
  });

  test('a nested-folder query gets a path-derived camelCase name', () => {
    // reporting/tasks-by-priority.sql → reportingTasksByPriority.
    const q = byName.get('reportingTasksByPriority');
    expect(q).toBeDefined();
    expect(q?.tables).toEqual(['tasks']);
    expect(q?.params).toEqual([
      {
        name: 'priority',
        langName: 'priority',
        type: 'integer',
        source: 'inferred',
      },
    ]);
  });

  test('a multi-statement file yields one query per `-- name:` statement', () => {
    // task-reports.sql holds reportOpenTasks + reportDocScores.
    const open = byName.get('reportOpenTasks');
    const scores = byName.get('reportDocScores');
    expect(open).toBeDefined();
    expect(scores).toBeDefined();
    // Per-statement param scoping: :projectId inferred in the first statement…
    expect(open?.params).toEqual([
      {
        name: 'projectId',
        langName: 'projectId',
        type: 'string',
        source: 'inferred',
      },
    ]);
    expect(open?.tables).toEqual(['tasks']);
    // …:minScore's `-- param float` comment belongs to the SECOND statement.
    expect(scores?.params).toEqual([
      {
        name: 'minScore',
        langName: 'minScore',
        type: 'float',
        source: 'comment',
      },
    ]);
    expect(scores?.tables).toEqual(['docs']);
    // A path-derived `taskReports` name does NOT exist (overrides replace it).
    expect(byName.get('taskReports')).toBeUndefined();
  });

  test('a single-statement file honors a `-- name:` override verbatim', () => {
    // doc-lookup.sql → default docLookup, overridden to findDocByOrg.
    expect(byName.get('findDocByOrg')).toBeDefined();
    expect(byName.get('docLookup')).toBeUndefined();
    expect(byName.get('findDocByOrg')?.params).toEqual([
      { name: 'orgId', langName: 'orgId', type: 'string', source: 'inferred' },
    ]);
  });
});
