// Generated by @syncular/typegen — DO NOT EDIT.
// irVersion: 1
// irHash: sha256:7c07edc88f5e6f4b6da196da47e08abe4c7cb304d257a429da6950024f02fa85

export type SyqlRuntimeErrorCode =
  | 'SYQL_RUNTIME_MISSING_REQUIRED_INPUT'
  | 'SYQL_RUNTIME_UNKNOWN_INPUT'
  | 'SYQL_RUNTIME_INVALID_INPUT'
  | 'SYQL_RUNTIME_INVALID_GROUP'
  | 'SYQL_RUNTIME_INVALID_SORT'
  | 'SYQL_RUNTIME_INVALID_LIMIT';

export class SyqlInputError extends Error {
  readonly name = 'SyqlInputError';
  constructor(readonly code: SyqlRuntimeErrorCode, message: string) {
    super(message);
  }
}

export interface SyqlPresent<T> {
  readonly present: true;
  readonly value: T;
}

export function syqlPresent<T>(value: T): SyqlPresent<T> {
  return { present: true, value };
}

/** A generated named-query row did not match its analyzed result type. */
export class QueryResultDecodeError extends TypeError {
  readonly name = 'QueryResultDecodeError';
  constructor(readonly query: string, readonly column: string) {
    super(query + ': result column ' + column + ' is not a SQLite boolean');
  }
}

/** Lift a SQLite boolean: preserve booleans, map 0 to false and finite non-zero numbers to true. */
function decodeQueryBoolean(value: unknown, query: string, column: string): boolean {
  if (typeof value === 'boolean') return value;
  if (typeof value === 'number' && Number.isFinite(value)) return value !== 0;
  throw new QueryResultDecodeError(query, column);
}

/** A bindable SQL param/row value (the wrapper's SqlValue subset). */
export type QueryValue =
  | string
  | number
  | bigint
  | boolean
  | Uint8Array
  | null;

/** Minimal structural client surface — the wrapper's positional
 *  `query(sql, params?)`. `SyncClient`/`SyncClientHandle`/`SyncClientLike`
 *  all satisfy it, so this module imports nothing. */
export interface QueryClient {
  query(
    sql: string,
    params?: readonly QueryValue[],
  ): unknown[] | Promise<unknown[]>;
}

/** A named-query descriptor — checked SQL plus revisioned reactive metadata and a
 *  `bind(params)` → positional args. Consumed by
 *  `@syncular/react`'s `useQuery`. `Row` is the projection row
 *  type; `Params` is `undefined` for a param-less query. `sqlFor`
 *  selects a checked revision-1 SYQL physical statement when needed. */
export interface NamedQuery<Row, Params = undefined> {
  readonly id: string;
  readonly hasParams: boolean;
  readonly sql: string;
  readonly mapRow: (row: Readonly<Record<string, unknown>>) => Row;
  readonly tables: readonly string[];
  readonly bind: (params: Params) => readonly QueryValue[];
  readonly sqlFor?: (params: Params) => string;
  readonly dependencies: (params: Params) => readonly QueryDependency[];
  readonly coverage: (params: Params) => readonly WindowCoverage[];
  readonly rowKey?: (row: Row) => readonly QueryValue[];
  /** Phantom — carries the Row type for `useQuery` inference. */
  readonly __row?: Row;
}

export interface QueryDependency {
  readonly table: string;
  readonly scopeKeys?: readonly string[];
}

export interface WindowCoverage {
  readonly base: {
    readonly table: string;
    readonly variable: string;
    readonly fixedScopes?: Readonly<Record<string, readonly string[]>>;
    readonly params?: string;
  };
  readonly units: readonly string[];
}

/** One row of the 'listTodos' query (its projection). */
export interface ListTodosRow {
  id: string;
  listId: string;
  title: string;
  done: boolean;
  position: number;
  updatedAtMs: number;
}

/** Decode one storage-shaped result row for 'listTodos'. */
export function listTodosMapRow(row: Readonly<Record<string, unknown>>): ListTodosRow {
  return {
    ...row,
    done: decodeQueryBoolean(row['done'], 'listTodos', 'done'),
  } as unknown as ListTodosRow;
}

/** Public revision-1 SYQL inputs for 'listTodos'. */
export interface ListTodosParams {
  listId: string;
}

function listTodosValidate(raw?: ListTodosParams): ListTodosParams {
  const params = raw ?? ({} as ListTodosParams);
  const allowed = new Set(['listId']);
  for (const key of Object.keys(params)) {
    if (!allowed.has(key)) throw new SyqlInputError('SYQL_RUNTIME_UNKNOWN_INPUT', 'listTodos' + ': unknown input ' + key);
  }
  if (!Object.prototype.hasOwnProperty.call(params, 'listId')) throw new SyqlInputError('SYQL_RUNTIME_MISSING_REQUIRED_INPUT', 'listTodos: missing required input listId');
  if (!(typeof params.listId === 'string')) throw new SyqlInputError('SYQL_RUNTIME_INVALID_INPUT', 'listTodos: invalid input listId');
  return params;
}

/** Tables 'listTodos' reads (compatibility/export surface). */
export const listTodosTables = ['todos'] as const;

const listTodosStatements: { sql: string; bind: (params: ListTodosParams) => QueryValue[] }[] = [
  { sql: 'select id, list_id AS listId, title, done, position, updated_at_ms AS updatedAtMs from todos where todos.list_id = ? order by position, id', bind: (params) => [params.listId] },
];
function listTodosSelect(raw: ListTodosParams): { sql: string; bind: QueryValue[] } {
  const params = listTodosValidate(raw);
  let mask = 0;
  const statement = listTodosStatements[mask * 1 + 0];
  if (statement === undefined) throw new Error('invalid generated SYQL statement index');
  return { sql: statement.sql, bind: statement.bind(params) };
}

/** Run the 'listTodos' named query (SELECT-only). */
export async function listTodos(client: QueryClient, params: ListTodosParams): Promise<ListTodosRow[]> {
  const selected = listTodosSelect(params);
  const rows = await client.query(selected.sql, selected.bind);
  return rows.map((row) => listTodosMapRow(row as Readonly<Record<string, unknown>>));
}

/** Revisioned reactive descriptor for `useQuery(listTodosQuery, params)`. */
export const listTodosQuery: NamedQuery<ListTodosRow, ListTodosParams> = {
  id: 'sha256:7c07edc88f5e6f4b6da196da47e08abe4c7cb304d257a429da6950024f02fa85/listTodos',
  hasParams: true,
  sql: 'select id, list_id AS listId, title, done, position, updated_at_ms AS updatedAtMs from todos where todos.list_id = ? order by position, id',
  mapRow: listTodosMapRow,
  sqlFor: (params: ListTodosParams) => listTodosSelect(params).sql,
  tables: listTodosTables,
  dependencies: (params) => [
    { table: 'todos', scopeKeys: ['list:' + String(params.listId) + ''] },
  ],
  coverage: () => [
  ],
  bind: (params: ListTodosParams) => listTodosSelect(params).bind,
  rowKey: (row) => [row.id],
};
