//! Tauri v2 plugin build script: generates the permission scaffolding for the
//! two commands the plugin exposes. `tauri-plugin` reads `permissions/` and
//! emits the autogenerated `allow-*`/`deny-*` permissions plus the `default`
//! permission set an app references in its capabilities.

const COMMANDS: &[&str] = &["syncular_command", "syncular_query"];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
