// Generated by @syncular/typegen — DO NOT EDIT.
// irVersion: 1
// irHash: sha256:e2e39c94ce6c13720e1f1579e2523d460fd6bb3fea2f8eaaa114305b7aa332ba

/** Structural descriptor consumed by renderer bindings; phantom type
 * fields make row/insert/update/id inference available without imports. */
export interface SyncTable<Row, Insert, Update, Id> {
  readonly name: string;
  /** Language-facing key used in generated row and mutation types. */
  readonly primaryKey: keyof Row & string;
  /** Physical SQLite/wire primary-key column. */
  readonly physicalPrimaryKey: string;
  readonly __row?: Row;
  readonly __insert?: Insert;
  readonly __update?: Update;
  readonly __id?: Id;
}

/** ServerSchema-compatible schema object (SPEC §2.4, §3.1). */
export const schema = {
  version: 1,
  tables: [
    {
      name: 'notes',
      columns: [
        { name: 'id', type: 'string', nullable: false },
        { name: 'list_id', type: 'string', nullable: false },
        { name: 'body', type: 'string', nullable: false },
        { name: 'updated_at_ms', type: 'integer', nullable: false },
      ],
      primaryKey: 'id',
      scopes: [
        { pattern: 'list:{list_id}', column: 'list_id' },
      ],
    },
  ],
} as const;

/** One notes row (§2.4 column order). */
export interface NotesRow {
  id: string;
  listId: string;
  body: string;
  updatedAtMs: number;
}

/** Insert shape: nullable columns may be omitted. */
export interface NotesInsert {
  id: string;
  listId: string;
  body: string;
  updatedAtMs: number;
}

/** Update shape: primary key required, all other columns optional. */
export interface NotesUpdate {
  id: string;
  listId?: string;
  body?: string;
  updatedAtMs?: number;
}

/** Typed mutation/resource descriptor for 'notes'. */
export const notesTable: SyncTable<NotesRow, NotesInsert, NotesUpdate, string> = {
  name: 'notes',
  primaryKey: 'id',
  physicalPrimaryKey: 'id',
};

export interface NotesInListParams {
  listId: string;
}

/** Requested-scope template for the 'notesInList' subscription. */
export const notesInListSubscription = {
  name: 'notesInList',
  table: 'notes',
  scopes: (params: NotesInListParams): Record<string, string[]> => ({
    list_id: [params.listId],
  }),
} as const;
