// Generated by @syncular-v2/typegen — DO NOT EDIT.
// irVersion: 1
// irHash: sha256:2ffc5b70cb96cd546326de9c06868bd988c9fa3459fb3bac8428a81dcc85fca0

/** ServerSchema-compatible schema object (SPEC §2.4, §3.1). */
export const schema = {
  version: 1,
  tables: [
    {
      name: 'todos',
      columns: [
        { name: 'id', type: 'string', nullable: false },
        { name: 'list_id', type: 'string', nullable: false },
        { name: 'title', type: 'string', nullable: false },
        { name: 'done', type: 'boolean', nullable: false },
        { name: 'position', type: 'integer', nullable: false },
        { name: 'updated_at_ms', type: 'integer', nullable: false },
      ],
      primaryKey: 'id',
      scopes: [
        { pattern: 'list:{list_id}', column: 'list_id' },
      ],
    },
  ],
} as const;

/** One todos row (§2.4 column order). */
export interface TodosRow {
  id: string;
  list_id: string;
  title: string;
  done: boolean;
  position: number;
  updated_at_ms: number;
}

/** Insert shape: nullable columns may be omitted. */
export interface TodosInsert {
  id: string;
  list_id: string;
  title: string;
  done: boolean;
  position: number;
  updated_at_ms: number;
}

/** Update shape: primary key required, all other columns optional. */
export interface TodosUpdate {
  id: string;
  list_id?: string;
  title?: string;
  done?: boolean;
  position?: number;
  updated_at_ms?: number;
}

export interface TodoListParams {
  listId: string;
}

/** Requested-scope template for the 'todoList' subscription. */
export const todoListSubscription = {
  name: 'todoList',
  table: 'todos',
  scopes: (params: TodoListParams): Record<string, string[]> => ({
    list_id: [params.listId],
  }),
} as const;
