CREATE TABLE IF NOT EXISTS tasks (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  completed INTEGER NOT NULL DEFAULT 0,
  user_id TEXT NOT NULL,
  created_at BIGINT NOT NULL DEFAULT 0,
  server_version BIGINT NOT NULL DEFAULT 0
) WITHOUT ROWID;
