// Auto-generated by BoltFFI. Do not edit.
package dev.syncular.client;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.charset.StandardCharsets;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.function.Function;
import java.util.function.IntFunction;

final class WireReader {
    private final byte[] data;
    private int pos;
    private static final int MIN_LONG_VEC_INPUT_CAPACITY = 16;
    private static final ThreadLocal<ArrayList<ByteBuffer>> LONG_VEC_INPUT_SLOTS =
            ThreadLocal.withInitial(ArrayList::new);

    WireReader(byte[] data) {
        this.data = data;
        this.pos = 0;
    }

    boolean readBool() {
        return data[pos++] != 0;
    }

    byte readI8() {
        return data[pos++];
    }

    short readI16() {
        short v = (short) ((data[pos] & 0xFF) | ((data[pos + 1] & 0xFF) << 8));
        pos += 2;
        return v;
    }

    int readI32() {
        int v = (data[pos] & 0xFF)
              | ((data[pos + 1] & 0xFF) << 8)
              | ((data[pos + 2] & 0xFF) << 16)
              | ((data[pos + 3] & 0xFF) << 24);
        pos += 4;
        return v;
    }

    long readI64() {
        long v = (data[pos] & 0xFFL)
               | ((data[pos + 1] & 0xFFL) << 8)
               | ((data[pos + 2] & 0xFFL) << 16)
               | ((data[pos + 3] & 0xFFL) << 24)
               | ((data[pos + 4] & 0xFFL) << 32)
               | ((data[pos + 5] & 0xFFL) << 40)
               | ((data[pos + 6] & 0xFFL) << 48)
               | ((data[pos + 7] & 0xFFL) << 56);
        pos += 8;
        return v;
    }

    float readF32() {
        return Float.intBitsToFloat(readI32());
    }

    double readF64() {
        return Double.longBitsToDouble(readI64());
    }

    private void requireAvailable(int len, String kind) {
        if (len > data.length - pos) {
            throw new RuntimeException("corrupt wire: truncated " + kind);
        }
    }

    private int checkedByteCount(int count, int elementSize, String kind) {
        if (count < 0) throw new RuntimeException("corrupt wire: negative " + kind + " length");
        long byteCountLong = (long) count * (long) elementSize;
        if (byteCountLong > Integer.MAX_VALUE) {
            throw new RuntimeException("corrupt wire: " + kind + " payload too large");
        }
        int byteCount = (int) byteCountLong;
        requireAvailable(byteCount, kind + " payload");
        return byteCount;
    }

    String readString() {
        int len = readI32();
        if (len == 0) return "";
        if (len < 0) throw new RuntimeException("corrupt wire: negative string length");
        requireAvailable(len, "string payload");
        String v = new String(data, pos, len, StandardCharsets.UTF_8);
        pos += len;
        return v;
    }

    byte[] readBytes() {
        int len = readI32();
        if (len == 0) return new byte[0];
        if (len < 0) throw new RuntimeException("corrupt wire: negative bytes length");
        requireAvailable(len, "bytes payload");
        byte[] v = new byte[len];
        System.arraycopy(data, pos, v, 0, len);
        pos += len;
        return v;
    }

    boolean[] readBooleanArray() {
        int count = readI32();
        if (count == 0) return new boolean[0];
        int byteCount = checkedByteCount(count, 1, "boolean vec");
        boolean[] result = new boolean[count];
        int end = pos + byteCount;
        for (int index = 0, dataIndex = pos; dataIndex < end; index++, dataIndex++) {
            result[index] = data[dataIndex] != 0;
        }
        pos = end;
        return result;
    }

    byte[] readByteArray() {
        int count = readI32();
        if (count == 0) return new byte[0];
        int byteCount = checkedByteCount(count, 1, "byte vec");
        byte[] result = new byte[count];
        System.arraycopy(data, pos, result, 0, byteCount);
        pos += byteCount;
        return result;
    }

    short[] readShortArray() {
        int count = readI32();
        if (count == 0) return new short[0];
        int byteCount = checkedByteCount(count, 2, "short vec");
        short[] result = new short[count];
        ByteBuffer.wrap(data, pos, byteCount).order(ByteOrder.LITTLE_ENDIAN).asShortBuffer().get(result);
        pos += byteCount;
        return result;
    }

    int[] readIntArray() {
        int count = readI32();
        if (count == 0) return new int[0];
        int byteCount = checkedByteCount(count, 4, "int vec");
        int[] result = new int[count];
        ByteBuffer.wrap(data, pos, byteCount).order(ByteOrder.LITTLE_ENDIAN).asIntBuffer().get(result);
        pos += byteCount;
        return result;
    }

    long[] readLongArray() {
        int count = readI32();
        if (count == 0) return new long[0];
        int byteCount = checkedByteCount(count, 8, "long vec");
        long[] result = new long[count];
        ByteBuffer.wrap(data, pos, byteCount).order(ByteOrder.LITTLE_ENDIAN).asLongBuffer().get(result);
        pos += byteCount;
        return result;
    }

    float[] readFloatArray() {
        int count = readI32();
        if (count == 0) return new float[0];
        int byteCount = checkedByteCount(count, 4, "float vec");
        float[] result = new float[count];
        ByteBuffer.wrap(data, pos, byteCount).order(ByteOrder.LITTLE_ENDIAN).asFloatBuffer().get(result);
        pos += byteCount;
        return result;
    }

    double[] readDoubleArray() {
        int count = readI32();
        if (count == 0) return new double[0];
        int byteCount = checkedByteCount(count, 8, "double vec");
        double[] result = new double[count];
        ByteBuffer.wrap(data, pos, byteCount).order(ByteOrder.LITTLE_ENDIAN).asDoubleBuffer().get(result);
        pos += byteCount;
        return result;
    }

    ByteBuffer readBlittableBuffer(int count, int elementSize) {
        if (count < 0) throw new RuntimeException("corrupt wire: negative vec length");
        long byteCountLong = (long) count * (long) elementSize;
        if (byteCountLong > Integer.MAX_VALUE) {
            throw new RuntimeException("corrupt wire: vec payload too large");
        }
        int byteCount = (int) byteCountLong;
        requireAvailable(byteCount, "blittable vec payload");
        ByteBuffer view = ByteBuffer
                .wrap(data, pos, byteCount)
                .slice()
                .order(ByteOrder.LITTLE_ENDIAN);
        pos += byteCount;
        return view;
    }

    static boolean[] booleanArrayFromRawBuffer(byte[] buf) {
        if (buf == null || buf.length == 0) return new boolean[0];
        boolean[] result = new boolean[buf.length];
        for (int i = 0; i < buf.length; i++) result[i] = buf[i] != 0;
        return result;
    }

    static short[] shortArrayFromRawBuffer(byte[] buf) {
        if (buf == null || buf.length == 0) return new short[0];
        ByteBuffer bb = ByteBuffer.wrap(buf).order(ByteOrder.LITTLE_ENDIAN);
        short[] result = new short[buf.length / 2];
        bb.asShortBuffer().get(result);
        return result;
    }

    static int[] intArrayFromRawBuffer(byte[] buf) {
        if (buf == null || buf.length == 0) return new int[0];
        ByteBuffer bb = ByteBuffer.wrap(buf).order(ByteOrder.LITTLE_ENDIAN);
        int[] result = new int[buf.length / 4];
        bb.asIntBuffer().get(result);
        return result;
    }

    static long[] longArrayFromRawBuffer(byte[] buf) {
        if (buf == null || buf.length == 0) return new long[0];
        ByteBuffer bb = ByteBuffer.wrap(buf).order(ByteOrder.LITTLE_ENDIAN);
        long[] result = new long[buf.length / 8];
        bb.asLongBuffer().get(result);
        return result;
    }

    static float[] floatArrayFromRawBuffer(byte[] buf) {
        if (buf == null || buf.length == 0) return new float[0];
        ByteBuffer bb = ByteBuffer.wrap(buf).order(ByteOrder.LITTLE_ENDIAN);
        float[] result = new float[buf.length / 4];
        bb.asFloatBuffer().get(result);
        return result;
    }

    static double[] doubleArrayFromRawBuffer(byte[] buf) {
        if (buf == null || buf.length == 0) return new double[0];
        ByteBuffer bb = ByteBuffer.wrap(buf).order(ByteOrder.LITTLE_ENDIAN);
        double[] result = new double[buf.length / 8];
        bb.asDoubleBuffer().get(result);
        return result;
    }

    @FunctionalInterface
    interface ByteMapper<T> {
        T apply(byte value);
    }

    @FunctionalInterface
    interface ShortMapper<T> {
        T apply(short value);
    }

    @FunctionalInterface
    interface IntMapper<T> {
        T apply(int value);
    }

    @FunctionalInterface
    interface LongMapper<T> {
        T apply(long value);
    }

    @FunctionalInterface
    interface ByteExtractor<T> {
        byte apply(T value);
    }

    @FunctionalInterface
    interface ShortExtractor<T> {
        short apply(T value);
    }

    @FunctionalInterface
    interface IntExtractor<T> {
        int apply(T value);
    }

    @FunctionalInterface
    interface LongExtractor<T> {
        long apply(T value);
    }

    static <T> byte[] toByteArray(List<T> values, ByteExtractor<T> extractor) {
        if (values.isEmpty()) return new byte[0];
        byte[] result = new byte[values.size()];
        int index = 0;
        for (T value : values) result[index++] = extractor.apply(value);
        return result;
    }

    static <T> short[] toShortArray(List<T> values, ShortExtractor<T> extractor) {
        if (values.isEmpty()) return new short[0];
        short[] result = new short[values.size()];
        int index = 0;
        for (T value : values) result[index++] = extractor.apply(value);
        return result;
    }

    static <T> int[] toIntArray(List<T> values, IntExtractor<T> extractor) {
        if (values.isEmpty()) return new int[0];
        int[] result = new int[values.size()];
        int index = 0;
        for (T value : values) result[index++] = extractor.apply(value);
        return result;
    }

    static <T> long[] toLongArray(List<T> values, LongExtractor<T> extractor) {
        if (values.isEmpty()) return new long[0];
        long[] result = new long[values.size()];
        int index = 0;
        for (T value : values) result[index++] = extractor.apply(value);
        return result;
    }

    static ByteBuffer encodeLongVecInput(long[] values, int slot) {
        if (slot < 0) {
            throw new RuntimeException("invalid long vec slot index");
        }
        int count = values == null ? 0 : values.length;
        long requiredCapacityLong = 4L + ((long) count * 8L);
        if (requiredCapacityLong > Integer.MAX_VALUE) {
            throw new RuntimeException("input too large: long vec payload exceeds JVM buffer limits");
        }
        int requiredCapacity = (int) requiredCapacityLong;
        ArrayList<ByteBuffer> buffers = LONG_VEC_INPUT_SLOTS.get();
        while (buffers.size() <= slot) {
            buffers.add(ByteBuffer.allocateDirect(MIN_LONG_VEC_INPUT_CAPACITY).order(ByteOrder.LITTLE_ENDIAN));
        }
        ByteBuffer buffer = buffers.get(slot);
        if (buffer.capacity() < requiredCapacity) {
            int grownCapacity = Math.max(buffer.capacity() * 2, requiredCapacity);
            buffer = ByteBuffer.allocateDirect(grownCapacity).order(ByteOrder.LITTLE_ENDIAN);
            buffers.set(slot, buffer);
        } else {
            buffer.clear();
            buffer.order(ByteOrder.LITTLE_ENDIAN);
        }
        buffer.putInt(count);
        if (values != null) {
            for (long value : values) {
                buffer.putLong(value);
            }
        }
        buffer.flip();
        return buffer;
    }

    static <T> List<T> mapByteArray(byte[] values, ByteMapper<T> mapper) {
        if (values == null || values.length == 0) return Collections.emptyList();
        List<T> result = new ArrayList<>(values.length);
        for (byte value : values) result.add(mapper.apply(value));
        return result;
    }

    static <T> List<T> mapShortArray(short[] values, ShortMapper<T> mapper) {
        if (values.length == 0) return Collections.emptyList();
        List<T> result = new ArrayList<>(values.length);
        for (short value : values) result.add(mapper.apply(value));
        return result;
    }

    static <T> List<T> mapShortRawBuffer(byte[] values, ShortMapper<T> mapper) {
        if (values == null || values.length == 0) return Collections.emptyList();
        if ((values.length & 1) != 0) {
            throw new RuntimeException("corrupt buffer: expected short-aligned enum vec payload");
        }
        ByteBuffer buffer = ByteBuffer.wrap(values).order(ByteOrder.LITTLE_ENDIAN);
        int count = values.length / 2;
        List<T> result = new ArrayList<>(count);
        for (int index = 0; index < count; index++) result.add(mapper.apply(buffer.getShort()));
        return result;
    }

    static <T> List<T> mapIntArray(int[] values, IntMapper<T> mapper) {
        if (values.length == 0) return Collections.emptyList();
        List<T> result = new ArrayList<>(values.length);
        for (int value : values) result.add(mapper.apply(value));
        return result;
    }

    static <T> List<T> mapIntRawBuffer(byte[] values, IntMapper<T> mapper) {
        if (values == null || values.length == 0) return Collections.emptyList();
        if ((values.length & 3) != 0) {
            throw new RuntimeException("corrupt buffer: expected int-aligned enum vec payload");
        }
        ByteBuffer buffer = ByteBuffer.wrap(values).order(ByteOrder.LITTLE_ENDIAN);
        int count = values.length / 4;
        List<T> result = new ArrayList<>(count);
        for (int index = 0; index < count; index++) result.add(mapper.apply(buffer.getInt()));
        return result;
    }

    static <T> List<T> mapLongArray(long[] values, LongMapper<T> mapper) {
        if (values.length == 0) return Collections.emptyList();
        List<T> result = new ArrayList<>(values.length);
        for (long value : values) result.add(mapper.apply(value));
        return result;
    }

    static <T> List<T> mapLongRawBuffer(byte[] values, LongMapper<T> mapper) {
        if (values == null || values.length == 0) return Collections.emptyList();
        if ((values.length & 7) != 0) {
            throw new RuntimeException("corrupt buffer: expected long-aligned enum vec payload");
        }
        ByteBuffer buffer = ByteBuffer.wrap(values).order(ByteOrder.LITTLE_ENDIAN);
        int count = values.length / 8;
        List<T> result = new ArrayList<>(count);
        for (int index = 0; index < count; index++) result.add(mapper.apply(buffer.getLong()));
        return result;
    }

    <T> List<T> readList(IntFunction<T> decoder) {
        int count = readI32();
        List<T> result = new ArrayList<>(count);
        for (int i = 0; i < count; i++) result.add(decoder.apply(i));
        return result;
    }

    static <T> List<T> readList(byte[] data, IntFunction<T> decoder) {
        return new WireReader(data).readList(decoder);
    }

    static WireReader fromBuffer(ByteBuffer buffer) {
        byte[] bytes = new byte[buffer.remaining()];
        buffer.get(bytes);
        return new WireReader(bytes);
    }

    static <T> T decodeBuffer(ByteBuffer buffer, Function<WireReader, T> decoder) {
        return decoder.apply(fromBuffer(buffer));
    }

    static String stringFromBuffer(ByteBuffer buffer) {
        byte[] bytes = new byte[buffer.remaining()];
        buffer.get(bytes);
        return new String(bytes, StandardCharsets.UTF_8);
    }

    static byte[] wireEncodeIntArray(int[] values) {
        ByteBuffer buf = ByteBuffer.allocate(4 + values.length * 4).order(ByteOrder.LITTLE_ENDIAN);
        buf.putInt(values.length);
        for (int v : values) buf.putInt(v);
        return buf.array();
    }

    static List<Boolean> readPackedBools(byte[] bytes) {
        List<Boolean> result = new ArrayList<>(bytes.length);
        for (byte b : bytes) result.add(b != 0);
        return result;
    }

    static List<Byte> readPackedBytes(byte[] bytes) {
        List<Byte> result = new ArrayList<>(bytes.length);
        for (byte b : bytes) result.add(b);
        return result;
    }

    static List<Short> readPackedShorts(byte[] bytes) {
        java.nio.ShortBuffer buf = ByteBuffer.wrap(bytes).order(ByteOrder.nativeOrder()).asShortBuffer();
        List<Short> result = new ArrayList<>(buf.remaining());
        while (buf.hasRemaining()) result.add(buf.get());
        return result;
    }

    static List<Integer> readPackedInts(byte[] bytes) {
        java.nio.IntBuffer buf = ByteBuffer.wrap(bytes).order(ByteOrder.nativeOrder()).asIntBuffer();
        List<Integer> result = new ArrayList<>(buf.remaining());
        while (buf.hasRemaining()) result.add(buf.get());
        return result;
    }

    static List<Long> readPackedLongs(byte[] bytes) {
        java.nio.LongBuffer buf = ByteBuffer.wrap(bytes).order(ByteOrder.nativeOrder()).asLongBuffer();
        List<Long> result = new ArrayList<>(buf.remaining());
        while (buf.hasRemaining()) result.add(buf.get());
        return result;
    }

    static List<Float> readPackedFloats(byte[] bytes) {
        java.nio.FloatBuffer buf = ByteBuffer.wrap(bytes).order(ByteOrder.nativeOrder()).asFloatBuffer();
        List<Float> result = new ArrayList<>(buf.remaining());
        while (buf.hasRemaining()) result.add(buf.get());
        return result;
    }

    static List<Double> readPackedDoubles(byte[] bytes) {
        java.nio.DoubleBuffer buf = ByteBuffer.wrap(bytes).order(ByteOrder.nativeOrder()).asDoubleBuffer();
        List<Double> result = new ArrayList<>(buf.remaining());
        while (buf.hasRemaining()) result.add(buf.get());
        return result;
    }
}

final class WireWriter implements AutoCloseable {
    private static final int MIN_CAPACITY = 16;
    private static final int MAX_POOLED_BUFFERS_PER_THREAD = 8;
    private static final int MAX_POOLED_CAPACITY = 1 << 20;
    private static final ThreadLocal<ArrayDeque<ByteBuffer>> POOL =
            ThreadLocal.withInitial(ArrayDeque::new);

    private ByteBuffer buf;
    private boolean closed;

    WireWriter(int capacity) {
        this.buf = takeBuffer(capacity);
        this.closed = false;
    }

    ByteBuffer toBuffer() {
        ByteBuffer view = buf.duplicate().order(ByteOrder.LITTLE_ENDIAN);
        view.flip();
        return view.slice().order(ByteOrder.LITTLE_ENDIAN);
    }

    byte[] toByteArray() {
        ByteBuffer view = toBuffer();
        byte[] bytes = new byte[view.remaining()];
        view.get(bytes);
        return bytes;
    }

    private void ensureCapacity(int needed) {
        if (buf.remaining() >= needed) return;
        int next = Math.max(buf.capacity() * 2, buf.position() + needed);
        ByteBuffer grown = allocateBuffer(next);
        buf.flip();
        grown.put(buf);
        recycleBuffer(buf);
        buf = grown;
    }

    void writeBool(boolean v) { ensureCapacity(1); buf.put((byte) (v ? 1 : 0)); }
    void writeI8(byte v) { ensureCapacity(1); buf.put(v); }
    void writeI16(short v) { ensureCapacity(2); buf.putShort(v); }
    void writeI32(int v) { ensureCapacity(4); buf.putInt(v); }
    void writeI64(long v) { ensureCapacity(8); buf.putLong(v); }
    void writeF32(float v) { ensureCapacity(4); buf.putFloat(v); }
    void writeF64(double v) { ensureCapacity(8); buf.putDouble(v); }

    @FunctionalInterface
    interface RawBytesWriter {
        void write(ByteBuffer buffer, int baseOffset);
    }

    void writeRawBytes(int byteCount, RawBytesWriter writer) {
        if (byteCount <= 0) return;
        ensureCapacity(byteCount);
        int baseOffset = buf.position();
        writer.write(buf, baseOffset);
        buf.position(baseOffset + byteCount);
    }

    void writeString(String v) {
        byte[] utf8 = v.getBytes(StandardCharsets.UTF_8);
        writeI32(utf8.length);
        ensureCapacity(utf8.length);
        buf.put(utf8);
    }

    void writeBytes(byte[] v) {
        writeI32(v.length);
        ensureCapacity(v.length);
        buf.put(v);
    }

    void writeBooleanArray(boolean[] v) {
        writeI32(v.length);
        ensureCapacity(v.length);
        for (boolean b : v) buf.put((byte) (b ? 1 : 0));
    }

    void writeByteArray(byte[] v) {
        writeI32(v.length);
        ensureCapacity(v.length);
        buf.put(v);
    }

    void writeShortArray(short[] v) {
        writeI32(v.length);
        int byteCount = v.length * 2;
        ensureCapacity(byteCount);
        buf.asShortBuffer().put(v);
        buf.position(buf.position() + byteCount);
    }

    void writeIntArray(int[] v) {
        writeI32(v.length);
        int byteCount = v.length * 4;
        ensureCapacity(byteCount);
        buf.asIntBuffer().put(v);
        buf.position(buf.position() + byteCount);
    }

    void writeLongArray(long[] v) {
        writeI32(v.length);
        int byteCount = v.length * 8;
        ensureCapacity(byteCount);
        buf.asLongBuffer().put(v);
        buf.position(buf.position() + byteCount);
    }

    void writeFloatArray(float[] v) {
        writeI32(v.length);
        int byteCount = v.length * 4;
        ensureCapacity(byteCount);
        buf.asFloatBuffer().put(v);
        buf.position(buf.position() + byteCount);
    }

    void writeDoubleArray(double[] v) {
        writeI32(v.length);
        int byteCount = v.length * 8;
        ensureCapacity(byteCount);
        buf.asDoubleBuffer().put(v);
        buf.position(buf.position() + byteCount);
    }

    static int stringWireSize(String v) {
        return 4 + (v.length() * 3);
    }

    static int vecLength(List<?> v) {
        return v.size();
    }

    static int vecLength(boolean[] v) {
        return v.length;
    }

    static int vecLength(byte[] v) {
        return v.length;
    }

    static int vecLength(short[] v) {
        return v.length;
    }

    static int vecLength(int[] v) {
        return v.length;
    }

    static int vecLength(long[] v) {
        return v.length;
    }

    static int vecLength(float[] v) {
        return v.length;
    }

    static int vecLength(double[] v) {
        return v.length;
    }

    static <T> int listWireSize(List<T> list, java.util.function.ToIntFunction<T> sizer) {
        int total = 4;
        for (T item : list) total += sizer.applyAsInt(item);
        return total;
    }

    static <T> boolean listEquals(
        List<T> left,
        List<T> right,
        java.util.function.BiPredicate<T, T> itemEquals
    ) {
        if (left == right) return true;
        if (left == null || right == null) return false;
        if (left.size() != right.size()) return false;
        for (int index = 0; index < left.size(); index++) {
            if (!itemEquals.test(left.get(index), right.get(index))) return false;
        }
        return true;
    }

    static <T> int listHash(List<T> values, java.util.function.ToIntFunction<T> itemHash) {
        if (values == null) return 0;
        int result = 1;
        for (T value : values) {
            result = 31 * result + itemHash.applyAsInt(value);
        }
        return result;
    }

    @Override
    public void close() {
        if (closed) return;
        closed = true;
        recycleBuffer(buf);
        buf = null;
    }

    private static ByteBuffer takeBuffer(int requestedCapacity) {
        int requiredCapacity = Math.max(requestedCapacity, MIN_CAPACITY);
        ArrayDeque<ByteBuffer> pool = POOL.get();
        int remaining = pool.size();
        while (remaining-- > 0) {
            ByteBuffer candidate = pool.pollFirst();
            if (candidate.capacity() >= requiredCapacity) {
                candidate.clear();
                candidate.order(ByteOrder.LITTLE_ENDIAN);
                return candidate;
            }
            pool.offerLast(candidate);
        }
        return allocateBuffer(requiredCapacity);
    }

    private static ByteBuffer allocateBuffer(int capacity) {
        return ByteBuffer.allocateDirect(capacity).order(ByteOrder.LITTLE_ENDIAN);
    }

    private static void recycleBuffer(ByteBuffer buffer) {
        if (buffer == null) return;
        if (buffer.capacity() > MAX_POOLED_CAPACITY) return;
        ArrayDeque<ByteBuffer> pool = POOL.get();
        if (pool.size() >= MAX_POOLED_BUFFERS_PER_THREAD) return;
        buffer.clear();
        buffer.order(ByteOrder.LITTLE_ENDIAN);
        pool.offerFirst(buffer);
    }
}

final class BoltFFIResult<Ok, Err> {
    private final Ok okValue;
    private final Err errValue;
    private final boolean ok;

    private BoltFFIResult(Ok okValue, Err errValue, boolean ok) {
        this.okValue = okValue;
        this.errValue = errValue;
        this.ok = ok;
    }

    static <Ok, Err> BoltFFIResult<Ok, Err> ok(Ok value) {
        return new BoltFFIResult<>(value, null, true);
    }

    static <Ok, Err> BoltFFIResult<Ok, Err> err(Err value) {
        return new BoltFFIResult<>(null, value, false);
    }

    boolean isOk() {
        return ok;
    }

    Ok okValue() {
        return okValue;
    }

    Err errValue() {
        return errValue;
    }
}final class Native {
    static {
        String preferredLibrary = "syncular_runtime_jni";
        String fallbackLibrary = "syncular_runtime";
        String vmName = System.getProperty("java.vm.name");
        if (vmName == null) vmName = "";
        boolean isAndroidRuntime =
            vmName.toLowerCase().contains("dalvik") ||
            vmName.toLowerCase().contains("art");
        if (isAndroidRuntime) {
            System.loadLibrary(fallbackLibrary);
        } else {
            loadDesktopLibraries(preferredLibrary, fallbackLibrary);
        }
    }

    private Native() {}
    private static volatile java.io.File bundledLibraryDirectory;

    private static void loadDesktopLibraries(String preferredLibrary, String fallbackLibrary) {
        UnsatisfiedLinkError preferredFailure = tryLoadDesktopLibrary(preferredLibrary);
        if (preferredFailure == null) {
            return;
        }

        if (tryLoadOptionalDesktopLibrary(fallbackLibrary)) {
            preferredFailure = tryLoadDesktopLibrary(preferredLibrary);
            if (preferredFailure == null) {
                return;
            }
        }

        throw preferredFailure;
    }

    private static UnsatisfiedLinkError tryLoadDesktopLibrary(String libraryName) {
        try {
            if (loadBundledLibraryIfPresent(libraryName) || loadExternalLibraryIfPresent(libraryName)) {
                return null;
            }
            return new UnsatisfiedLinkError("Could not load native library '" + libraryName + "'");
        } catch (UnsatisfiedLinkError error) {
            return error;
        }
    }

    private static boolean tryLoadOptionalDesktopLibrary(String libraryName) {
        try {
            return loadBundledLibraryIfPresent(libraryName) || loadExternalLibraryIfPresent(libraryName);
        } catch (UnsatisfiedLinkError ignored) {
            return false;
        }
    }

    private static boolean loadExternalLibraryIfPresent(String libraryName) {
        try {
            System.loadLibrary(libraryName);
            return true;
        } catch (UnsatisfiedLinkError ignored) {
            return false;
        }
    }

    private static boolean loadBundledLibraryIfPresent(String libraryName) {
        String mappedName = System.mapLibraryName(libraryName);
        for (String resourcePath : bundledLibraryResourceCandidates(mappedName)) {
            try (java.io.InputStream input = Native.class.getResourceAsStream(resourcePath)) {
                if (input == null) continue;
                java.io.File extracted = extractBundledLibrary(resourcePath, input);
                System.load(extracted.getAbsolutePath());
                return true;
            } catch (java.io.IOException error) {
                throw new ExceptionInInitializerError(error);
            }
        }
        return false;
    }

    private static java.io.File extractBundledLibrary(
        String resourcePath,
        java.io.InputStream input
    ) throws java.io.IOException {
        String fileName = resourcePath.substring(resourcePath.lastIndexOf('/') + 1);
        java.io.File extracted = new java.io.File(bundledLibraryDirectory(), fileName);
        if (!extracted.isFile()) {
            copyBundledLibrary(input, extracted);
            extracted.deleteOnExit();
        }
        return extracted;
    }

    private static void copyBundledLibrary(
        java.io.InputStream input,
        java.io.File extracted
    ) throws java.io.IOException {
        try (java.io.OutputStream output = new java.io.FileOutputStream(extracted)) {
            byte[] buffer = new byte[8192];
            int read;
            while ((read = input.read(buffer)) != -1) {
                output.write(buffer, 0, read);
            }
        }
    }

    private static java.io.File bundledLibraryDirectory() throws java.io.IOException {
        java.io.File existing = bundledLibraryDirectory;
        if (existing != null) {
            return existing;
        }

        synchronized (Native.class) {
            if (bundledLibraryDirectory == null) {
                bundledLibraryDirectory = createBundledLibraryDirectory();
            }
            return bundledLibraryDirectory;
        }
    }

    private static java.io.File createBundledLibraryDirectory() throws java.io.IOException {
        java.io.File created = java.io.File.createTempFile("boltffi-native-", "");
        if (!created.delete() || !created.mkdir()) {
            throw new java.io.IOException("failed to create temp directory for bundled native extraction");
        }
        created.deleteOnExit();
        return created;
    }

    private static java.util.List<String> bundledLibraryResourceCandidates(String mappedName) {
        java.util.ArrayList<String> candidates = new java.util.ArrayList<>();
        for (String directory : desktopNativeDirectories()) {
            candidates.add("/" + directory + "/" + mappedName);
            candidates.add("/native/" + directory + "/" + mappedName);
        }
        candidates.add("/" + mappedName);
        return candidates;
    }

    private static java.util.List<String> desktopNativeDirectories() {
        String osName = System.getProperty("os.name", "").toLowerCase();
        String osArch = System.getProperty("os.arch", "").toLowerCase();

        if ((osName.contains("mac") || osName.contains("darwin"))
            && (osArch.equals("aarch64") || osArch.equals("arm64"))) {
            return java.util.Arrays.asList("darwin-arm64", "darwin-aarch64");
        }
        if ((osName.contains("mac") || osName.contains("darwin")) && osArch.equals("x86_64")) {
            return java.util.Arrays.asList("darwin-x86_64", "darwin-x86-64");
        }
        if (osName.contains("linux") && (osArch.equals("x86_64") || osArch.equals("amd64"))) {
            return java.util.Arrays.asList("linux-x86_64", "linux-x86-64");
        }
        if (osName.contains("linux") && (osArch.equals("aarch64") || osArch.equals("arm64"))) {
            return java.util.Arrays.asList("linux-aarch64", "linux-arm64");
        }
        if (osName.contains("windows") && (osArch.equals("x86_64") || osArch.equals("amd64"))) {
            return java.util.Arrays.asList("windows-x86_64", "windows-x86-64", "win32-x86_64");
        }

        return java.util.Collections.emptyList();
    }

    @SuppressWarnings("unused")
    static void boltffiFutureContinuationCallback(long handle, byte pollResult) {
    }

    static native void boltffi_free_string(long ptr);
    static native byte[] boltffi_last_error_message();
    static native byte[] boltffi_syncular_runtime_manifest_json();
    static native byte[] boltffi_syncular_take_last_open_error();
    static native byte[] boltffi_syncular_yjs_build_text_update_json(byte[] argsJson);
    static native byte[] boltffi_syncular_yjs_apply_text_updates_json(byte[] argsJson);
    static native byte[] boltffi_syncular_yjs_apply_envelope_to_payload_json(byte[] argsJson);
    static native byte[] boltffi_syncular_yjs_materialize_row_json(byte[] argsJson);
    static native byte[] boltffi_syncular_encryption_helper_json(byte[] method, byte[] argsJson);
    static native void boltffi_syncular_bolt_client_free(long handle);
    static native long boltffi_syncular_bolt_client_open(ByteBuffer config);
    static native long boltffi_syncular_bolt_client_open_async(ByteBuffer config);
    static native byte[] boltffi_syncular_bolt_client_open_command_id(long handle);
    static native byte[] boltffi_syncular_bolt_client_is_open_finished(long handle);
    static native byte[] boltffi_syncular_bolt_client_finish_open_timeout(long handle, long timeoutMs);
    static native byte[] boltffi_syncular_bolt_client_runtime_manifest_json(long handle);
    static native byte[] boltffi_syncular_bolt_client_set_auth_headers_json(long handle, byte[] headersJson);
    static native byte[] boltffi_syncular_bolt_client_set_subscriptions_json(long handle, byte[] subscriptionsJson);
    static native byte[] boltffi_syncular_bolt_client_force_subscriptions_bootstrap_json(long handle, byte[] subscriptionIdsJson);
    static native byte[] boltffi_syncular_bolt_client_reset_local_sync_state_json(long handle, byte[] requestJson);
    static native byte[] boltffi_syncular_bolt_client_set_field_encryption_json(long handle, byte[] configJson);
    static native byte[] boltffi_syncular_bolt_client_set_encrypted_crdt_json(long handle, byte[] configJson);
    static native byte[] boltffi_syncular_bolt_client_trigger_sync(long handle);
    static native byte[] boltffi_syncular_bolt_client_trigger_sync_websocket(long handle);
    static native byte[] boltffi_syncular_bolt_client_enqueue_sync_now(long handle);
    static native byte[] boltffi_syncular_bolt_client_enqueue_sync_websocket(long handle);
    static native byte[] boltffi_syncular_bolt_client_pause_sync_worker(long handle);
    static native byte[] boltffi_syncular_bolt_client_resume_sync_worker(long handle);
    static native byte[] boltffi_syncular_bolt_client_resume_from_background(long handle);
    static native byte[] boltffi_syncular_bolt_client_sync_worker_running(long handle);
    static native byte[] boltffi_syncular_bolt_client_start_realtime_worker(long handle);
    static native byte[] boltffi_syncular_bolt_client_stop_realtime_worker(long handle);
    static native byte[] boltffi_syncular_bolt_client_join_presence(long handle, byte[] scopeKey, ByteBuffer metadataJson);
    static native byte[] boltffi_syncular_bolt_client_leave_presence(long handle, byte[] scopeKey);
    static native byte[] boltffi_syncular_bolt_client_update_presence_metadata(long handle, byte[] scopeKey, byte[] metadataJson);
    static native byte[] boltffi_syncular_bolt_client_presence_json(long handle, byte[] scopeKey);
    static native byte[] boltffi_syncular_bolt_client_start_event_stream(long handle, long capacity);
    static native byte[] boltffi_syncular_bolt_client_next_event_json(long handle);
    static native byte[] boltffi_syncular_bolt_client_next_event_json_timeout(long handle, long timeoutMs);
    static native byte[] boltffi_syncular_bolt_client_close_event_stream(long handle);
    static native byte[] boltffi_syncular_bolt_client_apply_mutation_json(long handle, byte[] mutationJson, ByteBuffer localRowJson);
    static native byte[] boltffi_syncular_bolt_client_apply_leased_mutation_json(long handle, byte[] mutationJson, ByteBuffer localRowJson);
    static native byte[] boltffi_syncular_bolt_client_enqueue_mutation_json(long handle, byte[] mutationJson, ByteBuffer localRowJson);
    static native byte[] boltffi_syncular_bolt_client_enqueue_leased_mutation_json(long handle, byte[] mutationJson, ByteBuffer localRowJson);
    static native byte[] boltffi_syncular_bolt_client_enqueue_yjs_update_json(long handle, byte[] updateJson);
    static native byte[] boltffi_syncular_bolt_client_open_crdt_field_json(long handle, byte[] requestJson);
    static native byte[] boltffi_syncular_bolt_client_apply_crdt_field_text_json(long handle, byte[] requestJson);
    static native byte[] boltffi_syncular_bolt_client_apply_crdt_field_yjs_update_json(long handle, byte[] requestJson);
    static native byte[] boltffi_syncular_bolt_client_enqueue_crdt_field_yjs_update_json(long handle, byte[] requestJson);
    static native byte[] boltffi_syncular_bolt_client_enqueue_crdt_field_text_json(long handle, byte[] requestJson);
    static native byte[] boltffi_syncular_bolt_client_enqueue_crdt_field_compaction_json(long handle, byte[] requestJson);
    static native byte[] boltffi_syncular_bolt_client_materialize_crdt_field_json(long handle, byte[] requestJson);
    static native byte[] boltffi_syncular_bolt_client_crdt_document_snapshot_json(long handle, byte[] requestJson);
    static native byte[] boltffi_syncular_bolt_client_crdt_update_log_json(long handle, byte[] requestJson);
    static native byte[] boltffi_syncular_bolt_client_snapshot_crdt_field_state_vector_json(long handle, byte[] requestJson);
    static native byte[] boltffi_syncular_bolt_client_compact_crdt_field_json(long handle, byte[] requestJson);
    static native byte[] boltffi_syncular_bolt_client_apply_encrypted_crdt_update_json(long handle, byte[] requestJson);
    static native byte[] boltffi_syncular_bolt_client_enqueue_encrypted_crdt_update_json(long handle, byte[] requestJson);
    static native byte[] boltffi_syncular_bolt_client_apply_encrypted_crdt_checkpoint_json(long handle, byte[] requestJson);
    static native byte[] boltffi_syncular_bolt_client_enqueue_encrypted_crdt_checkpoint_json(long handle, byte[] requestJson);
    static native byte[] boltffi_syncular_bolt_client_list_table_json(long handle, byte[] table);
    static native byte[] boltffi_syncular_bolt_client_query_json(long handle, byte[] requestJson);
    static native byte[] boltffi_syncular_bolt_client_enqueue_refresh_snapshot_json(long handle, byte[] requestJson);
    static native byte[] boltffi_syncular_bolt_client_store_blob_file_json(long handle, byte[] path, ByteBuffer optionsJson);
    static native byte[] boltffi_syncular_bolt_client_enqueue_store_blob_file_json(long handle, byte[] path, ByteBuffer optionsJson);
    static native byte[] boltffi_syncular_bolt_client_retrieve_blob_file_json(long handle, byte[] refJson, byte[] path, ByteBuffer optionsJson);
    static native byte[] boltffi_syncular_bolt_client_enqueue_retrieve_blob_file_json(long handle, byte[] refJson, byte[] path, ByteBuffer optionsJson);
    static native byte[] boltffi_syncular_bolt_client_is_blob_local(long handle, byte[] hash);
    static native byte[] boltffi_syncular_bolt_client_process_blob_upload_queue_json(long handle);
    static native byte[] boltffi_syncular_bolt_client_enqueue_process_blob_upload_queue(long handle);
    static native byte[] boltffi_syncular_bolt_client_blob_upload_queue_stats_json(long handle);
    static native byte[] boltffi_syncular_bolt_client_blob_cache_stats_json(long handle);
    static native byte[] boltffi_syncular_bolt_client_prune_blob_cache(long handle, long maxBytes);
    static native byte[] boltffi_syncular_bolt_client_enqueue_prune_blob_cache(long handle, long maxBytes);
    static native byte[] boltffi_syncular_bolt_client_clear_blob_cache(long handle);
    static native byte[] boltffi_syncular_bolt_client_enqueue_clear_blob_cache(long handle);
    static native byte[] boltffi_syncular_bolt_client_compact_storage_json(long handle, ByteBuffer optionsJson);
    static native byte[] boltffi_syncular_bolt_client_enqueue_compact_storage_json(long handle, ByteBuffer optionsJson);
    static native byte[] boltffi_syncular_bolt_client_app_tables_json(long handle);
    static native byte[] boltffi_syncular_bolt_client_app_table_metadata_json(long handle);
    static native byte[] boltffi_syncular_bolt_client_app_schema_state_json(long handle);
    static native byte[] boltffi_syncular_bolt_client_register_query_json(long handle, byte[] queryJson);
    static native byte[] boltffi_syncular_bolt_client_unregister_query(long handle, byte[] id);
    static native byte[] boltffi_syncular_bolt_client_observed_queries_json(long handle);
    static native byte[] boltffi_syncular_bolt_client_diagnostic_snapshot_json(long handle);
    static native byte[] boltffi_syncular_bolt_client_local_health_check_json(long handle);
    static native byte[] boltffi_syncular_bolt_client_export_local_support_bundle_json(long handle);
    static native byte[] boltffi_syncular_bolt_client_import_local_support_bundle_json(long handle, byte[] bundleJson);
    static native byte[] boltffi_syncular_bolt_client_repair_local_health_json(long handle, byte[] requestJson);
    static native byte[] boltffi_syncular_bolt_client_outbox_summaries_json(long handle);
    static native byte[] boltffi_syncular_bolt_client_upsert_auth_lease_json(long handle, byte[] leaseJson);
    static native byte[] boltffi_syncular_bolt_client_issue_auth_lease_json(long handle, byte[] requestJson);
    static native byte[] boltffi_syncular_bolt_client_auth_lease_json(long handle, byte[] leaseId);
    static native byte[] boltffi_syncular_bolt_client_active_auth_leases_json(long handle, ByteBuffer actorId, long nowMs);
    static native byte[] boltffi_syncular_bolt_client_set_outbox_auth_lease_json(long handle, byte[] clientCommitId, ByteBuffer provenanceJson);
    static native byte[] boltffi_syncular_bolt_client_conflict_summaries_json(long handle);
    static native byte[] boltffi_syncular_bolt_client_resolve_conflict(long handle, byte[] id, byte[] resolution);
    static native byte[] boltffi_syncular_bolt_client_enqueue_resolve_conflict(long handle, byte[] id, byte[] resolution);
    static native byte[] boltffi_syncular_bolt_client_retry_conflict_keep_local(long handle, byte[] id);
    static native byte[] boltffi_syncular_bolt_client_shutdown(long handle);
}
public final class Syncular {
    private Syncular() {}

    public static String syncularRuntimeManifestJson() {
        byte[] _buf = Native.boltffi_syncular_runtime_manifest_json();
        if (_buf == null) throw new RuntimeException("FFI call returned null buffer");
        WireReader reader = new WireReader(_buf);
        if (reader.readI8() != 0) {
            throw new RuntimeException(reader.readString());
        }
        return reader.readString();
    }

    public static java.util.Optional<String> syncularTakeLastOpenError() {
        byte[] _buf = Native.boltffi_syncular_take_last_open_error();
        if (_buf == null) throw new RuntimeException("FFI call returned null buffer");
        WireReader reader = new WireReader(_buf);
        return reader.readI8() == 0 ? java.util.Optional.empty() : java.util.Optional.ofNullable(reader.readString());
    }

    public static String syncularYjsBuildTextUpdateJson(String argsJson) {
        byte[] _buf = Native.boltffi_syncular_yjs_build_text_update_json(argsJson.getBytes(java.nio.charset.StandardCharsets.UTF_8));
        if (_buf == null) throw new RuntimeException("FFI call returned null buffer");
        WireReader reader = new WireReader(_buf);
        if (reader.readI8() != 0) {
            throw new RuntimeException(reader.readString());
        }
        return reader.readString();
    }

    public static String syncularYjsApplyTextUpdatesJson(String argsJson) {
        byte[] _buf = Native.boltffi_syncular_yjs_apply_text_updates_json(argsJson.getBytes(java.nio.charset.StandardCharsets.UTF_8));
        if (_buf == null) throw new RuntimeException("FFI call returned null buffer");
        WireReader reader = new WireReader(_buf);
        if (reader.readI8() != 0) {
            throw new RuntimeException(reader.readString());
        }
        return reader.readString();
    }

    public static String syncularYjsApplyEnvelopeToPayloadJson(String argsJson) {
        byte[] _buf = Native.boltffi_syncular_yjs_apply_envelope_to_payload_json(argsJson.getBytes(java.nio.charset.StandardCharsets.UTF_8));
        if (_buf == null) throw new RuntimeException("FFI call returned null buffer");
        WireReader reader = new WireReader(_buf);
        if (reader.readI8() != 0) {
            throw new RuntimeException(reader.readString());
        }
        return reader.readString();
    }

    public static String syncularYjsMaterializeRowJson(String argsJson) {
        byte[] _buf = Native.boltffi_syncular_yjs_materialize_row_json(argsJson.getBytes(java.nio.charset.StandardCharsets.UTF_8));
        if (_buf == null) throw new RuntimeException("FFI call returned null buffer");
        WireReader reader = new WireReader(_buf);
        if (reader.readI8() != 0) {
            throw new RuntimeException(reader.readString());
        }
        return reader.readString();
    }

    public static String syncularEncryptionHelperJson(String method, String argsJson) {
        byte[] _buf = Native.boltffi_syncular_encryption_helper_json(method.getBytes(java.nio.charset.StandardCharsets.UTF_8), argsJson.getBytes(java.nio.charset.StandardCharsets.UTF_8));
        if (_buf == null) throw new RuntimeException("FFI call returned null buffer");
        WireReader reader = new WireReader(_buf);
        if (reader.readI8() != 0) {
            throw new RuntimeException(reader.readString());
        }
        return reader.readString();
    }
}
