// Generated by @syncular/typegen — DO NOT EDIT.
// irVersion: 1
// irHash: sha256:05e3151ae198a4fb7eb768ecc5e226fcd844b19abb3d04b7f4185865161e76ab

/** A bindable SQL param/row value (the wrapper's SqlValue subset). */
export type QueryValue =
  | string
  | number
  | bigint
  | boolean
  | Uint8Array
  | null;

/** Minimal structural client surface — the wrapper's positional
 *  `query(sql, params?)`. `SyncClient`/`SyncClientHandle`/`SyncClientLike`
 *  all satisfy it, so this module imports nothing. */
export interface QueryClient {
  query(
    sql: string,
    params?: readonly QueryValue[],
  ): unknown[] | Promise<unknown[]>;
}

/** A named-query descriptor — checked SQL plus revisioned reactive metadata and a
 *  `bind(params)` → positional args. Consumed by
 *  `@syncular/react`'s `useQuery`. `Row` is the projection row
 *  type; `Params` is `undefined` for a param-less query. `sqlFor`
 *  (present only with an orderBy knob) composes the statement from a
 *  generate-time-checked column allowlist. */
export interface NamedQuery<Row, Params = undefined> {
  readonly id: string;
  readonly hasParams: boolean;
  readonly sql: string;
  readonly tables: readonly string[];
  readonly bind: (params: Params) => readonly QueryValue[];
  readonly sqlFor?: (params: Params) => string;
  readonly dependencies: (params: Params) => readonly QueryDependency[];
  readonly coverage: (params: Params) => readonly WindowCoverage[];
  readonly rowKey?: (row: Row) => readonly QueryValue[];
  /** Phantom — carries the Row type for `useQuery` inference. */
  readonly __row?: Row;
}

export interface QueryDependency {
  readonly table: string;
  readonly scopeKeys?: readonly string[];
}

export interface WindowCoverage {
  readonly base: {
    readonly table: string;
    readonly variable: string;
    readonly fixedScopes?: Readonly<Record<string, readonly string[]>>;
    readonly params?: string;
  };
  readonly units: readonly string[];
}

/** One row of the 'listTodos' query (its projection). */
export interface ListTodosRow {
  id: string;
  listId: string;
  title: string;
  done: boolean;
  position: number;
  updatedAtMs: number;
  attachment: string | null;
}

/** Named parameters for 'listTodos'. */
export interface ListTodosParams {
  listId: string;
  q?: string | null;
}

/** Tables 'listTodos' reads (compatibility/export surface). */
export const listTodosTables = ['todos'] as const;

const listTodosSql = 'select id, list_id AS listId, title, done, position, updated_at_ms AS updatedAtMs, attachment from todos where list_id = ?1 and (?2 is null or (title like \'%\' || ?2 || \'%\')) order by position, id';

/** Run the 'listTodos' named query (SELECT-only). */
export async function listTodos(client: QueryClient, params: ListTodosParams): Promise<ListTodosRow[]> {
  const rows = await client.query(listTodosSql, [params.listId, params.q ?? null]);
  return rows as unknown as ListTodosRow[];
}

/** Revisioned reactive descriptor for `useQuery(listTodosQuery, params)`. */
export const listTodosQuery: NamedQuery<ListTodosRow, ListTodosParams> = {
  id: 'sha256:05e3151ae198a4fb7eb768ecc5e226fcd844b19abb3d04b7f4185865161e76ab/listTodos',
  hasParams: true,
  sql: listTodosSql,
  tables: listTodosTables,
  dependencies: (params) => [
    { table: 'todos', scopeKeys: ['list:' + String(params.listId) + ''] },
  ],
  coverage: (params) => [
    { base: { table: 'todos', variable: 'list_id' }, units: [String(params.listId)] },
  ],
  bind: (params: ListTodosParams) => [params.listId, params.q ?? null],
  rowKey: (row) => [row.id],
};
