// Generated by @syncular/typegen — DO NOT EDIT.
// irVersion: 1
// irHash: sha256:8b4e2f0a7924bb38d7c896965cafff4a083fbfe61276ccb09cf3b258193090b4

/** Structural descriptor consumed by renderer bindings; phantom type
 * fields make row/insert/update/id inference available without imports. */
export interface SyncTable<Row, Insert, Update, Id> {
  readonly name: string;
  /** Language-facing key used in generated row and mutation types. */
  readonly primaryKey: keyof Row & string;
  /** Physical SQLite/wire primary-key column. */
  readonly physicalPrimaryKey: string;
  readonly __row?: Row;
  readonly __insert?: Insert;
  readonly __update?: Update;
  readonly __id?: Id;
}

/** ServerSchema-compatible schema object (SPEC §2.4, §3.1). */
export const schema = {
  version: 1,
  tables: [
    {
      name: 'boards',
      columns: [
        { name: 'id', type: 'string', nullable: false },
        { name: 'board_id', type: 'string', nullable: false },
        { name: 'name', type: 'string', nullable: false },
        { name: 'color', type: 'string', nullable: false },
      ],
      primaryKey: 'id',
      scopes: [
        { pattern: 'board:{board_id}', column: 'board_id' },
      ],
    },
    {
      name: 'members',
      columns: [
        { name: 'id', type: 'string', nullable: false },
        { name: 'board_id', type: 'string', nullable: false },
        { name: 'user_id', type: 'string', nullable: false },
        { name: 'name', type: 'string', nullable: false },
        { name: 'color', type: 'string', nullable: false },
        { name: 'role', type: 'string', nullable: false },
      ],
      primaryKey: 'id',
      scopes: [
        { pattern: 'board:{board_id}', column: 'board_id' },
      ],
      references: [
        { column: 'board_id', parentTable: 'boards', onDelete: 'RESTRICT' },
      ],
      indexes: [
        { name: 'idx_members_board_id_ref', columns: ['board_id'], unique: false },
      ],
    },
    {
      name: 'labels',
      columns: [
        { name: 'id', type: 'string', nullable: false },
        { name: 'board_id', type: 'string', nullable: false },
        { name: 'name', type: 'string', nullable: false },
        { name: 'color', type: 'string', nullable: false },
      ],
      primaryKey: 'id',
      scopes: [
        { pattern: 'board:{board_id}', column: 'board_id' },
      ],
      references: [
        { column: 'board_id', parentTable: 'boards', onDelete: 'RESTRICT' },
      ],
      indexes: [
        { name: 'idx_labels_board_id_ref', columns: ['board_id'], unique: false },
      ],
    },
    {
      name: 'cards',
      columns: [
        { name: 'id', type: 'string', nullable: false },
        { name: 'board_id', type: 'string', nullable: false },
        { name: 'column_id', type: 'string', nullable: false },
        { name: 'position', type: 'integer', nullable: false },
        { name: 'title', type: 'string', nullable: false },
        { name: 'assignee_id', type: 'string', nullable: true },
        { name: 'estimate', type: 'integer', nullable: false },
        { name: 'created_at_ms', type: 'integer', nullable: false },
        { name: 'updated_at_ms', type: 'integer', nullable: false },
      ],
      primaryKey: 'id',
      scopes: [
        { pattern: 'board:{board_id}', column: 'board_id' },
      ],
      references: [
        { column: 'board_id', parentTable: 'boards', onDelete: 'RESTRICT' },
        { column: 'assignee_id', parentTable: 'members', onDelete: 'SET NULL' },
      ],
      indexes: [
        { name: 'idx_cards_board_id_ref', columns: ['board_id'], unique: false },
        { name: 'idx_cards_assignee_id_ref', columns: ['assignee_id'], unique: false },
        { name: 'cards_by_column', columns: ['board_id', 'column_id', 'position'], unique: false },
      ],
    },
    {
      name: 'card_labels',
      columns: [
        { name: 'id', type: 'string', nullable: false },
        { name: 'card_id', type: 'string', nullable: false },
        { name: 'label_id', type: 'string', nullable: false },
        { name: 'board_id', type: 'string', nullable: false },
      ],
      primaryKey: 'id',
      scopes: [
        { pattern: 'board:{board_id}', column: 'board_id' },
      ],
      references: [
        { column: 'card_id', parentTable: 'cards', onDelete: 'CASCADE' },
        { column: 'label_id', parentTable: 'labels', onDelete: 'CASCADE' },
        { column: 'board_id', parentTable: 'boards', onDelete: 'RESTRICT' },
      ],
      indexes: [
        { name: 'idx_card_labels_card_id_ref', columns: ['card_id'], unique: false },
        { name: 'idx_card_labels_label_id_ref', columns: ['label_id'], unique: false },
        { name: 'idx_card_labels_board_id_ref', columns: ['board_id'], unique: false },
      ],
    },
    {
      name: 'comments',
      columns: [
        { name: 'id', type: 'string', nullable: false },
        { name: 'card_id', type: 'string', nullable: false },
        { name: 'board_id', type: 'string', nullable: false },
        { name: 'author_id', type: 'string', nullable: false },
        { name: 'body', type: 'string', nullable: false },
        { name: 'created_at_ms', type: 'integer', nullable: false },
      ],
      primaryKey: 'id',
      scopes: [
        { pattern: 'board:{board_id}', column: 'board_id' },
      ],
      references: [
        { column: 'card_id', parentTable: 'cards', onDelete: 'CASCADE' },
        { column: 'board_id', parentTable: 'boards', onDelete: 'RESTRICT' },
        { column: 'author_id', parentTable: 'members', onDelete: 'RESTRICT' },
      ],
      indexes: [
        { name: 'idx_comments_card_id_ref', columns: ['card_id'], unique: false },
        { name: 'idx_comments_board_id_ref', columns: ['board_id'], unique: false },
        { name: 'idx_comments_author_id_ref', columns: ['author_id'], unique: false },
        { name: 'comments_by_card', columns: ['card_id', 'created_at_ms'], unique: false },
      ],
    },
  ],
} as const;

/** One boards row (§2.4 column order). */
export interface BoardsRow {
  id: string;
  boardId: string;
  name: string;
  color: string;
}

/** Insert shape: nullable columns may be omitted. */
export interface BoardsInsert {
  id: string;
  boardId: string;
  name: string;
  color: string;
}

/** Update shape: primary key required, all other columns optional. */
export interface BoardsUpdate {
  id: string;
  boardId?: string;
  name?: string;
  color?: string;
}

/** Typed mutation/resource descriptor for 'boards'. */
export const boardsTable: SyncTable<BoardsRow, BoardsInsert, BoardsUpdate, string> = {
  name: 'boards',
  primaryKey: 'id',
  physicalPrimaryKey: 'id',
};

/** One members row (§2.4 column order). */
export interface MembersRow {
  id: string;
  boardId: string;
  userId: string;
  name: string;
  color: string;
  role: string;
}

/** Insert shape: nullable columns may be omitted. */
export interface MembersInsert {
  id: string;
  boardId: string;
  userId: string;
  name: string;
  color: string;
  role: string;
}

/** Update shape: primary key required, all other columns optional. */
export interface MembersUpdate {
  id: string;
  boardId?: string;
  userId?: string;
  name?: string;
  color?: string;
  role?: string;
}

/** Typed mutation/resource descriptor for 'members'. */
export const membersTable: SyncTable<MembersRow, MembersInsert, MembersUpdate, string> = {
  name: 'members',
  primaryKey: 'id',
  physicalPrimaryKey: 'id',
};

/** One labels row (§2.4 column order). */
export interface LabelsRow {
  id: string;
  boardId: string;
  name: string;
  color: string;
}

/** Insert shape: nullable columns may be omitted. */
export interface LabelsInsert {
  id: string;
  boardId: string;
  name: string;
  color: string;
}

/** Update shape: primary key required, all other columns optional. */
export interface LabelsUpdate {
  id: string;
  boardId?: string;
  name?: string;
  color?: string;
}

/** Typed mutation/resource descriptor for 'labels'. */
export const labelsTable: SyncTable<LabelsRow, LabelsInsert, LabelsUpdate, string> = {
  name: 'labels',
  primaryKey: 'id',
  physicalPrimaryKey: 'id',
};

/** One cards row (§2.4 column order). */
export interface CardsRow {
  id: string;
  boardId: string;
  columnId: string;
  position: number;
  title: string;
  assigneeId: string | null;
  estimate: number;
  createdAtMs: number;
  updatedAtMs: number;
}

/** Insert shape: nullable columns may be omitted. */
export interface CardsInsert {
  id: string;
  boardId: string;
  columnId: string;
  position: number;
  title: string;
  assigneeId?: string | null;
  estimate: number;
  createdAtMs: number;
  updatedAtMs: number;
}

/** Update shape: primary key required, all other columns optional. */
export interface CardsUpdate {
  id: string;
  boardId?: string;
  columnId?: string;
  position?: number;
  title?: string;
  assigneeId?: string | null;
  estimate?: number;
  createdAtMs?: number;
  updatedAtMs?: number;
}

/** Typed mutation/resource descriptor for 'cards'. */
export const cardsTable: SyncTable<CardsRow, CardsInsert, CardsUpdate, string> = {
  name: 'cards',
  primaryKey: 'id',
  physicalPrimaryKey: 'id',
};

/** One card_labels row (§2.4 column order). */
export interface CardLabelsRow {
  id: string;
  cardId: string;
  labelId: string;
  boardId: string;
}

/** Insert shape: nullable columns may be omitted. */
export interface CardLabelsInsert {
  id: string;
  cardId: string;
  labelId: string;
  boardId: string;
}

/** Update shape: primary key required, all other columns optional. */
export interface CardLabelsUpdate {
  id: string;
  cardId?: string;
  labelId?: string;
  boardId?: string;
}

/** Typed mutation/resource descriptor for 'card_labels'. */
export const cardLabelsTable: SyncTable<CardLabelsRow, CardLabelsInsert, CardLabelsUpdate, string> = {
  name: 'card_labels',
  primaryKey: 'id',
  physicalPrimaryKey: 'id',
};

/** One comments row (§2.4 column order). */
export interface CommentsRow {
  id: string;
  cardId: string;
  boardId: string;
  authorId: string;
  body: string;
  createdAtMs: number;
}

/** Insert shape: nullable columns may be omitted. */
export interface CommentsInsert {
  id: string;
  cardId: string;
  boardId: string;
  authorId: string;
  body: string;
  createdAtMs: number;
}

/** Update shape: primary key required, all other columns optional. */
export interface CommentsUpdate {
  id: string;
  cardId?: string;
  boardId?: string;
  authorId?: string;
  body?: string;
  createdAtMs?: number;
}

/** Typed mutation/resource descriptor for 'comments'. */
export const commentsTable: SyncTable<CommentsRow, CommentsInsert, CommentsUpdate, string> = {
  name: 'comments',
  primaryKey: 'id',
  physicalPrimaryKey: 'id',
};

export interface BoardBoardsParams {
  boardId: string;
}

/** Requested-scope template for the 'boardBoards' subscription. */
export const boardBoardsSubscription = {
  name: 'boardBoards',
  table: 'boards',
  scopes: (params: BoardBoardsParams): Record<string, string[]> => ({
    board_id: [params.boardId],
  }),
} as const;

export interface BoardMembersParams {
  boardId: string;
}

/** Requested-scope template for the 'boardMembers' subscription. */
export const boardMembersSubscription = {
  name: 'boardMembers',
  table: 'members',
  scopes: (params: BoardMembersParams): Record<string, string[]> => ({
    board_id: [params.boardId],
  }),
} as const;

export interface BoardLabelsParams {
  boardId: string;
}

/** Requested-scope template for the 'boardLabels' subscription. */
export const boardLabelsSubscription = {
  name: 'boardLabels',
  table: 'labels',
  scopes: (params: BoardLabelsParams): Record<string, string[]> => ({
    board_id: [params.boardId],
  }),
} as const;

export interface BoardCardsParams {
  boardId: string;
}

/** Requested-scope template for the 'boardCards' subscription. */
export const boardCardsSubscription = {
  name: 'boardCards',
  table: 'cards',
  scopes: (params: BoardCardsParams): Record<string, string[]> => ({
    board_id: [params.boardId],
  }),
} as const;

export interface BoardCardLabelsParams {
  boardId: string;
}

/** Requested-scope template for the 'boardCardLabels' subscription. */
export const boardCardLabelsSubscription = {
  name: 'boardCardLabels',
  table: 'card_labels',
  scopes: (params: BoardCardLabelsParams): Record<string, string[]> => ({
    board_id: [params.boardId],
  }),
} as const;

export interface BoardCommentsParams {
  boardId: string;
}

/** Requested-scope template for the 'boardComments' subscription. */
export const boardCommentsSubscription = {
  name: 'boardComments',
  table: 'comments',
  scopes: (params: BoardCommentsParams): Record<string, string[]> => ({
    board_id: [params.boardId],
  }),
} as const;
