/**
 * Golden-file tests for the native emitters (Swift/Kotlin/Dart), mirroring
 * the TS golden: the committed fixtures are the snapshots; regeneration must
 * reproduce them byte-exactly and deterministically, and each carries the
 * DO-NOT-EDIT header + IR hash so `--check` gates freshness per language.
 */
import { describe, expect, test } from 'bun:test';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { checkOutputs, generate } from '../src';

const FIXTURE = join(import.meta.dir, 'fixtures', 'basic');

/** The native outputs the fixture manifest opts into, by basename. */
const NATIVE_FILES = {
  swift: 'Syncular.generated.swift',
  kotlin: 'Syncular.generated.kt',
  dart: 'syncular.generated.dart',
} as const;

function outputFor(basename: string): string {
  const result = generate(FIXTURE);
  const output = result.outputs.find((o) => o.path.endsWith(`/${basename}`));
  if (output === undefined) {
    throw new Error(`fixture did not emit ${basename}`);
  }
  return output.content;
}

describe('native emitter goldens', () => {
  for (const [lang, basename] of Object.entries(NATIVE_FILES)) {
    describe(lang, () => {
      test('snapshot matches byte-exactly', () => {
        const committed = readFileSync(join(FIXTURE, basename), 'utf8');
        expect(outputFor(basename)).toBe(committed);
      });

      test('two runs are byte-identical (determinism)', () => {
        expect(outputFor(basename)).toBe(outputFor(basename));
      });

      test('carries the DO-NOT-EDIT header + IR hash', () => {
        const content = outputFor(basename);
        expect(content.startsWith('// Generated by @syncular-v2/typegen')).toBe(
          true,
        );
        expect(content).toContain(`// irHash: ${generate(FIXTURE).hash}`);
        expect(content).toContain('// irVersion: 1');
      });
    });
  }

  test('generate emits IR + TS + all three native outputs (+ query files)', () => {
    const result = generate(FIXTURE);
    const names = result.outputs.map((o) => o.path.split('/').pop());
    // Schema outputs in a stable order; each language's queries file follows
    // its schema file when the manifest opts into named queries.
    expect(names).toEqual([
      'syncular.ir.json',
      'syncular.generated.ts',
      'syncular.queries.ts',
      NATIVE_FILES.swift,
      'Syncular.queries.swift',
      NATIVE_FILES.kotlin,
      'Syncular.queries.kt',
      NATIVE_FILES.dart,
      'syncular.queries.dart',
    ]);
  });

  test('checkOutputs covers the native files (no drift on committed)', () => {
    expect(checkOutputs(generate(FIXTURE))).toEqual([]);
  });

  test('Swift schema namespace + typed structs are present', () => {
    const swift = outputFor(NATIVE_FILES.swift);
    expect(swift).toContain('public enum BasicSchema {');
    expect(swift).toContain('public static let schema: JSONValue =');
    expect(swift).toContain('public struct Tasks: Sendable, Equatable {');
    expect(swift).toContain('public init?(row: [String: JSONValue]) {');
    // blob-ref/crdt honest shapes: crdt → [UInt8]; bytes → [UInt8].
    expect(swift).toContain('public let bodyDoc: [UInt8]?');
  });

  test('Kotlin package + data classes + fromRow are present', () => {
    const kotlin = outputFor(NATIVE_FILES.kotlin);
    expect(kotlin).toContain('package dev.syncular.basic');
    expect(kotlin).toContain('object BasicSchema {');
    expect(kotlin).toContain('data class Tasks(');
    expect(kotlin).toContain('fun fromRow(row: JsonValue): Tasks?');
    // integer → Long (honest JVM mapping).
    expect(kotlin).toContain('val priority: Long?');
  });

  test('Dart const schema + classes + subscriptions are present', () => {
    const dart = outputFor(NATIVE_FILES.dart);
    expect(dart).toContain(
      'const Map<String, Object?> syncularSchema = <String, Object?>{',
    );
    expect(dart).toContain('class Tasks {');
    expect(dart).toContain('static Tasks? fromRow(Map<String, Object?> row) {');
    expect(dart).toContain('class SyncularProjectTasksSubscription {');
  });
});
