/**
 * Golden-file tests: the committed fixture IR + generated module are the
 * snapshots; regeneration must reproduce them byte-exactly, twice.
 */
import { describe, expect, test } from 'bun:test';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { checkOutputs, generate, irHash } from '../src';

const FIXTURE = join(import.meta.dir, 'fixtures', 'basic');

describe('golden fixtures', () => {
  test('IR snapshot matches byte-exactly', () => {
    const result = generate(FIXTURE);
    const committed = readFileSync(join(FIXTURE, 'syncular.ir.json'), 'utf8');
    expect(result.irJson).toBe(committed);
  });

  test('generated module snapshot matches byte-exactly', () => {
    const result = generate(FIXTURE);
    const committed = readFileSync(
      join(FIXTURE, 'syncular.generated.ts'),
      'utf8',
    );
    expect(result.module).toBe(committed);
  });

  test('two runs are byte-identical (determinism)', () => {
    const first = generate(FIXTURE);
    const second = generate(FIXTURE);
    expect(first.irJson).toBe(second.irJson);
    expect(first.module).toBe(second.module);
    expect(first.hash).toBe(second.hash);
  });

  test('module header carries the IR hash', () => {
    const result = generate(FIXTURE);
    expect(result.hash).toBe(irHash(result.irJson));
    expect(result.module).toContain(`// irHash: ${result.hash}`);
    expect(result.module.startsWith('// Generated by')).toBe(true);
  });

  test('checkOutputs reports no drift for the committed fixture', () => {
    expect(checkOutputs(generate(FIXTURE))).toEqual([]);
  });

  test('IR shape: versioned, extension slots present, no TS types', () => {
    const ir = JSON.parse(generate(FIXTURE).irJson);
    expect(ir.irVersion).toBe(1);
    expect(ir.schemaVersion).toBe(3);
    expect(ir.extensions).toEqual({});
    expect(ir.tables[0].extensions).toEqual({});
    expect(ir.schemaVersions).toEqual([
      { version: 1, migrations: ['0001_initial'] },
      { version: 2, migrations: ['0002_add_task_estimate'] },
      { version: 3, migrations: ['0003_add_doc_crdt'] },
    ]);
    // §5.10.1: the CRDT keyword became a crdt column carrying a crdtType.
    const bodyDoc = ir.tables[1].columns.find(
      (c: { name: string }) => c.name === 'body_doc',
    );
    expect(bodyDoc).toEqual({
      name: 'body_doc',
      type: 'crdt',
      nullable: true,
      crdtType: 'yjs-doc',
    });
    // Scope patterns are pre-resolved for non-TS emitters.
    expect(ir.tables[1].scopes[1]).toEqual({
      pattern: 'project:{projectId}',
      variable: 'projectId',
      column: 'project_id',
    });
    // Subscription templates are structured, not TS-flavored strings.
    expect(ir.subscriptions[1].scopes).toEqual([
      { variable: 'org_id', values: [{ kind: 'literal', value: 'acme' }] },
      {
        variable: 'projectId',
        values: [{ kind: 'parameter', name: 'projectId' }],
      },
    ]);
  });
});
