// Generated by @syncular/typegen — DO NOT EDIT.
// irVersion: 1
// irHash: sha256:e2ab7513a95a05589cd85d01bb1ef36c52dea0788df2ff31bff8bb08d5f65009

import Foundation
import Syncular

/// Param-bind helpers shared by the generated query runners.
enum SyncularSchemaQueryBind {
    static func bytes(_ value: [UInt8]) -> JSONValue {
        let hex = value.map { String(format: "%02x", $0) }.joined()
        return .object(["$bytes": .string(hex)])
    }
}

/// One row of the listNotes query (its projection).
public struct ListNotesRow: Sendable, Equatable {
    public let id: String
    public let listId: String
    public let body: String
    public let updatedAtMs: Int

    public init?(row: [String: JSONValue]) {
        guard let id = row["id"]?.stringValue else { return nil }
        self.id = id
        guard let listId = row["listId"]?.stringValue else { return nil }
        self.listId = listId
        guard let body = row["body"]?.stringValue else { return nil }
        self.body = body
        guard let updatedAtMs = row["updatedAtMs"]?.numberValue.map(Int.init) else { return nil }
        self.updatedAtMs = updatedAtMs
    }
}

/// Typed named queries (the sqlc/SQLDelight tier).
public enum SyncularSchemaQueries {
    public static let listNotesTables = ["notes"]
    private static let listNotesSql = "SELECT id, list_id AS listId, body, updated_at_ms AS updatedAtMs FROM notes WHERE list_id = ? ORDER BY id"

    /// Run the listNotes named query (SELECT-only).
    public static func listNotes(client: SyncularClient, listId: String) throws -> [ListNotesRow] {
        let params: [JSONValue] = [.string(listId)]
        return try client.query(listNotesSql, params: params).compactMap { row in
            guard case let .object(fields) = row else { return nil }
            return ListNotesRow(row: fields)
        }
    }
}
