name: Release

on:
  workflow_run:
    workflows: ["Checks"]
    types: [completed]
    branches: [main, release]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

concurrency:
  group: release-${{ github.event.workflow_run.head_branch || github.ref_name }}
  cancel-in-progress: false

jobs:
  release:
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.ref }}
      - uses: ./.github/actions/setup-environment

      - name: Create version PR or publish
        uses: changesets/action@v1
        with:
          version: bun run version-packages
          # publish: ${{ (github.event.workflow_run.head_branch || github.ref_name) == 'main' && 'bun run release:next' || 'bun run release' }}
          publish: bun run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: "true"
